// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SFA.DAS.Payments.AcceptanceTests.EndToEnd.Tests.InconsistentSubmissionData
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Levy learner changes course details in ILR after payments made and adds eng & mat" +
        "hs - PV2-284")]
    public partial class LevyLearnerChangesCourseDetailsInILRAfterPaymentsMadeAndAddsEngMaths_PV2_284Feature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "PV2-284 Levy learner, adds English and Maths aim after payments made.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Levy learner changes course details in ILR after payments made and adds eng & mat" +
                    "hs - PV2-284", "\t\tAs a provider,\r\n\t\tI want a levy learner, where the course details have changed " +
                    "after payments have been made, to be paid the correct amount,\r\n\t\tSo that I am ac" +
                    "curately paid my apprenticeship provision - PV2-284", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Levy learner changes course details in ILR after payments made and adds eng & mat" +
            "hs - PV2-284")]
        [NUnit.Framework.TestCaseAttribute("R03/Current Academic Year", "8400", "8", null)]
        [NUnit.Framework.TestCaseAttribute("R04/Current Academic Year", "7800", "10", null)]
        [NUnit.Framework.TestCaseAttribute("R05/Current Academic Year", "7200", "12", null)]
        [NUnit.Framework.TestCaseAttribute("R06/Current Academic Year", "6600", "14", null)]
        [NUnit.Framework.TestCaseAttribute("R07/Current Academic Year", "6000", "16", null)]
        [NUnit.Framework.TestCaseAttribute("R08/Current Academic Year", "5400", "18", null)]
        [NUnit.Framework.TestCaseAttribute("R09/Current Academic Year", "4800", "20", null)]
        [NUnit.Framework.TestCaseAttribute("R10/Current Academic Year", "4200", "22", null)]
        [NUnit.Framework.TestCaseAttribute("R11/Current Academic Year", "3600", "24", null)]
        [NUnit.Framework.TestCaseAttribute("R12/Current Academic Year", "3000", "26", null)]
        public virtual void LevyLearnerChangesCourseDetailsInILRAfterPaymentsMadeAndAddsEngMaths_PV2_284(string collection_Period, string levyBalance, string expectedRequiredPayments, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Levy learner changes course details in ILR after payments made and adds eng & mat" +
                    "hs - PV2-284", null, exampleTags);
#line 9
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 10
 testRunner.Given(string.Format("the employer levy account balance in collection period {0} is {1}", collection_Period, levyBalance), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1079 = new TechTalk.SpecFlow.Table(new string[] {
                        "Identifier",
                        "start date",
                        "end date",
                        "agreed price",
                        "status",
                        "Framework Code",
                        "Pathway Code",
                        "Programme Type"});
            table1079.AddRow(new string[] {
                        "Apprenticeship 1",
                        "01/Aug/Current Academic Year",
                        "01/Aug/Next Academic Year",
                        "9000",
                        "active",
                        "593",
                        "1",
                        "20"});
#line 11
 testRunner.And("the following commitments exist", ((string)(null)), table1079, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1080 = new TechTalk.SpecFlow.Table(new string[] {
                        "Aim Type",
                        "Aim Reference",
                        "Start Date",
                        "Planned Duration",
                        "Actual Duration",
                        "Aim Sequence Number",
                        "Framework Code",
                        "Pathway Code",
                        "Programme Type",
                        "Funding Line Type",
                        "Completion Status"});
            table1080.AddRow(new string[] {
                        "Programme",
                        "ZPROG001",
                        "06/Aug/Current Academic Year",
                        "12 months",
                        "",
                        "1",
                        "593",
                        "1",
                        "20",
                        "19-24 Apprenticeship Levy",
                        "continuing"});
#line 14
 testRunner.And("the following aims", ((string)(null)), table1080, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1081 = new TechTalk.SpecFlow.Table(new string[] {
                        "Price Episode Id",
                        "Total Training Price",
                        "Total Training Price Effective Date",
                        "Contract Type",
                        "Aim Sequence Number",
                        "SFA Contribution Percentage"});
            table1081.AddRow(new string[] {
                        "pe-1",
                        "9000",
                        "06/Aug/Current Academic Year",
                        "Act1",
                        "1",
                        "90%"});
#line 17
 testRunner.And("price details as follows", ((string)(null)), table1081, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1082 = new TechTalk.SpecFlow.Table(new string[] {
                        "Delivery Period",
                        "On-Programme",
                        "Completion",
                        "Balancing",
                        "OnProgrammeMathsAndEnglish",
                        "Aim Sequence Number",
                        "Price Episode Identifier"});
            table1082.AddRow(new string[] {
                        "Aug/Current Academic Year",
                        "600",
                        "0",
                        "0",
                        "0",
                        "1",
                        "pe-1"});
            table1082.AddRow(new string[] {
                        "Sep/Current Academic Year",
                        "600",
                        "0",
                        "0",
                        "0",
                        "1",
                        "pe-1"});
            table1082.AddRow(new string[] {
                        "Oct/Current Academic Year",
                        "600",
                        "0",
                        "0",
                        "0",
                        "1",
                        "pe-1"});
            table1082.AddRow(new string[] {
                        "Nov/Current Academic Year",
                        "600",
                        "0",
                        "0",
                        "0",
                        "1",
                        "pe-1"});
            table1082.AddRow(new string[] {
                        "Dec/Current Academic Year",
                        "600",
                        "0",
                        "0",
                        "0",
                        "1",
                        "pe-1"});
            table1082.AddRow(new string[] {
                        "Jan/Current Academic Year",
                        "600",
                        "0",
                        "0",
                        "0",
                        "1",
                        "pe-1"});
            table1082.AddRow(new string[] {
                        "Feb/Current Academic Year",
                        "600",
                        "0",
                        "0",
                        "0",
                        "1",
                        "pe-1"});
            table1082.AddRow(new string[] {
                        "Mar/Current Academic Year",
                        "600",
                        "0",
                        "0",
                        "0",
                        "1",
                        "pe-1"});
            table1082.AddRow(new string[] {
                        "Apr/Current Academic Year",
                        "600",
                        "0",
                        "0",
                        "0",
                        "1",
                        "pe-1"});
            table1082.AddRow(new string[] {
                        "May/Current Academic Year",
                        "600",
                        "0",
                        "0",
                        "0",
                        "1",
                        "pe-1"});
            table1082.AddRow(new string[] {
                        "Jun/Current Academic Year",
                        "600",
                        "0",
                        "0",
                        "0",
                        "1",
                        "pe-1"});
            table1082.AddRow(new string[] {
                        "Jul/Current Academic Year",
                        "600",
                        "0",
                        "0",
                        "0",
                        "1",
                        "pe-1"});
#line 20
    testRunner.And("the following earnings had been generated for the learner", ((string)(null)), table1082, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1083 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection Period",
                        "Delivery Period",
                        "Levy Payments",
                        "SFA Fully-Funded Payments",
                        "Transaction Type"});
            table1083.AddRow(new string[] {
                        "R01/Current Academic Year",
                        "Aug/Current Academic Year",
                        "600",
                        "0",
                        "Learning"});
            table1083.AddRow(new string[] {
                        "R02/Current Academic Year",
                        "Sep/Current Academic Year",
                        "600",
                        "0",
                        "Learning"});
#line 36
    testRunner.And("the following provider payments had been generated", ((string)(null)), table1083, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1084 = new TechTalk.SpecFlow.Table(new string[] {
                        "Aim Type",
                        "Aim Reference",
                        "Start Date",
                        "Planned Duration",
                        "Actual Duration",
                        "Aim Sequence Number",
                        "Framework Code",
                        "Pathway Code",
                        "Programme Type",
                        "Funding Line Type",
                        "Completion Status"});
            table1084.AddRow(new string[] {
                        "Maths or English",
                        "12345",
                        "06/Aug/Current Academic Year",
                        "12 months",
                        "",
                        "1",
                        "584",
                        "1",
                        "20",
                        "19-24 Apprenticeship Levy",
                        "continuing"});
            table1084.AddRow(new string[] {
                        "Programme",
                        "ZPROG001",
                        "06/Aug/Current Academic Year",
                        "12 months",
                        "",
                        "2",
                        "584",
                        "1",
                        "20",
                        "19-24 Apprenticeship Levy",
                        "continuing"});
#line 41
    testRunner.But("aims details are changed as follows", ((string)(null)), table1084, "But ");
#line hidden
            TechTalk.SpecFlow.Table table1085 = new TechTalk.SpecFlow.Table(new string[] {
                        "Price Episode Id",
                        "Total Training Price",
                        "Total Training Price Effective Date",
                        "Contract Type",
                        "Aim Sequence Number",
                        "SFA Contribution Percentage"});
            table1085.AddRow(new string[] {
                        "",
                        "471",
                        "06/Aug/Current Academic Year",
                        "Act1",
                        "1",
                        ""});
            table1085.AddRow(new string[] {
                        "pe-1",
                        "9000",
                        "06/Aug/Current Academic Year",
                        "Act1",
                        "2",
                        "90%"});
#line 45
 testRunner.And("price details are changed as follows", ((string)(null)), table1085, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1086 = new TechTalk.SpecFlow.Table(new string[] {
                        "Identifier",
                        "start date",
                        "end date",
                        "agreed price",
                        "status",
                        "Framework Code",
                        "Pathway Code",
                        "Programme Type",
                        "stop effective from"});
            table1086.AddRow(new string[] {
                        "Apprenticeship 1",
                        "01/Aug/Current Academic Year",
                        "01/Aug/Next Academic Year",
                        "9000",
                        "cancelled",
                        "593",
                        "1",
                        "20",
                        "01/Aug/Current Academic Year"});
            table1086.AddRow(new string[] {
                        "Apprenticeship 2",
                        "01/Aug/Current Academic Year",
                        "01/Aug/Next Academic Year",
                        "9000",
                        "active",
                        "584",
                        "1",
                        "20",
                        ""});
#line 49
 testRunner.And("the Commitment details are changed as follows", ((string)(null)), table1086, "And ");
#line 53
 testRunner.When(string.Format("the amended ILR file is re-submitted for the learners in collection period {0}", collection_Period), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table1087 = new TechTalk.SpecFlow.Table(new string[] {
                        "Delivery Period",
                        "On-Programme",
                        "Completion",
                        "Balancing",
                        "OnProgrammeMathsAndEnglish",
                        "Aim Sequence Number",
                        "Price Episode Identifier",
                        "Contract Type"});
            table1087.AddRow(new string[] {
                        "Aug/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "39.25",
                        "1",
                        "",
                        "Act1"});
            table1087.AddRow(new string[] {
                        "Sep/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "39.25",
                        "1",
                        "",
                        "Act1"});
            table1087.AddRow(new string[] {
                        "Oct/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "39.25",
                        "1",
                        "",
                        "Act1"});
            table1087.AddRow(new string[] {
                        "Nov/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "39.25",
                        "1",
                        "",
                        "Act1"});
            table1087.AddRow(new string[] {
                        "Dec/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "39.25",
                        "1",
                        "",
                        "Act1"});
            table1087.AddRow(new string[] {
                        "Jan/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "39.25",
                        "1",
                        "",
                        "Act1"});
            table1087.AddRow(new string[] {
                        "Feb/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "39.25",
                        "1",
                        "",
                        "Act1"});
            table1087.AddRow(new string[] {
                        "Mar/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "39.25",
                        "1",
                        "",
                        "Act1"});
            table1087.AddRow(new string[] {
                        "Apr/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "39.25",
                        "1",
                        "",
                        "Act1"});
            table1087.AddRow(new string[] {
                        "May/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "39.25",
                        "1",
                        "",
                        "Act1"});
            table1087.AddRow(new string[] {
                        "Jun/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "39.25",
                        "1",
                        "",
                        "Act1"});
            table1087.AddRow(new string[] {
                        "Jul/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "39.25",
                        "1",
                        "",
                        "Act1"});
            table1087.AddRow(new string[] {
                        "Aug/Current Academic Year",
                        "600",
                        "0",
                        "0",
                        "0",
                        "2",
                        "pe-1",
                        "Act1"});
            table1087.AddRow(new string[] {
                        "Sep/Current Academic Year",
                        "600",
                        "0",
                        "0",
                        "0",
                        "2",
                        "pe-1",
                        "Act1"});
            table1087.AddRow(new string[] {
                        "Oct/Current Academic Year",
                        "600",
                        "0",
                        "0",
                        "0",
                        "2",
                        "pe-1",
                        "Act1"});
            table1087.AddRow(new string[] {
                        "Nov/Current Academic Year",
                        "600",
                        "0",
                        "0",
                        "0",
                        "2",
                        "pe-1",
                        "Act1"});
            table1087.AddRow(new string[] {
                        "Dec/Current Academic Year",
                        "600",
                        "0",
                        "0",
                        "0",
                        "2",
                        "pe-1",
                        "Act1"});
            table1087.AddRow(new string[] {
                        "Jan/Current Academic Year",
                        "600",
                        "0",
                        "0",
                        "0",
                        "2",
                        "pe-1",
                        "Act1"});
            table1087.AddRow(new string[] {
                        "Feb/Current Academic Year",
                        "600",
                        "0",
                        "0",
                        "0",
                        "2",
                        "pe-1",
                        "Act1"});
            table1087.AddRow(new string[] {
                        "Mar/Current Academic Year",
                        "600",
                        "0",
                        "0",
                        "0",
                        "2",
                        "pe-1",
                        "Act1"});
            table1087.AddRow(new string[] {
                        "Apr/Current Academic Year",
                        "600",
                        "0",
                        "0",
                        "0",
                        "2",
                        "pe-1",
                        "Act1"});
            table1087.AddRow(new string[] {
                        "May/Current Academic Year",
                        "600",
                        "0",
                        "0",
                        "0",
                        "2",
                        "pe-1",
                        "Act1"});
            table1087.AddRow(new string[] {
                        "Jun/Current Academic Year",
                        "600",
                        "0",
                        "0",
                        "0",
                        "2",
                        "pe-1",
                        "Act1"});
            table1087.AddRow(new string[] {
                        "Jul/Current Academic Year",
                        "600",
                        "0",
                        "0",
                        "0",
                        "2",
                        "pe-1",
                        "Act1"});
#line 54
    testRunner.Then("the following learner earnings should be generated", ((string)(null)), table1087, "Then ");
#line 82
    testRunner.And(string.Format("{0} required payments are generated", expectedRequiredPayments), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 83
    testRunner.And("levy month end is ran", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1088 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection Period",
                        "Delivery Period",
                        "Levy Payments",
                        "SFA Fully-Funded Payments",
                        "Transaction Type",
                        "Framework Code"});
            table1088.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Aug/Current Academic Year",
                        "-600",
                        "0",
                        "Learning",
                        "593"});
            table1088.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Sep/Current Academic Year",
                        "-600",
                        "0",
                        "Learning",
                        "593"});
            table1088.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Aug/Current Academic Year",
                        "600",
                        "0",
                        "Learning",
                        "584"});
            table1088.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Sep/Current Academic Year",
                        "600",
                        "0",
                        "Learning",
                        "584"});
            table1088.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Oct/Current Academic Year",
                        "600",
                        "0",
                        "Learning",
                        "584"});
            table1088.AddRow(new string[] {
                        "R04/Current Academic Year",
                        "Nov/Current Academic Year",
                        "600",
                        "0",
                        "Learning",
                        "584"});
            table1088.AddRow(new string[] {
                        "R05/Current Academic Year",
                        "Dec/Current Academic Year",
                        "600",
                        "0",
                        "Learning",
                        "584"});
            table1088.AddRow(new string[] {
                        "R06/Current Academic Year",
                        "Jan/Current Academic Year",
                        "600",
                        "0",
                        "Learning",
                        "584"});
            table1088.AddRow(new string[] {
                        "R07/Current Academic Year",
                        "Feb/Current Academic Year",
                        "600",
                        "0",
                        "Learning",
                        "584"});
            table1088.AddRow(new string[] {
                        "R08/Current Academic Year",
                        "Mar/Current Academic Year",
                        "600",
                        "0",
                        "Learning",
                        "584"});
            table1088.AddRow(new string[] {
                        "R09/Current Academic Year",
                        "Apr/Current Academic Year",
                        "600",
                        "0",
                        "Learning",
                        "584"});
            table1088.AddRow(new string[] {
                        "R10/Current Academic Year",
                        "May/Current Academic Year",
                        "600",
                        "0",
                        "Learning",
                        "584"});
            table1088.AddRow(new string[] {
                        "R11/Current Academic Year",
                        "Jun/Current Academic Year",
                        "600",
                        "0",
                        "Learning",
                        "584"});
            table1088.AddRow(new string[] {
                        "R12/Current Academic Year",
                        "Jul/Current Academic Year",
                        "600",
                        "0",
                        "Learning",
                        "584"});
            table1088.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Aug/Current Academic Year",
                        "0",
                        "39.25",
                        "OnProgrammeMathsAndEnglish",
                        "593"});
            table1088.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Sep/Current Academic Year",
                        "0",
                        "39.25",
                        "OnProgrammeMathsAndEnglish",
                        "593"});
            table1088.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Oct/Current Academic Year",
                        "0",
                        "39.25",
                        "OnProgrammeMathsAndEnglish",
                        "584"});
            table1088.AddRow(new string[] {
                        "R04/Current Academic Year",
                        "Nov/Current Academic Year",
                        "0",
                        "39.25",
                        "OnProgrammeMathsAndEnglish",
                        "584"});
            table1088.AddRow(new string[] {
                        "R05/Current Academic Year",
                        "Dec/Current Academic Year",
                        "0",
                        "39.25",
                        "OnProgrammeMathsAndEnglish",
                        "584"});
            table1088.AddRow(new string[] {
                        "R06/Current Academic Year",
                        "Jan/Current Academic Year",
                        "0",
                        "39.25",
                        "OnProgrammeMathsAndEnglish",
                        "584"});
            table1088.AddRow(new string[] {
                        "R07/Current Academic Year",
                        "Feb/Current Academic Year",
                        "0",
                        "39.25",
                        "OnProgrammeMathsAndEnglish",
                        "584"});
            table1088.AddRow(new string[] {
                        "R08/Current Academic Year",
                        "Mar/Current Academic Year",
                        "0",
                        "39.25",
                        "OnProgrammeMathsAndEnglish",
                        "584"});
            table1088.AddRow(new string[] {
                        "R09/Current Academic Year",
                        "Apr/Current Academic Year",
                        "0",
                        "39.25",
                        "OnProgrammeMathsAndEnglish",
                        "584"});
            table1088.AddRow(new string[] {
                        "R10/Current Academic Year",
                        "May/Current Academic Year",
                        "0",
                        "39.25",
                        "OnProgrammeMathsAndEnglish",
                        "584"});
            table1088.AddRow(new string[] {
                        "R11/Current Academic Year",
                        "Jun/Current Academic Year",
                        "0",
                        "39.25",
                        "OnProgrammeMathsAndEnglish",
                        "584"});
            table1088.AddRow(new string[] {
                        "R12/Current Academic Year",
                        "Jul/Current Academic Year",
                        "0",
                        "39.25",
                        "OnProgrammeMathsAndEnglish",
                        "584"});
#line 84
    testRunner.And("only the following provider payments will be recorded", ((string)(null)), table1088, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1089 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection Period",
                        "Delivery Period",
                        "Levy Payments",
                        "SFA Fully-Funded Payments",
                        "Transaction Type",
                        "Framework Code"});
            table1089.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Aug/Current Academic Year",
                        "-600",
                        "0",
                        "Learning",
                        "593"});
            table1089.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Sep/Current Academic Year",
                        "-600",
                        "0",
                        "Learning",
                        "593"});
            table1089.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Aug/Current Academic Year",
                        "600",
                        "0",
                        "Learning",
                        "584"});
            table1089.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Sep/Current Academic Year",
                        "600",
                        "0",
                        "Learning",
                        "584"});
            table1089.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Oct/Current Academic Year",
                        "600",
                        "0",
                        "Learning",
                        "584"});
            table1089.AddRow(new string[] {
                        "R04/Current Academic Year",
                        "Nov/Current Academic Year",
                        "600",
                        "0",
                        "Learning",
                        "584"});
            table1089.AddRow(new string[] {
                        "R05/Current Academic Year",
                        "Dec/Current Academic Year",
                        "600",
                        "0",
                        "Learning",
                        "584"});
            table1089.AddRow(new string[] {
                        "R06/Current Academic Year",
                        "Jan/Current Academic Year",
                        "600",
                        "0",
                        "Learning",
                        "584"});
            table1089.AddRow(new string[] {
                        "R07/Current Academic Year",
                        "Feb/Current Academic Year",
                        "600",
                        "0",
                        "Learning",
                        "584"});
            table1089.AddRow(new string[] {
                        "R08/Current Academic Year",
                        "Mar/Current Academic Year",
                        "600",
                        "0",
                        "Learning",
                        "584"});
            table1089.AddRow(new string[] {
                        "R09/Current Academic Year",
                        "Apr/Current Academic Year",
                        "600",
                        "0",
                        "Learning",
                        "584"});
            table1089.AddRow(new string[] {
                        "R10/Current Academic Year",
                        "May/Current Academic Year",
                        "600",
                        "0",
                        "Learning",
                        "584"});
            table1089.AddRow(new string[] {
                        "R11/Current Academic Year",
                        "Jun/Current Academic Year",
                        "600",
                        "0",
                        "Learning",
                        "584"});
            table1089.AddRow(new string[] {
                        "R12/Current Academic Year",
                        "Jul/Current Academic Year",
                        "600",
                        "0",
                        "Learning",
                        "584"});
            table1089.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Aug/Current Academic Year",
                        "0",
                        "39.25",
                        "OnProgrammeMathsAndEnglish",
                        "584"});
            table1089.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Sep/Current Academic Year",
                        "0",
                        "39.25",
                        "OnProgrammeMathsAndEnglish",
                        "584"});
            table1089.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Oct/Current Academic Year",
                        "0",
                        "39.25",
                        "OnProgrammeMathsAndEnglish",
                        "584"});
            table1089.AddRow(new string[] {
                        "R04/Current Academic Year",
                        "Nov/Current Academic Year",
                        "0",
                        "39.25",
                        "OnProgrammeMathsAndEnglish",
                        "584"});
            table1089.AddRow(new string[] {
                        "R05/Current Academic Year",
                        "Dec/Current Academic Year",
                        "0",
                        "39.25",
                        "OnProgrammeMathsAndEnglish",
                        "593"});
            table1089.AddRow(new string[] {
                        "R06/Current Academic Year",
                        "Jan/Current Academic Year",
                        "0",
                        "39.25",
                        "OnProgrammeMathsAndEnglish",
                        "593"});
            table1089.AddRow(new string[] {
                        "R07/Current Academic Year",
                        "Feb/Current Academic Year",
                        "0",
                        "39.25",
                        "OnProgrammeMathsAndEnglish",
                        "584"});
            table1089.AddRow(new string[] {
                        "R08/Current Academic Year",
                        "Mar/Current Academic Year",
                        "0",
                        "39.25",
                        "OnProgrammeMathsAndEnglish",
                        "584"});
            table1089.AddRow(new string[] {
                        "R09/Current Academic Year",
                        "Apr/Current Academic Year",
                        "0",
                        "39.25",
                        "OnProgrammeMathsAndEnglish",
                        "584"});
            table1089.AddRow(new string[] {
                        "R10/Current Academic Year",
                        "May/Current Academic Year",
                        "0",
                        "39.25",
                        "OnProgrammeMathsAndEnglish",
                        "584"});
            table1089.AddRow(new string[] {
                        "R11/Current Academic Year",
                        "Jun/Current Academic Year",
                        "0",
                        "39.25",
                        "OnProgrammeMathsAndEnglish",
                        "584"});
            table1089.AddRow(new string[] {
                        "R12/Current Academic Year",
                        "Jul/Current Academic Year",
                        "0",
                        "39.25",
                        "OnProgrammeMathsAndEnglish",
                        "584"});
#line 113
 testRunner.And("only the following provider payments will be generated", ((string)(null)), table1089, "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
