// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SFA.DAS.Payments.AcceptanceTests.EndToEnd.Tests.InconsistentSubmissionData
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Inconsistent Submissions Data PV2-1627")]
    [NUnit.Framework.IgnoreAttribute("Ignored feature")]
    public partial class InconsistentSubmissionsDataPV2_1627Feature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "PV2-1627 Learner Removed at end of AY in R14.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Inconsistent Submissions Data PV2-1627", null, ProgrammingLanguage.CSharp, new string[] {
                        "ignore"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A learner was in the ILR correctly for R01 & R02, was withdrawn in R14 for previo" +
            "us AY, clawback R01 & R02 payments in R03")]
        public virtual void ALearnerWasInTheILRCorrectlyForR01R02WasWithdrawnInR14ForPreviousAYClawbackR01R02PaymentsInR03()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A learner was in the ILR correctly for R01 & R02, was withdrawn in R14 for previo" +
                    "us AY, clawback R01 & R02 payments in R03", null, ((string[])(null)));
#line 5
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table1038 = new TechTalk.SpecFlow.Table(new string[] {
                        "Learner Reference Number",
                        "Uln"});
            table1038.AddRow(new string[] {
                        "abc123",
                        "12345678"});
#line 6
 testRunner.Given("the following learners", ((string)(null)), table1038, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1039 = new TechTalk.SpecFlow.Table(new string[] {
                        "Aim Type",
                        "Aim Reference",
                        "Start Date",
                        "Planned Duration",
                        "Actual Duration",
                        "Aim Sequence Number",
                        "Framework Code",
                        "Pathway Code",
                        "Programme Type",
                        "Funding Line Type",
                        "Completion Status"});
            table1039.AddRow(new string[] {
                        "Programme",
                        "ZPROG001",
                        "01/Jan/Last Academic Year",
                        "12 months",
                        "",
                        "1",
                        "593",
                        "1",
                        "20",
                        "19+ Apprenticeship (From May 2017) Non-Levy Contract (non-procured)",
                        "continuing"});
            table1039.AddRow(new string[] {
                        "Maths or English",
                        "5012689",
                        "01/Jan/Last Academic Year",
                        "12 months",
                        "",
                        "2",
                        "593",
                        "1",
                        "20",
                        "19+ Apprenticeship (From May 2017) Non-Levy Contract (non-procured)",
                        "continuing"});
#line 9
 testRunner.And("the following aims", ((string)(null)), table1039, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1040 = new TechTalk.SpecFlow.Table(new string[] {
                        "Price Episode Id",
                        "Total Training Price",
                        "Total Training Price Effective Date",
                        "Total Assessment Price",
                        "Total Assessment Price Effective Date",
                        "Contract Type",
                        "Aim Sequence Number",
                        "SFA Contribution Percentage"});
            table1040.AddRow(new string[] {
                        "1st price details",
                        "9000",
                        "01/Jan/Last Academic Year",
                        "0",
                        "01/Jan/Last Academic Year",
                        "Act2",
                        "1",
                        "90%"});
            table1040.AddRow(new string[] {
                        "",
                        "0",
                        "01/Jan/Last Academic Year",
                        "0",
                        "01/Jan/Last Academic Year",
                        "Act2",
                        "2",
                        "90%"});
#line 13
 testRunner.And("price details as follows", ((string)(null)), table1040, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1041 = new TechTalk.SpecFlow.Table(new string[] {
                        "Delivery Period",
                        "On-Programme",
                        "Completion",
                        "Balancing",
                        "OnProgrammeMathsAndEnglish",
                        "Price Episode Identifier"});
            table1041.AddRow(new string[] {
                        "Jan/Last Academic Year",
                        "600",
                        "0",
                        "0",
                        "",
                        "1st price details"});
            table1041.AddRow(new string[] {
                        "Feb/Last Academic Year",
                        "600",
                        "0",
                        "0",
                        "",
                        "1st price details"});
            table1041.AddRow(new string[] {
                        "Mar/Last Academic Year",
                        "600",
                        "0",
                        "0",
                        "",
                        "1st price details"});
            table1041.AddRow(new string[] {
                        "Apr/Last Academic Year",
                        "600",
                        "0",
                        "0",
                        "",
                        "1st price details"});
            table1041.AddRow(new string[] {
                        "May/Last Academic Year",
                        "600",
                        "0",
                        "0",
                        "",
                        "1st price details"});
            table1041.AddRow(new string[] {
                        "Jun/Last Academic Year",
                        "600",
                        "0",
                        "0",
                        "",
                        "1st price details"});
            table1041.AddRow(new string[] {
                        "Jul/Last Academic Year",
                        "600",
                        "0",
                        "0",
                        "",
                        "1st price details"});
            table1041.AddRow(new string[] {
                        "Aug/Current Academic Year",
                        "600",
                        "0",
                        "0",
                        "",
                        "1st price details"});
            table1041.AddRow(new string[] {
                        "Sep/Current Academic Year",
                        "600",
                        "0",
                        "0",
                        "",
                        "1st price details"});
            table1041.AddRow(new string[] {
                        "Jan/Last Academic Year",
                        "0",
                        "0",
                        "0",
                        "39.25",
                        ""});
            table1041.AddRow(new string[] {
                        "Feb/Last Academic Year",
                        "0",
                        "0",
                        "0",
                        "39.25",
                        ""});
            table1041.AddRow(new string[] {
                        "Mar/Last Academic Year",
                        "0",
                        "0",
                        "0",
                        "39.25",
                        ""});
            table1041.AddRow(new string[] {
                        "Apr/Last Academic Year",
                        "0",
                        "0",
                        "0",
                        "39.25",
                        ""});
            table1041.AddRow(new string[] {
                        "May/Last Academic Year",
                        "0",
                        "0",
                        "0",
                        "39.25",
                        ""});
            table1041.AddRow(new string[] {
                        "Jun/Last Academic Year",
                        "0",
                        "0",
                        "0",
                        "39.25",
                        ""});
            table1041.AddRow(new string[] {
                        "Jul/Last Academic Year",
                        "0",
                        "0",
                        "0",
                        "39.25",
                        ""});
            table1041.AddRow(new string[] {
                        "Aug/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "39.25",
                        ""});
            table1041.AddRow(new string[] {
                        "Sep/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "39.25",
                        ""});
#line 17
    testRunner.And("the following earnings had been generated for the learner", ((string)(null)), table1041, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1042 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection Period",
                        "Delivery Period",
                        "SFA Co-Funded Payments",
                        "Employer Co-Funded Payments",
                        "SFA Fully-Funded Payments",
                        "Transaction Type"});
            table1042.AddRow(new string[] {
                        "R06/Last Academic Year",
                        "Jan/Last Academic Year",
                        "540",
                        "60",
                        "0",
                        "Learning"});
            table1042.AddRow(new string[] {
                        "R07/Last Academic Year",
                        "Feb/Last Academic Year",
                        "540",
                        "60",
                        "0",
                        "Learning"});
            table1042.AddRow(new string[] {
                        "R08/Last Academic Year",
                        "Mar/Last Academic Year",
                        "540",
                        "60",
                        "0",
                        "Learning"});
            table1042.AddRow(new string[] {
                        "R09/Last Academic Year",
                        "Apr/Last Academic Year",
                        "540",
                        "60",
                        "0",
                        "Learning"});
            table1042.AddRow(new string[] {
                        "R10/Last Academic Year",
                        "May/Last Academic Year",
                        "540",
                        "60",
                        "0",
                        "Learning"});
            table1042.AddRow(new string[] {
                        "R11/Last Academic Year",
                        "Jun/Last Academic Year",
                        "540",
                        "60",
                        "0",
                        "Learning"});
            table1042.AddRow(new string[] {
                        "R12/Last Academic Year",
                        "Jul/Last Academic Year",
                        "540",
                        "60",
                        "0",
                        "Learning"});
            table1042.AddRow(new string[] {
                        "R01/Current Academic Year",
                        "Aug/Current Academic Year",
                        "540",
                        "60",
                        "0",
                        "Learning"});
            table1042.AddRow(new string[] {
                        "R02/Current Academic Year",
                        "Sep/Current Academic Year",
                        "540",
                        "60",
                        "0",
                        "Learning"});
            table1042.AddRow(new string[] {
                        "R06/Last Academic Year",
                        "Jan/Last Academic Year",
                        "0",
                        "0",
                        "39.25",
                        "OnProgrammeMathsAndEnglish"});
            table1042.AddRow(new string[] {
                        "R07/Last Academic Year",
                        "Feb/Last Academic Year",
                        "0",
                        "0",
                        "39.25",
                        "OnProgrammeMathsAndEnglish"});
            table1042.AddRow(new string[] {
                        "R08/Last Academic Year",
                        "Mar/Last Academic Year",
                        "0",
                        "0",
                        "39.25",
                        "OnProgrammeMathsAndEnglish"});
            table1042.AddRow(new string[] {
                        "R09/Last Academic Year",
                        "Apr/Last Academic Year",
                        "0",
                        "0",
                        "39.25",
                        "OnProgrammeMathsAndEnglish"});
            table1042.AddRow(new string[] {
                        "R10/Last Academic Year",
                        "May/Last Academic Year",
                        "0",
                        "0",
                        "39.25",
                        "OnProgrammeMathsAndEnglish"});
            table1042.AddRow(new string[] {
                        "R11/Last Academic Year",
                        "Jun/Last Academic Year",
                        "0",
                        "0",
                        "39.25",
                        "OnProgrammeMathsAndEnglish"});
            table1042.AddRow(new string[] {
                        "R12/Last Academic Year",
                        "Jul/Last Academic Year",
                        "0",
                        "0",
                        "39.25",
                        "OnProgrammeMathsAndEnglish"});
            table1042.AddRow(new string[] {
                        "R01/Current Academic Year",
                        "Aug/Current Academic Year",
                        "0",
                        "0",
                        "39.25",
                        "OnProgrammeMathsAndEnglish"});
            table1042.AddRow(new string[] {
                        "R02/Current Academic Year",
                        "Sep/Current Academic Year",
                        "0",
                        "0",
                        "39.25",
                        "OnProgrammeMathsAndEnglish"});
#line 37
    testRunner.And("the following provider payments had been generated", ((string)(null)), table1042, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1043 = new TechTalk.SpecFlow.Table(new string[] {
                        "Aim Type",
                        "Aim Reference",
                        "Start Date",
                        "Planned Duration",
                        "Actual Duration",
                        "Aim Sequence Number",
                        "Framework Code",
                        "Pathway Code",
                        "Programme Type",
                        "Funding Line Type",
                        "Completion Status"});
            table1043.AddRow(new string[] {
                        "Programme",
                        "ZPROG001",
                        "01/Jan/Last Academic Year",
                        "",
                        "7 months - 1 day",
                        "1",
                        "593",
                        "1",
                        "20",
                        "19+ Apprenticeship (From May 2017) Non-Levy Contract (non-procured)",
                        "withdrawn"});
            table1043.AddRow(new string[] {
                        "Maths or English",
                        "5012689",
                        "01/Jan/Last Academic Year",
                        "",
                        "7 months - 1 day",
                        "2",
                        "593",
                        "1",
                        "20",
                        "19+ Apprenticeship (From May 2017) Non-Levy Contract (non-procured)",
                        "withdrawn"});
#line 57
    testRunner.But("aims details are changed as follows", ((string)(null)), table1043, "But ");
#line hidden
            TechTalk.SpecFlow.Table table1044 = new TechTalk.SpecFlow.Table(new string[] {
                        "Price Episode Id",
                        "Total Training Price",
                        "Total Training Price Effective Date",
                        "Total Assessment Price",
                        "Total Assessment Price Effective Date",
                        "Contract Type",
                        "Aim Sequence Number",
                        "SFA Contribution Percentage"});
            table1044.AddRow(new string[] {
                        "1st price details",
                        "9000",
                        "01/Jan/Last Academic Year",
                        "0",
                        "01/Jan/Last Academic Year",
                        "Act2",
                        "1",
                        "90%"});
            table1044.AddRow(new string[] {
                        "",
                        "0",
                        "01/Jan/Last Academic Year",
                        "0",
                        "01/Jan/Last Academic Year",
                        "Act2",
                        "2",
                        "90%"});
#line 61
 testRunner.And("price details are changed as follows", ((string)(null)), table1044, "And ");
#line 65
 testRunner.When("the amended ILR file is re-submitted for the learners in collection period R03/Cu" +
                    "rrent Academic Year", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table1045 = new TechTalk.SpecFlow.Table(new string[] {
                        "Delivery Period",
                        "On-Programme",
                        "Completion",
                        "Balancing",
                        "OnProgrammeMathsAndEnglish",
                        "Aim Sequence Number",
                        "Price Episode Identifier",
                        "Contract Type"});
            table1045.AddRow(new string[] {
                        "Aug/Last Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "1",
                        "1st price details",
                        "Act2"});
            table1045.AddRow(new string[] {
                        "Sep/Last Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "1",
                        "1st price details",
                        "Act2"});
            table1045.AddRow(new string[] {
                        "Oct/Last Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "1",
                        "1st price details",
                        "Act2"});
            table1045.AddRow(new string[] {
                        "Nov/Last Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "1",
                        "1st price details",
                        "Act2"});
            table1045.AddRow(new string[] {
                        "Dec/Last Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "1",
                        "1st price details",
                        "Act2"});
            table1045.AddRow(new string[] {
                        "Jan/Last Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "1",
                        "1st price details",
                        "Act2"});
            table1045.AddRow(new string[] {
                        "Feb/Last Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "1",
                        "1st price details",
                        "Act2"});
            table1045.AddRow(new string[] {
                        "Mar/Last Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "1",
                        "1st price details",
                        "Act2"});
            table1045.AddRow(new string[] {
                        "Apr/Last Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "1",
                        "1st price details",
                        "Act2"});
            table1045.AddRow(new string[] {
                        "May/Last Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "1",
                        "1st price details",
                        "Act2"});
            table1045.AddRow(new string[] {
                        "Jun/Last Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "1",
                        "1st price details",
                        "Act2"});
            table1045.AddRow(new string[] {
                        "Jul/Last Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "1",
                        "1st price details",
                        "Act2"});
            table1045.AddRow(new string[] {
                        "Aug/Last Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "2",
                        "",
                        "Act2"});
            table1045.AddRow(new string[] {
                        "Sep/Last Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "2",
                        "",
                        "Act2"});
            table1045.AddRow(new string[] {
                        "Oct/Last Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "2",
                        "",
                        "Act2"});
            table1045.AddRow(new string[] {
                        "Nov/Last Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "2",
                        "",
                        "Act2"});
            table1045.AddRow(new string[] {
                        "Dec/Last Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "2",
                        "",
                        "Act2"});
            table1045.AddRow(new string[] {
                        "Jan/Last Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "2",
                        "",
                        "Act2"});
            table1045.AddRow(new string[] {
                        "Feb/Last Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "2",
                        "",
                        "Act2"});
            table1045.AddRow(new string[] {
                        "Mar/Last Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "2",
                        "",
                        "Act2"});
            table1045.AddRow(new string[] {
                        "Apr/Last Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "2",
                        "",
                        "Act2"});
            table1045.AddRow(new string[] {
                        "May/Last Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "2",
                        "",
                        "Act2"});
            table1045.AddRow(new string[] {
                        "Jun/Last Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "2",
                        "",
                        "Act2"});
            table1045.AddRow(new string[] {
                        "Jul/Last Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "2",
                        "",
                        "Act2"});
#line 66
    testRunner.Then("the following learner earnings should be generated", ((string)(null)), table1045, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table1046 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection Period",
                        "Delivery Period",
                        "On-Programme",
                        "Completion",
                        "Balancing",
                        "OnProgrammeMathsAndEnglish"});
            table1046.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Aug/Current Academic Year",
                        "-600",
                        "0",
                        "0",
                        "-39.25"});
            table1046.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Sep/Current Academic Year",
                        "-600",
                        "0",
                        "0",
                        "-39.25"});
#line 92
    testRunner.And("only the following payments will be calculated", ((string)(null)), table1046, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1047 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection Period",
                        "Delivery Period",
                        "SFA Co-Funded Payments",
                        "Employer Co-Funded Payments",
                        "SFA Fully-Funded Payments",
                        "Transaction Type",
                        "Price Episode Identifier"});
            table1047.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Aug/Current Academic Year",
                        "-540",
                        "-60",
                        "0",
                        "Learning",
                        "1st price details"});
            table1047.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Sep/Current Academic Year",
                        "-540",
                        "-60",
                        "0",
                        "Learning",
                        "1st price details"});
            table1047.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Aug/Current Academic Year",
                        "",
                        "",
                        "-39.25",
                        "OnProgrammeMathsAndEnglish",
                        ""});
            table1047.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Sep/Current Academic Year",
                        "",
                        "",
                        "-39.25",
                        "OnProgrammeMathsAndEnglish",
                        ""});
#line 96
    testRunner.And("only the following provider payments will be recorded", ((string)(null)), table1047, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1048 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection Period",
                        "Delivery Period",
                        "SFA Co-Funded Payments",
                        "Employer Co-Funded Payments",
                        "SFA Fully-Funded Payments",
                        "Transaction Type",
                        "Price Episode Identifier"});
            table1048.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Aug/Current Academic Year",
                        "-540",
                        "-60",
                        "0",
                        "Learning",
                        "1st price details"});
            table1048.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Sep/Current Academic Year",
                        "-540",
                        "-60",
                        "0",
                        "Learning",
                        "1st price details"});
            table1048.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Aug/Current Academic Year",
                        "0",
                        "0",
                        "-39.25",
                        "OnProgrammeMathsAndEnglish",
                        ""});
            table1048.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Sep/Current Academic Year",
                        "0",
                        "0",
                        "-39.25",
                        "OnProgrammeMathsAndEnglish",
                        ""});
#line 102
 testRunner.And("at month end only the following provider payments will be generated", ((string)(null)), table1048, "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
