// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SFA.DAS.Payments.AcceptanceTests.EndToEnd.Tests.LearnerChangeOfCircumstances
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("PV2-2898 course completion Date is changed Completion payment refunded")]
    public partial class PV2_2898CourseCompletionDateIsChangedCompletionPaymentRefundedFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Levy_course_completion_changed_balancing_compl_refunded_PV2-2898.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "PV2-2898 course completion Date is changed Completion payment refunded", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Levy learner, the course completion Date is changed, with a Balancing payment. Co" +
            "mpletion and Balancing is refunded")]
        [NUnit.Framework.TestCaseAttribute("R04/Current Academic Year", "5000", null)]
        public virtual void LevyLearnerTheCourseCompletionDateIsChangedWithABalancingPayment_CompletionAndBalancingIsRefunded(string collection_Period, string levyBalance, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Levy learner, the course completion Date is changed, with a Balancing payment. Co" +
                    "mpletion and Balancing is refunded", null, exampleTags);
#line 2
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 3
 testRunner.Given(string.Format("the employer levy account balance in collection period {0} is {1}", collection_Period, levyBalance), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table522 = new TechTalk.SpecFlow.Table(new string[] {
                        "framework code",
                        "programme type",
                        "pathway code",
                        "agreed price",
                        "start date",
                        "end date",
                        "status",
                        "effective from",
                        "stop effective from"});
            table522.AddRow(new string[] {
                        "593",
                        "20",
                        "1",
                        "17500",
                        "01/Aug/Last Academic Year",
                        "01/Oct/Current Academic Year",
                        "stopped",
                        "01/Aug/Last Academic Year",
                        "15/Oct/Current Academic Year"});
#line 4
 testRunner.And("the following apprenticeships exist", ((string)(null)), table522, "And ");
#line hidden
            TechTalk.SpecFlow.Table table523 = new TechTalk.SpecFlow.Table(new string[] {
                        "Start Date",
                        "Planned Duration",
                        "Total Training Price",
                        "Total Training Price Effective Date",
                        "Total Assessment Price",
                        "Total Assessment Price Effective Date",
                        "Actual Duration",
                        "Completion Status",
                        "Contract Type",
                        "Aim Sequence Number",
                        "Aim Reference",
                        "Framework Code",
                        "Pathway Code",
                        "Programme Type",
                        "Funding Line Type",
                        "SFA Contribution Percentage"});
            table523.AddRow(new string[] {
                        "01/Aug/Last Academic Year",
                        "14 months",
                        "17500",
                        "01/Aug/Last Academic Year",
                        "",
                        "01/Sep/Last Academic Year",
                        "14 months",
                        "completed",
                        "Act1",
                        "1",
                        "ZPROG001",
                        "593",
                        "1",
                        "20",
                        "19+ Apprenticeship (From May 2017) Levy Contract",
                        "90%"});
#line 7
 testRunner.And("the provider previously submitted the following learner details", ((string)(null)), table523, "And ");
#line hidden
            TechTalk.SpecFlow.Table table524 = new TechTalk.SpecFlow.Table(new string[] {
                        "Price Episode Id",
                        "Total Training Price",
                        "Total Training Price Effective Date",
                        "Total Assessment Price",
                        "Total Assessment Price Effective Date",
                        "Contract Type",
                        "Aim Sequence Number",
                        "SFA Contribution Percentage"});
            table524.AddRow(new string[] {
                        "pe-1",
                        "17500",
                        "01/Aug/Last Academic Year",
                        "",
                        "01/Sep/Last Academic Year",
                        "Act1",
                        "1",
                        "90%"});
#line 10
    testRunner.And("price details as follows", ((string)(null)), table524, "And ");
#line hidden
            TechTalk.SpecFlow.Table table525 = new TechTalk.SpecFlow.Table(new string[] {
                        "Delivery Period",
                        "On-Programme",
                        "Completion",
                        "Balancing",
                        "Price Episode Id"});
            table525.AddRow(new string[] {
                        "Aug/Last Academic Year",
                        "1000",
                        "0",
                        "0",
                        "pe-1"});
            table525.AddRow(new string[] {
                        "Sep/Last Academic Year",
                        "1000",
                        "0",
                        "0",
                        "pe-1"});
            table525.AddRow(new string[] {
                        "Oct/Last Academic Year",
                        "1000",
                        "0",
                        "0",
                        "pe-1"});
            table525.AddRow(new string[] {
                        "Nov/Last Academic Year",
                        "1000",
                        "0",
                        "0",
                        "pe-1"});
            table525.AddRow(new string[] {
                        "Dec/Last Academic Year",
                        "1000",
                        "0",
                        "0",
                        "pe-1"});
            table525.AddRow(new string[] {
                        "Jan/Last Academic Year",
                        "1000",
                        "0",
                        "0",
                        "pe-1"});
            table525.AddRow(new string[] {
                        "Feb/Last Academic Year",
                        "1000",
                        "0",
                        "0",
                        "pe-1"});
            table525.AddRow(new string[] {
                        "Mar/Last Academic Year",
                        "1000",
                        "0",
                        "0",
                        "pe-1"});
            table525.AddRow(new string[] {
                        "Apr/Last Academic Year",
                        "1000",
                        "0",
                        "0",
                        "pe-1"});
            table525.AddRow(new string[] {
                        "May/Last Academic Year",
                        "1000",
                        "0",
                        "0",
                        "pe-1"});
            table525.AddRow(new string[] {
                        "Jun/Last Academic Year",
                        "1000",
                        "0",
                        "0",
                        "pe-1"});
            table525.AddRow(new string[] {
                        "Jul/Last Academic Year",
                        "1000",
                        "0",
                        "0",
                        "pe-1"});
            table525.AddRow(new string[] {
                        "Aug/Current Academic Year",
                        "1000",
                        "0",
                        "0",
                        "pe-1"});
            table525.AddRow(new string[] {
                        "Sep/Current Academic Year",
                        "1000",
                        "3500",
                        "0",
                        "pe-1"});
            table525.AddRow(new string[] {
                        "Oct/Current Academic Year",
                        "1000",
                        "3500",
                        "0",
                        "pe-1"});
#line 13
    testRunner.And("the following earnings had been generated for the learner", ((string)(null)), table525, "And ");
#line hidden
            TechTalk.SpecFlow.Table table526 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection Period",
                        "Delivery Period",
                        "Levy Payments",
                        "Transaction Type",
                        "Price Episode Id"});
            table526.AddRow(new string[] {
                        "R01/Last Academic Year",
                        "Aug/Last Academic Year",
                        "1000",
                        "Learning",
                        "pe-1"});
            table526.AddRow(new string[] {
                        "R02/Last Academic Year",
                        "Sep/Last Academic Year",
                        "1000",
                        "Learning",
                        "pe-1"});
            table526.AddRow(new string[] {
                        "R03/Last Academic Year",
                        "Oct/Last Academic Year",
                        "1000",
                        "Learning",
                        "pe-1"});
            table526.AddRow(new string[] {
                        "R04/Last Academic Year",
                        "Nov/Last Academic Year",
                        "1000",
                        "Learning",
                        "pe-1"});
            table526.AddRow(new string[] {
                        "R05/Last Academic Year",
                        "Dec/Last Academic Year",
                        "1000",
                        "Learning",
                        "pe-1"});
            table526.AddRow(new string[] {
                        "R06/Last Academic Year",
                        "Jan/Last Academic Year",
                        "1000",
                        "Learning",
                        "pe-1"});
            table526.AddRow(new string[] {
                        "R07/Last Academic Year",
                        "Feb/Last Academic Year",
                        "1000",
                        "Learning",
                        "pe-1"});
            table526.AddRow(new string[] {
                        "R08/Last Academic Year",
                        "Mar/Last Academic Year",
                        "1000",
                        "Learning",
                        "pe-1"});
            table526.AddRow(new string[] {
                        "R09/Last Academic Year",
                        "Apr/Last Academic Year",
                        "1000",
                        "Learning",
                        "pe-1"});
            table526.AddRow(new string[] {
                        "R10/Last Academic Year",
                        "May/Last Academic Year",
                        "1000",
                        "Learning",
                        "pe-1"});
            table526.AddRow(new string[] {
                        "R11/Last Academic Year",
                        "Jun/Last Academic Year",
                        "1000",
                        "Learning",
                        "pe-1"});
            table526.AddRow(new string[] {
                        "R12/Last Academic Year",
                        "Jul/Last Academic Year",
                        "1000",
                        "Learning",
                        "pe-1"});
            table526.AddRow(new string[] {
                        "R01/Current Academic Year",
                        "Aug/Current Academic Year",
                        "1000",
                        "Learning",
                        "pe-1"});
            table526.AddRow(new string[] {
                        "R02/Current Academic Year",
                        "Sep/Current Academic Year",
                        "1000",
                        "Balancing",
                        "pe-1"});
            table526.AddRow(new string[] {
                        "R02/Current Academic Year",
                        "Sep/Current Academic Year",
                        "3500",
                        "Completion",
                        "pe-1"});
            table526.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Oct/Current Academic Year",
                        "1000",
                        "Balancing",
                        "pe-1"});
            table526.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Oct/Current Academic Year",
                        "3500",
                        "Completion",
                        "pe-1"});
#line 30
    testRunner.And("the following provider payments had been generated", ((string)(null)), table526, "And ");
#line hidden
            TechTalk.SpecFlow.Table table527 = new TechTalk.SpecFlow.Table(new string[] {
                        "Start Date",
                        "Planned Duration",
                        "Total Training Price",
                        "Total Training Price Effective Date",
                        "Total Assessment Price",
                        "Total Assessment Price Effective Date",
                        "Actual Duration",
                        "Completion Status",
                        "Contract Type",
                        "Aim Sequence Number",
                        "Aim Reference",
                        "Framework Code",
                        "Pathway Code",
                        "Programme Type",
                        "Funding Line Type",
                        "SFA Contribution Percentage"});
            table527.AddRow(new string[] {
                        "01/Aug/Last Academic Year",
                        "14 months",
                        "17500",
                        "01/Aug/Current Academic Year",
                        "",
                        "",
                        "14 months",
                        "completed",
                        "Act1",
                        "1",
                        "ZPROG001",
                        "593",
                        "1",
                        "20",
                        "19+ Apprenticeship (From May 2017) Levy Contract",
                        "90%"});
#line 49
    testRunner.But("the Provider now changes the Learner details as follows", ((string)(null)), table527, "But ");
#line hidden
            TechTalk.SpecFlow.Table table528 = new TechTalk.SpecFlow.Table(new string[] {
                        "Price Episode Id",
                        "Total Training Price",
                        "Total Training Price Effective Date",
                        "Total Assessment Price",
                        "ResidualAssessmentPrice",
                        "Residual Training Price Effective Date",
                        "Total Assessment Price Effective Date",
                        "Contract Type",
                        "Aim Sequence Number",
                        "SFA Contribution Percentage"});
            table528.AddRow(new string[] {
                        "pe-2",
                        "17500",
                        "01/Aug/Current Academic Year",
                        "",
                        "",
                        "",
                        "01/Oct/Current Academic Year",
                        "Act1",
                        "1",
                        "90%"});
            table528.AddRow(new string[] {
                        "pe-3",
                        "",
                        "",
                        "3000",
                        "1",
                        "01/Nov/Current Academic Year",
                        "01/Jan/Current Academic Year",
                        "Act1",
                        "1",
                        "90%"});
#line 53
 testRunner.And("price details are changed as follows", ((string)(null)), table528, "And ");
#line 58
 testRunner.When(string.Format("the amended ILR file is re-submitted for the learners in collection period {0}", collection_Period), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table529 = new TechTalk.SpecFlow.Table(new string[] {
                        "Delivery Period",
                        "On-Programme",
                        "Completion",
                        "Balancing",
                        "Price Episode Identifier"});
            table529.AddRow(new string[] {
                        "Aug/Current Academic Year",
                        "1000",
                        "0",
                        "0",
                        "pe-2"});
            table529.AddRow(new string[] {
                        "Sep/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-2"});
            table529.AddRow(new string[] {
                        "Oct/Current Academic Year",
                        "0",
                        "3500",
                        "1000",
                        "pe-2"});
            table529.AddRow(new string[] {
                        "Nov/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-2"});
            table529.AddRow(new string[] {
                        "Dec/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-2"});
            table529.AddRow(new string[] {
                        "Jan/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-2"});
            table529.AddRow(new string[] {
                        "Feb/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-2"});
            table529.AddRow(new string[] {
                        "Mar/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-2"});
            table529.AddRow(new string[] {
                        "Apr/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-2"});
            table529.AddRow(new string[] {
                        "May/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-2"});
            table529.AddRow(new string[] {
                        "Jun/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-2"});
            table529.AddRow(new string[] {
                        "Jul/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-2"});
#line 59
 testRunner.Then("the following learner earnings should be generated", ((string)(null)), table529, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table530 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection Period",
                        "Delivery Period",
                        "On-Programme",
                        "Completion",
                        "Balancing"});
            table530.AddRow(new string[] {
                        "R04/Current Academic Year",
                        "Sep/Current Academic Year",
                        "0",
                        "0",
                        "-1000"});
            table530.AddRow(new string[] {
                        "R04/Current Academic Year",
                        "Sep/Current Academic Year",
                        "0",
                        "-3500",
                        "0"});
#line 73
    testRunner.And("at month end only the following payments will be calculated", ((string)(null)), table530, "And ");
#line hidden
            TechTalk.SpecFlow.Table table531 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection Period",
                        "Delivery Period",
                        "Levy Payments",
                        "Transaction Type"});
            table531.AddRow(new string[] {
                        "R04/Current Academic Year",
                        "Sep/Current Academic Year",
                        "-1000",
                        "Balancing"});
            table531.AddRow(new string[] {
                        "R04/Current Academic Year",
                        "Sep/Current Academic Year",
                        "-3500",
                        "Completion"});
#line 77
 testRunner.And("only the following provider payments will be recorded", ((string)(null)), table531, "And ");
#line hidden
            TechTalk.SpecFlow.Table table532 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection Period",
                        "Delivery Period",
                        "Levy Payments",
                        "Transaction Type"});
            table532.AddRow(new string[] {
                        "R04/Current Academic Year",
                        "Sep/Current Academic Year",
                        "-1000",
                        "Balancing"});
            table532.AddRow(new string[] {
                        "R04/Current Academic Year",
                        "Sep/Current Academic Year",
                        "-3500",
                        "Completion"});
#line 81
 testRunner.And("only the following provider payments will be generated", ((string)(null)), table532, "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
