// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SFA.DAS.Payments.AcceptanceTests.EndToEnd.Tests.Levy_CareBursary
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Levy learner with levy balance starts after 1st day of month care leaver payment " +
        "made after 60 days - PV2-931")]
    public partial class LevyLearnerWithLevyBalanceStartsAfter1StDayOfMonthCareLeaverPaymentMadeAfter60Days_PV2_931Feature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "E2E - PV2-931 - Levy learner with levy balance starts after 1st day of month care leaver payment made after 60 days.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Levy learner with levy balance starts after 1st day of month care leaver payment " +
                    "made after 60 days - PV2-931", @"		As a Provider,
		I want a Levy learner with levy balance, where the learner is a care leaver and starts learning after first day of the month, and earns a care leaver payment after 60 days 
		So that I am paid the correct apprenticeship funding by SFA - PV2-931", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Levy learner with levy balance starts after 1st day of month care leaver payment " +
            "made after 60 days - PV2-931")]
        [NUnit.Framework.TestCaseAttribute("R01/Current Academic Year", "8000", null)]
        [NUnit.Framework.TestCaseAttribute("R02/Current Academic Year", "7500", null)]
        [NUnit.Framework.TestCaseAttribute("R03/Current Academic Year", "7000", null)]
        public virtual void LevyLearnerWithLevyBalanceStartsAfter1StDayOfMonthCareLeaverPaymentMadeAfter60Days_PV2_931(string collection_Period, string levyBalance, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Levy learner with levy balance starts after 1st day of month care leaver payment " +
                    "made after 60 days - PV2-931", null, exampleTags);
#line 65
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 67
 testRunner.Given(string.Format("the employer levy account balance in collection period {0} is {1}", collection_Period, levyBalance), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1339 = new TechTalk.SpecFlow.Table(new string[] {
                        "start date",
                        "end date",
                        "agreed price",
                        "status",
                        "Framework Code",
                        "Pathway Code",
                        "Programme Type"});
            table1339.AddRow(new string[] {
                        "03/Aug/Current Academic Year",
                        "08/Aug/Next Academic Year",
                        "7500",
                        "active",
                        "593",
                        "1",
                        "20"});
#line 69
 testRunner.And("the following commitments exist", ((string)(null)), table1339, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1340 = new TechTalk.SpecFlow.Table(new string[] {
                        "Start Date",
                        "Planned Duration",
                        "Total Training Price",
                        "Total Training Price Effective Date",
                        "Total Assessment Price",
                        "Total Assessment Price Effective Date",
                        "Actual Duration",
                        "Completion Status",
                        "Contract Type",
                        "Aim Sequence Number",
                        "Aim Reference",
                        "Framework Code",
                        "Pathway Code",
                        "Programme Type",
                        "Funding Line Type",
                        "SFA Contribution Percentage"});
            table1340.AddRow(new string[] {
                        "03/Aug/Current Academic Year",
                        "12 months",
                        "7500",
                        "03/Aug/Current Academic Year",
                        "",
                        "",
                        "",
                        "continuing",
                        "Act1",
                        "1",
                        "ZPROG001",
                        "593",
                        "1",
                        "20",
                        "19+ Apprenticeship (From May 2017) Non-Levy Contract (non-procured)",
                        "90%"});
#line 73
 testRunner.And("the provider is providing training for the following learners", ((string)(null)), table1340, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1341 = new TechTalk.SpecFlow.Table(new string[] {
                        "Price Episode Id",
                        "Total Training Price",
                        "Total Training Price Effective Date",
                        "Total Assessment Price",
                        "Total Assessment Price Effective Date",
                        "Contract Type",
                        "Aim Sequence Number",
                        "SFA Contribution Percentage"});
            table1341.AddRow(new string[] {
                        "pe-1",
                        "7500",
                        "03/Aug/Current Academic Year",
                        "",
                        "03/Aug/Current Academic Year",
                        "Act1",
                        "1",
                        "90%"});
#line 77
 testRunner.And("price details as follows", ((string)(null)), table1341, "And ");
#line 80
    testRunner.When(string.Format("the ILR file is submitted for the learners for collection period {0}", collection_Period), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table1342 = new TechTalk.SpecFlow.Table(new string[] {
                        "Delivery Period",
                        "On-Programme",
                        "Completion",
                        "Balancing",
                        "CareLeaverApprenticePayment",
                        "Price Episode Identifier"});
            table1342.AddRow(new string[] {
                        "Aug/Current Academic Year",
                        "500",
                        "0",
                        "0",
                        "0",
                        "pe-1"});
            table1342.AddRow(new string[] {
                        "Sep/Current Academic Year",
                        "500",
                        "0",
                        "0",
                        "0",
                        "pe-1"});
            table1342.AddRow(new string[] {
                        "Oct/Current Academic Year",
                        "500",
                        "0",
                        "0",
                        "1000",
                        "pe-1"});
            table1342.AddRow(new string[] {
                        "Nov/Current Academic Year",
                        "500",
                        "0",
                        "0",
                        "0",
                        "pe-1"});
            table1342.AddRow(new string[] {
                        "Dec/Current Academic Year",
                        "500",
                        "0",
                        "0",
                        "0",
                        "pe-1"});
            table1342.AddRow(new string[] {
                        "Jan/Current Academic Year",
                        "500",
                        "0",
                        "0",
                        "0",
                        "pe-1"});
            table1342.AddRow(new string[] {
                        "Feb/Current Academic Year",
                        "500",
                        "0",
                        "0",
                        "0",
                        "pe-1"});
            table1342.AddRow(new string[] {
                        "Mar/Current Academic Year",
                        "500",
                        "0",
                        "0",
                        "0",
                        "pe-1"});
            table1342.AddRow(new string[] {
                        "Apr/Current Academic Year",
                        "500",
                        "0",
                        "0",
                        "0",
                        "pe-1"});
            table1342.AddRow(new string[] {
                        "May/Current Academic Year",
                        "500",
                        "0",
                        "0",
                        "0",
                        "pe-1"});
            table1342.AddRow(new string[] {
                        "Jun/Current Academic Year",
                        "500",
                        "0",
                        "0",
                        "0",
                        "pe-1"});
            table1342.AddRow(new string[] {
                        "Jul/Current Academic Year",
                        "500",
                        "0",
                        "0",
                        "0",
                        "pe-1"});
#line 83
 testRunner.Then("the following learner earnings should be generated", ((string)(null)), table1342, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table1343 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection Period",
                        "Delivery Period",
                        "On-Programme",
                        "Completion",
                        "Balancing",
                        "CareLeaverApprenticePayment"});
            table1343.AddRow(new string[] {
                        "R01/Current Academic Year",
                        "Aug/Current Academic Year",
                        "500",
                        "0",
                        "0",
                        "0"});
            table1343.AddRow(new string[] {
                        "R02/Current Academic Year",
                        "Sep/Current Academic Year",
                        "500",
                        "0",
                        "0",
                        "0"});
            table1343.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Oct/Current Academic Year",
                        "500",
                        "0",
                        "0",
                        "1000"});
#line 98
 testRunner.And("at month end only the following payments will be calculated", ((string)(null)), table1343, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1344 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection Period",
                        "Delivery Period",
                        "Levy Payments",
                        "SFA Fully-Funded Payments",
                        "Transaction Type"});
            table1344.AddRow(new string[] {
                        "R01/Current Academic Year",
                        "Aug/Current Academic Year",
                        "500",
                        "0",
                        "Learning"});
            table1344.AddRow(new string[] {
                        "R02/Current Academic Year",
                        "Sep/Current Academic Year",
                        "500",
                        "0",
                        "Learning"});
            table1344.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Oct/Current Academic Year",
                        "500",
                        "0",
                        "Learning"});
            table1344.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Oct/Current Academic Year",
                        "0",
                        "1000",
                        "CareLeaverApprenticePayment"});
#line 105
 testRunner.And("only the following provider payments will be recorded", ((string)(null)), table1344, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1345 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection Period",
                        "Delivery Period",
                        "Levy Payments",
                        "SFA Fully-Funded Payments",
                        "Transaction Type"});
            table1345.AddRow(new string[] {
                        "R01/Current Academic Year",
                        "Aug/Current Academic Year",
                        "500",
                        "0",
                        "Learning"});
            table1345.AddRow(new string[] {
                        "R02/Current Academic Year",
                        "Sep/Current Academic Year",
                        "500",
                        "0",
                        "Learning"});
            table1345.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Oct/Current Academic Year",
                        "500",
                        "0",
                        "Learning"});
            table1345.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Oct/Current Academic Year",
                        "0",
                        "1000",
                        "CareLeaverApprenticePayment"});
#line 112
 testRunner.And("only the following provider payments will be generated", ((string)(null)), table1345, "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
