// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SFA.DAS.Payments.AcceptanceTests.EndToEnd.Tests.LearningSupportFunding
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Levy learner, takes an English qualification that has a planned end date that exc" +
        "eeds the actual end date of the programme aim and learning support is applicable" +
        " to all learning PV2-803")]
    public partial class LevyLearnerTakesAnEnglishQualificationThatHasAPlannedEndDateThatExceedsTheActualEndDateOfTheProgrammeAimAndLearningSupportIsApplicableToAllLearningPV2_803Feature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "PV2-803 - Levy learner - learning support applicable for maths and eng after main aim ended.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Levy learner, takes an English qualification that has a planned end date that exc" +
                    "eeds the actual end date of the programme aim and learning support is applicable" +
                    " to all learning PV2-803", "\t\tAs a provider,\r\n\t\tI want a Levy learner, with Learning Support, where English &" +
                    " Maths exceeds end date of programme aim\r\n\t\tSo that I am paid Learning Support b" +
                    "y SFA until English & Maths completes", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Levy learner, Eng aim planned end date exceeds the actual end date of the program" +
            "me aim and learning support is applicable to all learning PV2-803")]
        [NUnit.Framework.TestCaseAttribute("R01/Current Academic Year", "3500", null)]
        [NUnit.Framework.TestCaseAttribute("R02/Current Academic Year", "500", null)]
        [NUnit.Framework.TestCaseAttribute("R03/Current Academic Year", "500", null)]
        public virtual void LevyLearnerEngAimPlannedEndDateExceedsTheActualEndDateOfTheProgrammeAimAndLearningSupportIsApplicableToAllLearningPV2_803(string collection_Period, string levyBalance, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Levy learner, Eng aim planned end date exceeds the actual end date of the program" +
                    "me aim and learning support is applicable to all learning PV2-803", null, exampleTags);
#line 12
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 13
 testRunner.Given(string.Format("the employer levy account balance in collection period {0} is {1}", collection_Period, levyBalance), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1282 = new TechTalk.SpecFlow.Table(new string[] {
                        "start date",
                        "end date",
                        "agreed price",
                        "status",
                        "Framework Code",
                        "Pathway Code",
                        "Programme Type"});
            table1282.AddRow(new string[] {
                        "01/Aug/Last Academic Year",
                        "01/Aug/Current Academic Year",
                        "15000",
                        "active",
                        "593",
                        "1",
                        "20"});
#line 14
 testRunner.And("the following commitments exist", ((string)(null)), table1282, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1283 = new TechTalk.SpecFlow.Table(new string[] {
                        "Start Date",
                        "Planned Duration",
                        "Total Training Price",
                        "Total Training Price Effective Date",
                        "Total Assessment Price",
                        "Total Assessment Price Effective Date",
                        "Actual Duration",
                        "Completion Status",
                        "Contract Type",
                        "Aim Reference",
                        "SFA Contribution Percentage",
                        "Funding Line Type",
                        "Framework Code",
                        "Pathway Code",
                        "Programme Type"});
            table1283.AddRow(new string[] {
                        "06/Aug/Last Academic Year",
                        "12 months",
                        "12000",
                        "06/Aug/Last Academic Year",
                        "3000",
                        "06/Aug/Last Academic Year",
                        "",
                        "continuing",
                        "Act1",
                        "ZPROG001",
                        "90%",
                        "19-24 Apprenticeship Levy",
                        "593",
                        "1",
                        "20"});
#line 17
   testRunner.And("the provider previously submitted the following learner details", ((string)(null)), table1283, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1284 = new TechTalk.SpecFlow.Table(new string[] {
                        "Aim Type",
                        "Aim Reference",
                        "Start Date",
                        "Planned Duration",
                        "Actual Duration",
                        "Aim Sequence Number",
                        "Framework Code",
                        "Pathway Code",
                        "Programme Type",
                        "Funding Line Type",
                        "Completion Status",
                        "Price Episode Id"});
            table1284.AddRow(new string[] {
                        "Programme",
                        "ZPROG001",
                        "06/Aug/Last Academic Year",
                        "12 months",
                        "",
                        "1",
                        "593",
                        "1",
                        "20",
                        "19-24 Apprenticeship Levy",
                        "continuing",
                        "1st price details"});
            table1284.AddRow(new string[] {
                        "Maths or English",
                        "12345",
                        "06/Aug/Last Academic Year",
                        "14 months",
                        "",
                        "2",
                        "593",
                        "1",
                        "20",
                        "19-24 Apprenticeship Levy",
                        "continuing",
                        "2nd price details"});
#line 21
 testRunner.And("the following aims", ((string)(null)), table1284, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1285 = new TechTalk.SpecFlow.Table(new string[] {
                        "Price Episode Id",
                        "Total Training Price",
                        "Total Training Price Effective Date",
                        "Total Assessment Price",
                        "Total Assessment Price Effective Date",
                        "Contract Type",
                        "Aim Sequence Number",
                        "SFA Contribution Percentage"});
            table1285.AddRow(new string[] {
                        "1st price details",
                        "15000",
                        "06/Aug/Last Academic Year",
                        "0",
                        "06/Aug/Last Academic Year",
                        "Act1",
                        "1",
                        "90%"});
            table1285.AddRow(new string[] {
                        "",
                        "0",
                        "06/Aug/Last Academic Year",
                        "0",
                        "06/Aug/Last Academic Year",
                        "Act1",
                        "2",
                        "100%"});
#line 25
 testRunner.And("price details as follows", ((string)(null)), table1285, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1286 = new TechTalk.SpecFlow.Table(new string[] {
                        "Delivery Period",
                        "On-Programme",
                        "Completion",
                        "Balancing",
                        "LearningSupport",
                        "OnProgrammeMathsAndEnglish",
                        "Aim Sequence Number",
                        "Price Episode Identifier"});
            table1286.AddRow(new string[] {
                        "Aug/Last Academic Year",
                        "1000",
                        "0",
                        "0",
                        "150",
                        "0",
                        "1",
                        "1st price details"});
            table1286.AddRow(new string[] {
                        "Sep/Last Academic Year",
                        "1000",
                        "0",
                        "0",
                        "150",
                        "0",
                        "1",
                        "1st price details"});
            table1286.AddRow(new string[] {
                        "Oct/Last Academic Year",
                        "1000",
                        "0",
                        "0",
                        "150",
                        "0",
                        "1",
                        "1st price details"});
            table1286.AddRow(new string[] {
                        "Nov/Last Academic Year",
                        "1000",
                        "0",
                        "0",
                        "150",
                        "0",
                        "1",
                        "1st price details"});
            table1286.AddRow(new string[] {
                        "Dec/Last Academic Year",
                        "1000",
                        "0",
                        "0",
                        "150",
                        "0",
                        "1",
                        "1st price details"});
            table1286.AddRow(new string[] {
                        "Jan/Last Academic Year",
                        "1000",
                        "0",
                        "0",
                        "150",
                        "0",
                        "1",
                        "1st price details"});
            table1286.AddRow(new string[] {
                        "Feb/Last Academic Year",
                        "1000",
                        "0",
                        "0",
                        "150",
                        "0",
                        "1",
                        "1st price details"});
            table1286.AddRow(new string[] {
                        "Mar/Last Academic Year",
                        "1000",
                        "0",
                        "0",
                        "150",
                        "0",
                        "1",
                        "1st price details"});
            table1286.AddRow(new string[] {
                        "Apr/Last Academic Year",
                        "1000",
                        "0",
                        "0",
                        "150",
                        "0",
                        "1",
                        "1st price details"});
            table1286.AddRow(new string[] {
                        "May/Last Academic Year",
                        "1000",
                        "0",
                        "0",
                        "150",
                        "0",
                        "1",
                        "1st price details"});
            table1286.AddRow(new string[] {
                        "Jun/Last Academic Year",
                        "1000",
                        "0",
                        "0",
                        "150",
                        "0",
                        "1",
                        "1st price details"});
            table1286.AddRow(new string[] {
                        "Jul/Last Academic Year",
                        "1000",
                        "0",
                        "0",
                        "150",
                        "0",
                        "1",
                        "1st price details"});
            table1286.AddRow(new string[] {
                        "Aug/Last Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "33.64",
                        "2",
                        ""});
            table1286.AddRow(new string[] {
                        "Sep/Last Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "33.64",
                        "2",
                        ""});
            table1286.AddRow(new string[] {
                        "Oct/Last Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "33.64",
                        "2",
                        ""});
            table1286.AddRow(new string[] {
                        "Nov/Last Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "33.64",
                        "2",
                        ""});
            table1286.AddRow(new string[] {
                        "Dec/Last Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "33.64",
                        "2",
                        ""});
            table1286.AddRow(new string[] {
                        "Jan/Last Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "33.64",
                        "2",
                        ""});
            table1286.AddRow(new string[] {
                        "Feb/Last Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "33.64",
                        "2",
                        ""});
            table1286.AddRow(new string[] {
                        "Mar/Last Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "33.64",
                        "2",
                        ""});
            table1286.AddRow(new string[] {
                        "Apr/Last Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "33.64",
                        "2",
                        ""});
            table1286.AddRow(new string[] {
                        "May/Last Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "33.64",
                        "2",
                        ""});
            table1286.AddRow(new string[] {
                        "Jun/Last Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "33.64",
                        "2",
                        ""});
            table1286.AddRow(new string[] {
                        "Jul/Last Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "33.64",
                        "2",
                        ""});
#line 29
    testRunner.And("the following earnings had been generated for the learner", ((string)(null)), table1286, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1287 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection Period",
                        "Delivery Period",
                        "Levy Payments",
                        "SFA Fully-Funded Payments",
                        "Transaction Type"});
            table1287.AddRow(new string[] {
                        "R01/Last Academic Year",
                        "Aug/Last Academic Year",
                        "1000",
                        "0",
                        "Learning"});
            table1287.AddRow(new string[] {
                        "R02/Last Academic Year",
                        "Sep/Last Academic Year",
                        "1000",
                        "0",
                        "Learning"});
            table1287.AddRow(new string[] {
                        "R03/Last Academic Year",
                        "Oct/Last Academic Year",
                        "1000",
                        "0",
                        "Learning"});
            table1287.AddRow(new string[] {
                        "R04/Last Academic Year",
                        "Nov/Last Academic Year",
                        "1000",
                        "0",
                        "Learning"});
            table1287.AddRow(new string[] {
                        "R05/Last Academic Year",
                        "Dec/Last Academic Year",
                        "1000",
                        "0",
                        "Learning"});
            table1287.AddRow(new string[] {
                        "R06/Last Academic Year",
                        "Jan/Last Academic Year",
                        "1000",
                        "0",
                        "Learning"});
            table1287.AddRow(new string[] {
                        "R07/Last Academic Year",
                        "Feb/Last Academic Year",
                        "1000",
                        "0",
                        "Learning"});
            table1287.AddRow(new string[] {
                        "R08/Last Academic Year",
                        "Mar/Last Academic Year",
                        "1000",
                        "0",
                        "Learning"});
            table1287.AddRow(new string[] {
                        "R09/Last Academic Year",
                        "Apr/Last Academic Year",
                        "1000",
                        "0",
                        "Learning"});
            table1287.AddRow(new string[] {
                        "R10/Last Academic Year",
                        "May/Last Academic Year",
                        "1000",
                        "0",
                        "Learning"});
            table1287.AddRow(new string[] {
                        "R11/Last Academic Year",
                        "Jun/Last Academic Year",
                        "1000",
                        "0",
                        "Learning"});
            table1287.AddRow(new string[] {
                        "R12/Last Academic Year",
                        "Jul/Last Academic Year",
                        "1000",
                        "0",
                        "Learning"});
            table1287.AddRow(new string[] {
                        "R01/Last Academic Year",
                        "Aug/Last Academic Year",
                        "0",
                        "150",
                        "LearningSupport"});
            table1287.AddRow(new string[] {
                        "R02/Last Academic Year",
                        "Sep/Last Academic Year",
                        "0",
                        "150",
                        "LearningSupport"});
            table1287.AddRow(new string[] {
                        "R03/Last Academic Year",
                        "Oct/Last Academic Year",
                        "0",
                        "150",
                        "LearningSupport"});
            table1287.AddRow(new string[] {
                        "R04/Last Academic Year",
                        "Nov/Last Academic Year",
                        "0",
                        "150",
                        "LearningSupport"});
            table1287.AddRow(new string[] {
                        "R05/Last Academic Year",
                        "Dec/Last Academic Year",
                        "0",
                        "150",
                        "LearningSupport"});
            table1287.AddRow(new string[] {
                        "R06/Last Academic Year",
                        "Jan/Last Academic Year",
                        "0",
                        "150",
                        "LearningSupport"});
            table1287.AddRow(new string[] {
                        "R07/Last Academic Year",
                        "Feb/Last Academic Year",
                        "0",
                        "150",
                        "LearningSupport"});
            table1287.AddRow(new string[] {
                        "R08/Last Academic Year",
                        "Mar/Last Academic Year",
                        "0",
                        "150",
                        "LearningSupport"});
            table1287.AddRow(new string[] {
                        "R09/Last Academic Year",
                        "Apr/Last Academic Year",
                        "0",
                        "150",
                        "LearningSupport"});
            table1287.AddRow(new string[] {
                        "R10/Last Academic Year",
                        "May/Last Academic Year",
                        "0",
                        "150",
                        "LearningSupport"});
            table1287.AddRow(new string[] {
                        "R11/Last Academic Year",
                        "Jun/Last Academic Year",
                        "0",
                        "150",
                        "LearningSupport"});
            table1287.AddRow(new string[] {
                        "R12/Last Academic Year",
                        "Jul/Last Academic Year",
                        "0",
                        "150",
                        "LearningSupport"});
            table1287.AddRow(new string[] {
                        "R01/Last Academic Year",
                        "Aug/Last Academic Year",
                        "0",
                        "33.64",
                        "OnProgrammeMathsAndEnglish"});
            table1287.AddRow(new string[] {
                        "R02/Last Academic Year",
                        "Sep/Last Academic Year",
                        "0",
                        "33.64",
                        "OnProgrammeMathsAndEnglish"});
            table1287.AddRow(new string[] {
                        "R03/Last Academic Year",
                        "Oct/Last Academic Year",
                        "0",
                        "33.64",
                        "OnProgrammeMathsAndEnglish"});
            table1287.AddRow(new string[] {
                        "R04/Last Academic Year",
                        "Nov/Last Academic Year",
                        "0",
                        "33.64",
                        "OnProgrammeMathsAndEnglish"});
            table1287.AddRow(new string[] {
                        "R05/Last Academic Year",
                        "Dec/Last Academic Year",
                        "0",
                        "33.64",
                        "OnProgrammeMathsAndEnglish"});
            table1287.AddRow(new string[] {
                        "R06/Last Academic Year",
                        "Jan/Last Academic Year",
                        "0",
                        "33.64",
                        "OnProgrammeMathsAndEnglish"});
            table1287.AddRow(new string[] {
                        "R07/Last Academic Year",
                        "Feb/Last Academic Year",
                        "0",
                        "33.64",
                        "OnProgrammeMathsAndEnglish"});
            table1287.AddRow(new string[] {
                        "R08/Last Academic Year",
                        "Mar/Last Academic Year",
                        "0",
                        "33.64",
                        "OnProgrammeMathsAndEnglish"});
            table1287.AddRow(new string[] {
                        "R09/Last Academic Year",
                        "Apr/Last Academic Year",
                        "0",
                        "33.64",
                        "OnProgrammeMathsAndEnglish"});
            table1287.AddRow(new string[] {
                        "R10/Last Academic Year",
                        "May/Last Academic Year",
                        "0",
                        "33.64",
                        "OnProgrammeMathsAndEnglish"});
            table1287.AddRow(new string[] {
                        "R11/Last Academic Year",
                        "Jun/Last Academic Year",
                        "0",
                        "33.64",
                        "OnProgrammeMathsAndEnglish"});
            table1287.AddRow(new string[] {
                        "R12/Last Academic Year",
                        "Jul/Last Academic Year",
                        "0",
                        "33.64",
                        "OnProgrammeMathsAndEnglish"});
#line 56
    testRunner.And("the following provider payments had been generated", ((string)(null)), table1287, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1288 = new TechTalk.SpecFlow.Table(new string[] {
                        "Aim Type",
                        "Aim Reference",
                        "Start Date",
                        "Planned Duration",
                        "Actual Duration",
                        "Aim Sequence Number",
                        "Framework Code",
                        "Pathway Code",
                        "Programme Type",
                        "Funding Line Type",
                        "Completion Status",
                        "Price Episode Id"});
            table1288.AddRow(new string[] {
                        "Programme",
                        "ZPROG001",
                        "06/Aug/Last Academic Year",
                        "12 months",
                        "12 months",
                        "1",
                        "593",
                        "1",
                        "20",
                        "19-24 Apprenticeship Levy",
                        "completed",
                        "1st price details"});
            table1288.AddRow(new string[] {
                        "Maths or English",
                        "12345",
                        "06/Aug/Last Academic Year",
                        "14 months",
                        "14 months",
                        "2",
                        "593",
                        "1",
                        "20",
                        "19-24 Apprenticeship Levy",
                        "completed",
                        "2nd price details"});
#line 94
    testRunner.But("aims details are changed as follows", ((string)(null)), table1288, "But ");
#line hidden
            TechTalk.SpecFlow.Table table1289 = new TechTalk.SpecFlow.Table(new string[] {
                        "Price Episode Id",
                        "Total Training Price",
                        "Total Training Price Effective Date",
                        "Total Assessment Price",
                        "Total Assessment Price Effective Date",
                        "Contract Type",
                        "Aim Sequence Number",
                        "SFA Contribution Percentage"});
            table1289.AddRow(new string[] {
                        "1st price details",
                        "15000",
                        "06/Aug/Last Academic Year",
                        "0",
                        "06/Aug/Last Academic Year",
                        "Act1",
                        "1",
                        "90%"});
            table1289.AddRow(new string[] {
                        "",
                        "0",
                        "06/Aug/Last Academic Year",
                        "0",
                        "06/Aug/Last Academic Year",
                        "Act1",
                        "2",
                        "100%"});
#line 98
 testRunner.And("price details as follows", ((string)(null)), table1289, "And ");
#line 102
    testRunner.When(string.Format("the amended ILR file is re-submitted for the learners in collection period {0}", collection_Period), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table1290 = new TechTalk.SpecFlow.Table(new string[] {
                        "Delivery Period",
                        "On-Programme",
                        "Completion",
                        "Balancing",
                        "LearningSupport",
                        "OnProgrammeMathsAndEnglish",
                        "Aim Sequence Number",
                        "Price Episode Identifier",
                        "Contract Type"});
            table1290.AddRow(new string[] {
                        "Aug/Current Academic Year",
                        "0",
                        "3000",
                        "0",
                        "0",
                        "0",
                        "1",
                        "1st price details",
                        "Act1"});
            table1290.AddRow(new string[] {
                        "Sep/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "1",
                        "1st price details",
                        "Act1"});
            table1290.AddRow(new string[] {
                        "Oct/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "1",
                        "1st price details",
                        "Act1"});
            table1290.AddRow(new string[] {
                        "Nov/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "1",
                        "1st price details",
                        "Act1"});
            table1290.AddRow(new string[] {
                        "Dec/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "1",
                        "1st price details",
                        "Act1"});
            table1290.AddRow(new string[] {
                        "Jan/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "1",
                        "1st price details",
                        "Act1"});
            table1290.AddRow(new string[] {
                        "Feb/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "1",
                        "1st price details",
                        "Act1"});
            table1290.AddRow(new string[] {
                        "Mar/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "1",
                        "1st price details",
                        "Act1"});
            table1290.AddRow(new string[] {
                        "Apr/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "1",
                        "1st price details",
                        "Act1"});
            table1290.AddRow(new string[] {
                        "May/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "1",
                        "1st price details",
                        "Act1"});
            table1290.AddRow(new string[] {
                        "Jun/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "1",
                        "1st price details",
                        "Act1"});
            table1290.AddRow(new string[] {
                        "Jul/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "1",
                        "1st price details",
                        "Act1"});
            table1290.AddRow(new string[] {
                        "Aug/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "150",
                        "33.64",
                        "2",
                        "",
                        "Act1"});
            table1290.AddRow(new string[] {
                        "Sep/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "150",
                        "33.64",
                        "2",
                        "",
                        "Act1"});
            table1290.AddRow(new string[] {
                        "Oct/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "2",
                        "",
                        "Act1"});
            table1290.AddRow(new string[] {
                        "Nov/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "2",
                        "",
                        "Act1"});
            table1290.AddRow(new string[] {
                        "Dec/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "2",
                        "",
                        "Act1"});
            table1290.AddRow(new string[] {
                        "Jan/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "2",
                        "",
                        "Act1"});
            table1290.AddRow(new string[] {
                        "Feb/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "2",
                        "",
                        "Act1"});
            table1290.AddRow(new string[] {
                        "Mar/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "2",
                        "",
                        "Act1"});
            table1290.AddRow(new string[] {
                        "Apr/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "2",
                        "",
                        "Act1"});
            table1290.AddRow(new string[] {
                        "May/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "2",
                        "",
                        "Act1"});
            table1290.AddRow(new string[] {
                        "Jun/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "2",
                        "",
                        "Act1"});
            table1290.AddRow(new string[] {
                        "Jul/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "2",
                        "",
                        "Act1"});
#line 103
    testRunner.Then("the following learner earnings should be generated", ((string)(null)), table1290, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table1291 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection Period",
                        "Delivery Period",
                        "On-Programme",
                        "Completion",
                        "Balancing",
                        "LearningSupport",
                        "OnProgrammeMathsAndEnglish"});
            table1291.AddRow(new string[] {
                        "R01/Current Academic Year",
                        "Aug/Current Academic Year",
                        "0",
                        "3000",
                        "0",
                        "150",
                        "33.64"});
            table1291.AddRow(new string[] {
                        "R02/Current Academic Year",
                        "Sep/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "150",
                        "33.64"});
            table1291.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Oct/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table1291.AddRow(new string[] {
                        "R04/Current Academic Year",
                        "Nov/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table1291.AddRow(new string[] {
                        "R05/Current Academic Year",
                        "Dec/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table1291.AddRow(new string[] {
                        "R06/Current Academic Year",
                        "Jan/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table1291.AddRow(new string[] {
                        "R07/Current Academic Year",
                        "Feb/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table1291.AddRow(new string[] {
                        "R08/Current Academic Year",
                        "Mar/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table1291.AddRow(new string[] {
                        "R09/Current Academic Year",
                        "Apr/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table1291.AddRow(new string[] {
                        "R10/Current Academic Year",
                        "May/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table1291.AddRow(new string[] {
                        "R11/Current Academic Year",
                        "Jun/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table1291.AddRow(new string[] {
                        "R12/Current Academic Year",
                        "Jul/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
#line 130
    testRunner.And("at month end only the following payments will be calculated", ((string)(null)), table1291, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1292 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection Period",
                        "Delivery Period",
                        "Levy Payments",
                        "SFA Fully-Funded Payments",
                        "Transaction Type"});
            table1292.AddRow(new string[] {
                        "R01/Current Academic Year",
                        "Aug/Current Academic Year",
                        "3000",
                        "0",
                        "Completion"});
            table1292.AddRow(new string[] {
                        "R01/Current Academic Year",
                        "Aug/Current Academic Year",
                        "0",
                        "150",
                        "LearningSupport"});
            table1292.AddRow(new string[] {
                        "R02/Current Academic Year",
                        "Sep/Current Academic Year",
                        "0",
                        "150",
                        "LearningSupport"});
            table1292.AddRow(new string[] {
                        "R01/Current Academic Year",
                        "Aug/Current Academic Year",
                        "0",
                        "33.64",
                        "OnProgrammeMathsAndEnglish"});
            table1292.AddRow(new string[] {
                        "R02/Current Academic Year",
                        "Sep/Current Academic Year",
                        "0",
                        "33.64",
                        "OnProgrammeMathsAndEnglish"});
#line 144
    testRunner.And("only the following provider payments will be recorded", ((string)(null)), table1292, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1293 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection Period",
                        "Delivery Period",
                        "Levy Payments",
                        "SFA Fully-Funded Payments",
                        "Transaction Type"});
            table1293.AddRow(new string[] {
                        "R01/Current Academic Year",
                        "Aug/Current Academic Year",
                        "3000",
                        "0",
                        "Completion"});
            table1293.AddRow(new string[] {
                        "R01/Current Academic Year",
                        "Aug/Current Academic Year",
                        "0",
                        "150",
                        "LearningSupport"});
            table1293.AddRow(new string[] {
                        "R02/Current Academic Year",
                        "Sep/Current Academic Year",
                        "0",
                        "150",
                        "LearningSupport"});
            table1293.AddRow(new string[] {
                        "R01/Current Academic Year",
                        "Aug/Current Academic Year",
                        "0",
                        "33.64",
                        "OnProgrammeMathsAndEnglish"});
            table1293.AddRow(new string[] {
                        "R02/Current Academic Year",
                        "Sep/Current Academic Year",
                        "0",
                        "33.64",
                        "OnProgrammeMathsAndEnglish"});
#line 151
 testRunner.And("only the following provider payments will be generated", ((string)(null)), table1293, "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
