// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SFA.DAS.Payments.AcceptanceTests.EndToEnd.Tests.Levy_DataLocks
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("PV2-769 - DLOCK03 mismatch in standard code")]
    public partial class PV2_769_DLOCK03MismatchInStandardCodeFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "PV2-769 - DLOCK03 mismatch in standard code.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "PV2-769 - DLOCK03 mismatch in standard code", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 30
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("ILR changes before second Commitment starts (i.e. there is only one existing Comm" +
            "itment in place) produces DLOCK_03 PV2-769")]
        public virtual void ILRChangesBeforeSecondCommitmentStartsI_E_ThereIsOnlyOneExistingCommitmentInPlaceProducesDLOCK_03PV2_769()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ILR changes before second Commitment starts (i.e. there is only one existing Comm" +
                    "itment in place) produces DLOCK_03 PV2-769", null, ((string[])(null)));
#line 35
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 30
this.FeatureBackground();
#line 37
 testRunner.Given("the employer levy account balance in collection period R01/Current Academic Year " +
                    "is 15000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1439 = new TechTalk.SpecFlow.Table(new string[] {
                        "Identifier",
                        "standard code",
                        "programme type",
                        "pathway code",
                        "agreed price",
                        "start date",
                        "end date",
                        "status",
                        "effective from"});
            table1439.AddRow(new string[] {
                        "Apprenticeship a",
                        "51",
                        "25",
                        "1",
                        "15000",
                        "03/Aug/Current Academic Year",
                        "04/Aug/Next Academic Year",
                        "active",
                        "03/Aug/Current Academic Year"});
#line 38
 testRunner.And("the following commitments exist", ((string)(null)), table1439, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1440 = new TechTalk.SpecFlow.Table(new string[] {
                        "Learner Reference Number"});
            table1440.AddRow(new string[] {
                        "abc123"});
#line 41
 testRunner.And("the following learners", ((string)(null)), table1440, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1441 = new TechTalk.SpecFlow.Table(new string[] {
                        "Aim Type",
                        "Aim Reference",
                        "Start Date",
                        "Planned Duration",
                        "Actual Duration",
                        "Aim Sequence Number",
                        "Pathway Code",
                        "standard code",
                        "programme type",
                        "Funding Line Type",
                        "Completion Status"});
            table1441.AddRow(new string[] {
                        "Programme",
                        "ZPROG001",
                        "03/Aug/Current Academic Year",
                        "12 months",
                        "3 months",
                        "1",
                        "1",
                        "51",
                        "25",
                        "16-18 Apprenticeship (From May 2017) Levy Contract",
                        "withdrawn"});
            table1441.AddRow(new string[] {
                        "Programme",
                        "ZPROG001",
                        "02/Nov/Current Academic Year",
                        "12 months",
                        "",
                        "2",
                        "1",
                        "52",
                        "25",
                        "16-18 Apprenticeship (From May 2017) Levy Contract",
                        "continuing"});
#line 44
 testRunner.And("the following aims", ((string)(null)), table1441, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1442 = new TechTalk.SpecFlow.Table(new string[] {
                        "Price Episode Id",
                        "Total Training Price",
                        "Total Training Price Effective Date",
                        "Contract Type",
                        "SFA Contribution Percentage",
                        "Aim Sequence Number",
                        "Total Assessment Price"});
            table1442.AddRow(new string[] {
                        "pe-1",
                        "12000",
                        "03/Aug/Current Academic Year",
                        "Act1",
                        "90%",
                        "1",
                        "3000"});
            table1442.AddRow(new string[] {
                        "pe-2",
                        "4500",
                        "03/Nov/Current Academic Year",
                        "Act1",
                        "90%",
                        "2",
                        "1125"});
#line 48
 testRunner.And("price details as follows", ((string)(null)), table1442, "And ");
#line 52
 testRunner.When("the amended ILR file is re-submitted for the learners in collection period R05/Cu" +
                    "rrent Academic Year", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table1443 = new TechTalk.SpecFlow.Table(new string[] {
                        "Delivery Period",
                        "On-Programme",
                        "Completion",
                        "Balancing",
                        "Price Episode Identifier"});
            table1443.AddRow(new string[] {
                        "Aug/Current Academic Year",
                        "1000",
                        "0",
                        "0",
                        "pe-1"});
            table1443.AddRow(new string[] {
                        "Sep/Current Academic Year",
                        "1000",
                        "0",
                        "0",
                        "pe-1"});
            table1443.AddRow(new string[] {
                        "Oct/Current Academic Year",
                        "1000",
                        "0",
                        "0",
                        "pe-1"});
            table1443.AddRow(new string[] {
                        "Nov/Current Academic Year",
                        "500",
                        "0",
                        "0",
                        "pe-2"});
            table1443.AddRow(new string[] {
                        "Dec/Current Academic Year",
                        "500",
                        "0",
                        "0",
                        "pe-2"});
            table1443.AddRow(new string[] {
                        "Jan/Current Academic Year",
                        "500",
                        "0",
                        "0",
                        "pe-2"});
            table1443.AddRow(new string[] {
                        "Feb/Current Academic Year",
                        "500",
                        "0",
                        "0",
                        "pe-2"});
            table1443.AddRow(new string[] {
                        "Mar/Current Academic Year",
                        "500",
                        "0",
                        "0",
                        "pe-2"});
            table1443.AddRow(new string[] {
                        "Apr/Current Academic Year",
                        "500",
                        "0",
                        "0",
                        "pe-2"});
            table1443.AddRow(new string[] {
                        "May/Current Academic Year",
                        "500",
                        "0",
                        "0",
                        "pe-2"});
            table1443.AddRow(new string[] {
                        "Jun/Current Academic Year",
                        "500",
                        "0",
                        "0",
                        "pe-2"});
            table1443.AddRow(new string[] {
                        "Jul/Current Academic Year",
                        "500",
                        "0",
                        "0",
                        "pe-2"});
#line 54
 testRunner.Then("the following learner earnings should be generated", ((string)(null)), table1443, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table1444 = new TechTalk.SpecFlow.Table(new string[] {
                        "Apprenticeship",
                        "Delivery Period",
                        "Transaction Type",
                        "standard code",
                        "programme type",
                        "pathway code",
                        "Error Code",
                        "Price Episode Identifier"});
            table1444.AddRow(new string[] {
                        "Apprenticeship a",
                        "Nov/Current Academic Year",
                        "Learning",
                        "52",
                        "25",
                        "1",
                        "DLOCK_03",
                        "pe-2"});
            table1444.AddRow(new string[] {
                        "Apprenticeship a",
                        "Nov/Current Academic Year",
                        "Learning",
                        "52",
                        "25",
                        "1",
                        "DLOCK_07",
                        "pe-2"});
            table1444.AddRow(new string[] {
                        "Apprenticeship a",
                        "Dec/Current Academic Year",
                        "Learning",
                        "52",
                        "25",
                        "1",
                        "DLOCK_03",
                        "pe-2"});
            table1444.AddRow(new string[] {
                        "Apprenticeship a",
                        "Dec/Current Academic Year",
                        "Learning",
                        "52",
                        "25",
                        "1",
                        "DLOCK_07",
                        "pe-2"});
            table1444.AddRow(new string[] {
                        "Apprenticeship a",
                        "Jan/Current Academic Year",
                        "Learning",
                        "52",
                        "25",
                        "1",
                        "DLOCK_03",
                        "pe-2"});
            table1444.AddRow(new string[] {
                        "Apprenticeship a",
                        "Jan/Current Academic Year",
                        "Learning",
                        "52",
                        "25",
                        "1",
                        "DLOCK_07",
                        "pe-2"});
            table1444.AddRow(new string[] {
                        "Apprenticeship a",
                        "Feb/Current Academic Year",
                        "Learning",
                        "52",
                        "25",
                        "1",
                        "DLOCK_03",
                        "pe-2"});
            table1444.AddRow(new string[] {
                        "Apprenticeship a",
                        "Feb/Current Academic Year",
                        "Learning",
                        "52",
                        "25",
                        "1",
                        "DLOCK_07",
                        "pe-2"});
            table1444.AddRow(new string[] {
                        "Apprenticeship a",
                        "Mar/Current Academic Year",
                        "Learning",
                        "52",
                        "25",
                        "1",
                        "DLOCK_03",
                        "pe-2"});
            table1444.AddRow(new string[] {
                        "Apprenticeship a",
                        "Mar/Current Academic Year",
                        "Learning",
                        "52",
                        "25",
                        "1",
                        "DLOCK_07",
                        "pe-2"});
            table1444.AddRow(new string[] {
                        "Apprenticeship a",
                        "Apr/Current Academic Year",
                        "Learning",
                        "52",
                        "25",
                        "1",
                        "DLOCK_03",
                        "pe-2"});
            table1444.AddRow(new string[] {
                        "Apprenticeship a",
                        "Apr/Current Academic Year",
                        "Learning",
                        "52",
                        "25",
                        "1",
                        "DLOCK_07",
                        "pe-2"});
            table1444.AddRow(new string[] {
                        "Apprenticeship a",
                        "May/Current Academic Year",
                        "Learning",
                        "52",
                        "25",
                        "1",
                        "DLOCK_03",
                        "pe-2"});
            table1444.AddRow(new string[] {
                        "Apprenticeship a",
                        "May/Current Academic Year",
                        "Learning",
                        "52",
                        "25",
                        "1",
                        "DLOCK_07",
                        "pe-2"});
            table1444.AddRow(new string[] {
                        "Apprenticeship a",
                        "Jun/Current Academic Year",
                        "Learning",
                        "52",
                        "25",
                        "1",
                        "DLOCK_03",
                        "pe-2"});
            table1444.AddRow(new string[] {
                        "Apprenticeship a",
                        "Jun/Current Academic Year",
                        "Learning",
                        "52",
                        "25",
                        "1",
                        "DLOCK_07",
                        "pe-2"});
            table1444.AddRow(new string[] {
                        "Apprenticeship a",
                        "Jul/Current Academic Year",
                        "Learning",
                        "52",
                        "25",
                        "1",
                        "DLOCK_03",
                        "pe-2"});
            table1444.AddRow(new string[] {
                        "Apprenticeship a",
                        "Jul/Current Academic Year",
                        "Learning",
                        "52",
                        "25",
                        "1",
                        "DLOCK_07",
                        "pe-2"});
#line 68
 testRunner.Then("the following data lock failures were generated", ((string)(null)), table1444, "Then ");
#line 88
 testRunner.And("Month end is triggered", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1445 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection Period",
                        "Delivery Period",
                        "Levy Payments",
                        "Transaction Type",
                        "Price Episode Identifier",
                        "standard code"});
            table1445.AddRow(new string[] {
                        "R05/Current Academic Year",
                        "Aug/Current Academic Year",
                        "1000",
                        "Learning",
                        "pe-1",
                        "51"});
            table1445.AddRow(new string[] {
                        "R05/Current Academic Year",
                        "Sep/Current Academic Year",
                        "1000",
                        "Learning",
                        "pe-1",
                        "51"});
            table1445.AddRow(new string[] {
                        "R05/Current Academic Year",
                        "Oct/Current Academic Year",
                        "1000",
                        "Learning",
                        "pe-1",
                        "51"});
            table1445.AddRow(new string[] {
                        "R05/Current Academic Year",
                        "Nov/Current Academic Year",
                        "0",
                        "Learning",
                        "pe-1",
                        "51"});
            table1445.AddRow(new string[] {
                        "R05/Current Academic Year",
                        "Dec/Current Academic Year",
                        "0",
                        "Learning",
                        "pe-1",
                        "51"});
            table1445.AddRow(new string[] {
                        "R05/Current Academic Year",
                        "Jan/Current Academic Year",
                        "0",
                        "Learning",
                        "pe-1",
                        "51"});
            table1445.AddRow(new string[] {
                        "R05/Current Academic Year",
                        "Feb/Current Academic Year",
                        "0",
                        "Learning",
                        "pe-1",
                        "51"});
            table1445.AddRow(new string[] {
                        "R05/Current Academic Year",
                        "Mar/Current Academic Year",
                        "0",
                        "Learning",
                        "pe-1",
                        "51"});
            table1445.AddRow(new string[] {
                        "R05/Current Academic Year",
                        "Apr/Current Academic Year",
                        "0",
                        "Learning",
                        "pe-1",
                        "51"});
            table1445.AddRow(new string[] {
                        "R05/Current Academic Year",
                        "May/Current Academic Year",
                        "0",
                        "Learning",
                        "pe-1",
                        "51"});
            table1445.AddRow(new string[] {
                        "R05/Current Academic Year",
                        "Jun/Current Academic Year",
                        "0",
                        "Learning",
                        "pe-1",
                        "51"});
            table1445.AddRow(new string[] {
                        "R05/Current Academic Year",
                        "Jul/Current Academic Year",
                        "0",
                        "Learning",
                        "pe-1",
                        "51"});
#line 89
 testRunner.And("only the following provider payments will be recorded", ((string)(null)), table1445, "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
