// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SFA.DAS.Payments.AcceptanceTests.EndToEnd.Tests.Levy_DataLocks
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("DLOCK01 - When no matching record found in an employer digital account for the UK" +
        "PRN then datalock DLOCK_01 will be produced PV2-662")]
    public partial class DLOCK01_WhenNoMatchingRecordFoundInAnEmployerDigitalAccountForTheUKPRNThenDatalockDLOCK_01WillBeProducedPV2_662Feature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "PV2-662 - DLOCK01 when no matching record found for the UKPRN.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "DLOCK01 - When no matching record found in an employer digital account for the UK" +
                    "PRN then datalock DLOCK_01 will be produced PV2-662", "\t\tAs a provider,\r\n\t\tI want to be notified with a DLOCK01 When no matching record " +
                    "is found in an employer digital account for the UKPRN\r\n\t\tSo that I can correct t" +
                    "he data mis-match between the Commitment and ILR", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("DLOCK01 - When no matching record found in an employer digital account for the UK" +
            "PRN then datalock DLOCK_01 will be produced PV2-662")]
        [NUnit.Framework.TestCaseAttribute("R01/Current Academic Year", null)]
        [NUnit.Framework.TestCaseAttribute("R02/Current Academic Year", null)]
        [NUnit.Framework.TestCaseAttribute("R03/Current Academic Year", null)]
        [NUnit.Framework.TestCaseAttribute("R04/Current Academic Year", null)]
        [NUnit.Framework.TestCaseAttribute("R05/Current Academic Year", null)]
        [NUnit.Framework.TestCaseAttribute("R06/Current Academic Year", null)]
        [NUnit.Framework.TestCaseAttribute("R07/Current Academic Year", null)]
        [NUnit.Framework.TestCaseAttribute("R08/Current Academic Year", null)]
        [NUnit.Framework.TestCaseAttribute("R09/Current Academic Year", null)]
        [NUnit.Framework.TestCaseAttribute("R10/Current Academic Year", null)]
        [NUnit.Framework.TestCaseAttribute("R11/Current Academic Year", null)]
        [NUnit.Framework.TestCaseAttribute("R12/Current Academic Year", null)]
        public virtual void DLOCK01_WhenNoMatchingRecordFoundInAnEmployerDigitalAccountForTheUKPRNThenDatalockDLOCK_01WillBeProducedPV2_662(string collection_Period, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("DLOCK01 - When no matching record found in an employer digital account for the UK" +
                    "PRN then datalock DLOCK_01 will be produced PV2-662", null, exampleTags);
#line 7
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 8
 testRunner.Given("the employer levy account balance in collection period R12/Current Academic Year " +
                    "is 10000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1356 = new TechTalk.SpecFlow.Table(new string[] {
                        "Identifier",
                        "Provider",
                        "Learner ID",
                        "framework code",
                        "programme type",
                        "pathway code",
                        "agreed price",
                        "start date",
                        "end date",
                        "status",
                        "effective from"});
            table1356.AddRow(new string[] {
                        "Apprenticeship a",
                        "Provider b",
                        "learner a",
                        "593",
                        "20",
                        "1",
                        "10000",
                        "01/Aug/Current Academic Year",
                        "01/Aug/Next Academic Year",
                        "active",
                        "01/Aug/Current Academic Year"});
#line 9
 testRunner.And("the following commitments exist", ((string)(null)), table1356, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1357 = new TechTalk.SpecFlow.Table(new string[] {
                        "Learner ID",
                        "Start Date",
                        "Planned Duration",
                        "Total Training Price",
                        "Total Training Price Effective Date",
                        "Total Assessment Price",
                        "Total Assessment Price Effective Date",
                        "Actual Duration",
                        "Completion Status",
                        "Contract Type",
                        "Aim Sequence Number",
                        "Aim Reference",
                        "Framework Code",
                        "Pathway Code",
                        "Programme Type",
                        "Funding Line Type",
                        "SFA Contribution Percentage"});
            table1357.AddRow(new string[] {
                        "learner a",
                        "01/Aug/Current Academic Year",
                        "12 months",
                        "10000",
                        "01/Aug/Current Academic Year",
                        "",
                        "",
                        "",
                        "continuing",
                        "Act1",
                        "1",
                        "ZPROG001",
                        "593",
                        "1",
                        "20",
                        "16-18 Apprenticeship (From May 2017) Levy Contract",
                        "90%"});
#line 12
 testRunner.And("the \"provider a\" is providing training for the following learners", ((string)(null)), table1357, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1358 = new TechTalk.SpecFlow.Table(new string[] {
                        "Price Episode Id",
                        "Total Training Price",
                        "Total Training Price Effective Date",
                        "Contract Type",
                        "SFA Contribution Percentage"});
            table1358.AddRow(new string[] {
                        "pe-1",
                        "10000",
                        "01/Aug/Current Academic Year",
                        "Act1",
                        "90%"});
#line 15
    testRunner.And("price details as follows", ((string)(null)), table1358, "And ");
#line 18
 testRunner.When(string.Format("the ILR file is submitted for the learners for the collection period {0} by \"prov" +
                        "ider a\"", collection_Period), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table1359 = new TechTalk.SpecFlow.Table(new string[] {
                        "Delivery Period",
                        "On-Programme",
                        "Completion",
                        "Balancing",
                        "First16To18EmployerIncentive",
                        "First16To18ProviderIncentive",
                        "Second16To18EmployerIncentive",
                        "Second16To18ProviderIncentive",
                        "OnProgramme16To18FrameworkUplift",
                        "LearningSupport",
                        "FirstDisadvantagePayment",
                        "SecondDisadvantagePayment",
                        "Learner ID",
                        "Price Episode Identifier"});
            table1359.AddRow(new string[] {
                        "Aug/Current Academic Year",
                        "666.66667",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "120",
                        "150",
                        "0",
                        "0",
                        "learner a",
                        "pe-1"});
            table1359.AddRow(new string[] {
                        "Sep/Current Academic Year",
                        "666.66667",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "120",
                        "150",
                        "0",
                        "0",
                        "learner a",
                        "pe-1"});
            table1359.AddRow(new string[] {
                        "Oct/Current Academic Year",
                        "666.66667",
                        "0",
                        "0",
                        "500",
                        "500",
                        "0",
                        "0",
                        "120",
                        "150",
                        "0",
                        "0",
                        "learner a",
                        "pe-1"});
            table1359.AddRow(new string[] {
                        "Nov/Current Academic Year",
                        "666.66667",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "120",
                        "150",
                        "300",
                        "0",
                        "learner a",
                        "pe-1"});
            table1359.AddRow(new string[] {
                        "Dec/Current Academic Year",
                        "666.66667",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "120",
                        "150",
                        "0",
                        "0",
                        "learner a",
                        "pe-1"});
            table1359.AddRow(new string[] {
                        "Jan/Current Academic Year",
                        "666.66667",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "120",
                        "150",
                        "0",
                        "0",
                        "learner a",
                        "pe-1"});
            table1359.AddRow(new string[] {
                        "Feb/Current Academic Year",
                        "666.66667",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "120",
                        "150",
                        "0",
                        "0",
                        "learner a",
                        "pe-1"});
            table1359.AddRow(new string[] {
                        "Mar/Current Academic Year",
                        "666.66667",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "120",
                        "150",
                        "0",
                        "0",
                        "learner a",
                        "pe-1"});
            table1359.AddRow(new string[] {
                        "Apr/Current Academic Year",
                        "666.66667",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "120",
                        "150",
                        "0",
                        "0",
                        "learner a",
                        "pe-1"});
            table1359.AddRow(new string[] {
                        "May/Current Academic Year",
                        "666.66667",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "120",
                        "150",
                        "0",
                        "0",
                        "learner a",
                        "pe-1"});
            table1359.AddRow(new string[] {
                        "Jun/Current Academic Year",
                        "666.66667",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "120",
                        "150",
                        "0",
                        "0",
                        "learner a",
                        "pe-1"});
            table1359.AddRow(new string[] {
                        "Jul/Current Academic Year",
                        "666.66667",
                        "0",
                        "0",
                        "0",
                        "0",
                        "500",
                        "500",
                        "120",
                        "150",
                        "0",
                        "300",
                        "learner a",
                        "pe-1"});
#line 19
 testRunner.Then("the following learner earnings should be generated for \"provider a\"", ((string)(null)), table1359, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table1360 = new TechTalk.SpecFlow.Table(new string[] {
                        "Apprenticeship",
                        "Learner ID",
                        "Delivery Period",
                        "Framework Code",
                        "Programme Type",
                        "Pathway Code",
                        "Transaction Type",
                        "Error Code",
                        "Price Episode Identifier"});
            table1360.AddRow(new string[] {
                        "",
                        "learner a",
                        "Aug/Current Academic Year",
                        "593",
                        "20",
                        "1",
                        "Learning",
                        "DLOCK_01",
                        "pe-1"});
            table1360.AddRow(new string[] {
                        "",
                        "learner a",
                        "Sep/Current Academic Year",
                        "593",
                        "20",
                        "1",
                        "Learning",
                        "DLOCK_01",
                        "pe-1"});
            table1360.AddRow(new string[] {
                        "",
                        "learner a",
                        "Oct/Current Academic Year",
                        "593",
                        "20",
                        "1",
                        "Learning",
                        "DLOCK_01",
                        "pe-1"});
            table1360.AddRow(new string[] {
                        "",
                        "learner a",
                        "Nov/Current Academic Year",
                        "593",
                        "20",
                        "1",
                        "Learning",
                        "DLOCK_01",
                        "pe-1"});
            table1360.AddRow(new string[] {
                        "",
                        "learner a",
                        "Dec/Current Academic Year",
                        "593",
                        "20",
                        "1",
                        "Learning",
                        "DLOCK_01",
                        "pe-1"});
            table1360.AddRow(new string[] {
                        "",
                        "learner a",
                        "Jan/Current Academic Year",
                        "593",
                        "20",
                        "1",
                        "Learning",
                        "DLOCK_01",
                        "pe-1"});
            table1360.AddRow(new string[] {
                        "",
                        "learner a",
                        "Feb/Current Academic Year",
                        "593",
                        "20",
                        "1",
                        "Learning",
                        "DLOCK_01",
                        "pe-1"});
            table1360.AddRow(new string[] {
                        "",
                        "learner a",
                        "Mar/Current Academic Year",
                        "593",
                        "20",
                        "1",
                        "Learning",
                        "DLOCK_01",
                        "pe-1"});
            table1360.AddRow(new string[] {
                        "",
                        "learner a",
                        "Apr/Current Academic Year",
                        "593",
                        "20",
                        "1",
                        "Learning",
                        "DLOCK_01",
                        "pe-1"});
            table1360.AddRow(new string[] {
                        "",
                        "learner a",
                        "May/Current Academic Year",
                        "593",
                        "20",
                        "1",
                        "Learning",
                        "DLOCK_01",
                        "pe-1"});
            table1360.AddRow(new string[] {
                        "",
                        "learner a",
                        "Jun/Current Academic Year",
                        "593",
                        "20",
                        "1",
                        "Learning",
                        "DLOCK_01",
                        "pe-1"});
            table1360.AddRow(new string[] {
                        "",
                        "learner a",
                        "Jul/Current Academic Year",
                        "593",
                        "20",
                        "1",
                        "Learning",
                        "DLOCK_01",
                        "pe-1"});
#line 33
    testRunner.And("the following data lock failures were generated  for \"provider a\"", ((string)(null)), table1360, "And ");
#line 47
 testRunner.And("Month end is triggered", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 48
 testRunner.And("no provider payments will be recorded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 49
 testRunner.And("no provider payments will be generated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
