// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SFA.DAS.Payments.AcceptanceTests.EndToEnd.Tests.EmployerStops
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Employer Stops PV2-946")]
    public partial class EmployerStopsPV2_946Feature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "E2E -PV2-946 - Levy learner, Employer stops commitment after the day the course is completes, completion and balancing payment is paid .feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Employer Stops PV2-946", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Levy learner, Employer stops commitment after the day that the course is complete" +
            "d, but in the same month, with a Balancing payment. Completion and Balancing is " +
            "paid")]
        [NUnit.Framework.TestCaseAttribute("R02/Current Academic Year", "5000", null)]
        public virtual void LevyLearnerEmployerStopsCommitmentAfterTheDayThatTheCourseIsCompletedButInTheSameMonthWithABalancingPayment_CompletionAndBalancingIsPaid(string collection_Period, string levyBalance, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Levy learner, Employer stops commitment after the day that the course is complete" +
                    "d, but in the same month, with a Balancing payment. Completion and Balancing is " +
                    "paid", null, exampleTags);
#line 42
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 43
 testRunner.Given(string.Format("the employer levy account balance in collection period {0} is {1}", collection_Period, levyBalance), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table544 = new TechTalk.SpecFlow.Table(new string[] {
                        "framework code",
                        "programme type",
                        "pathway code",
                        "agreed price",
                        "start date",
                        "end date",
                        "status",
                        "effective from",
                        "stop effective from"});
            table544.AddRow(new string[] {
                        "593",
                        "20",
                        "1",
                        "17500",
                        "01/Aug/Last Academic Year",
                        "01/Oct/Current Academic Year",
                        "stopped",
                        "01/Aug/Last Academic Year",
                        "15/Sep/Current Academic Year"});
#line 44
 testRunner.And("the following apprenticeships exist", ((string)(null)), table544, "And ");
#line hidden
            TechTalk.SpecFlow.Table table545 = new TechTalk.SpecFlow.Table(new string[] {
                        "Start Date",
                        "Planned Duration",
                        "Total Training Price",
                        "Total Training Price Effective Date",
                        "Total Assessment Price",
                        "Total Assessment Price Effective Date",
                        "Actual Duration",
                        "Completion Status",
                        "Contract Type",
                        "Aim Sequence Number",
                        "Aim Reference",
                        "Framework Code",
                        "Pathway Code",
                        "Programme Type",
                        "Funding Line Type",
                        "SFA Contribution Percentage"});
            table545.AddRow(new string[] {
                        "01/Aug/Last Academic Year",
                        "14 months",
                        "17500",
                        "01/Aug/Last Academic Year",
                        "",
                        "",
                        "",
                        "continuing",
                        "Act1",
                        "1",
                        "ZPROG001",
                        "593",
                        "1",
                        "20",
                        "19+ Apprenticeship (From May 2017) Levy Contract",
                        "90%"});
#line 47
 testRunner.And("the provider previously submitted the following learner details", ((string)(null)), table545, "And ");
#line hidden
            TechTalk.SpecFlow.Table table546 = new TechTalk.SpecFlow.Table(new string[] {
                        "Delivery Period",
                        "On-Programme",
                        "Completion",
                        "Balancing"});
            table546.AddRow(new string[] {
                        "Aug/Last Academic Year",
                        "1000",
                        "0",
                        "0"});
            table546.AddRow(new string[] {
                        "Sep/Last Academic Year",
                        "1000",
                        "0",
                        "0"});
            table546.AddRow(new string[] {
                        "Oct/Last Academic Year",
                        "1000",
                        "0",
                        "0"});
            table546.AddRow(new string[] {
                        "Nov/Last Academic Year",
                        "1000",
                        "0",
                        "0"});
            table546.AddRow(new string[] {
                        "Dec/Last Academic Year",
                        "1000",
                        "0",
                        "0"});
            table546.AddRow(new string[] {
                        "Jan/Last Academic Year",
                        "1000",
                        "0",
                        "0"});
            table546.AddRow(new string[] {
                        "Feb/Last Academic Year",
                        "1000",
                        "0",
                        "0"});
            table546.AddRow(new string[] {
                        "Mar/Last Academic Year",
                        "1000",
                        "0",
                        "0"});
            table546.AddRow(new string[] {
                        "Apr/Last Academic Year",
                        "1000",
                        "0",
                        "0"});
            table546.AddRow(new string[] {
                        "May/Last Academic Year",
                        "1000",
                        "0",
                        "0"});
            table546.AddRow(new string[] {
                        "Jun/Last Academic Year",
                        "1000",
                        "0",
                        "0"});
            table546.AddRow(new string[] {
                        "Jul/Last Academic Year",
                        "1000",
                        "0",
                        "0"});
            table546.AddRow(new string[] {
                        "Aug/Current Academic Year",
                        "1000",
                        "0",
                        "0"});
            table546.AddRow(new string[] {
                        "Sep/Current Academic Year",
                        "1000",
                        "3500",
                        "0"});
#line 50
    testRunner.And("the following earnings had been generated for the learner", ((string)(null)), table546, "And ");
#line hidden
            TechTalk.SpecFlow.Table table547 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection Period",
                        "Delivery Period",
                        "Levy Payments",
                        "Transaction Type"});
            table547.AddRow(new string[] {
                        "R02/Last Academic Year",
                        "Sep/Last Academic Year",
                        "1000",
                        "Learning"});
            table547.AddRow(new string[] {
                        "R03/Last Academic Year",
                        "Oct/Last Academic Year",
                        "1000",
                        "Learning"});
            table547.AddRow(new string[] {
                        "R04/Last Academic Year",
                        "Nov/Last Academic Year",
                        "1000",
                        "Learning"});
            table547.AddRow(new string[] {
                        "R05/Last Academic Year",
                        "Dec/Last Academic Year",
                        "1000",
                        "Learning"});
            table547.AddRow(new string[] {
                        "R06/Last Academic Year",
                        "Jan/Last Academic Year",
                        "1000",
                        "Learning"});
            table547.AddRow(new string[] {
                        "R07/Last Academic Year",
                        "Feb/Last Academic Year",
                        "1000",
                        "Learning"});
            table547.AddRow(new string[] {
                        "R08/Last Academic Year",
                        "Mar/Last Academic Year",
                        "1000",
                        "Learning"});
            table547.AddRow(new string[] {
                        "R09/Last Academic Year",
                        "Apr/Last Academic Year",
                        "1000",
                        "Learning"});
            table547.AddRow(new string[] {
                        "R10/Last Academic Year",
                        "May/Last Academic Year",
                        "1000",
                        "Learning"});
            table547.AddRow(new string[] {
                        "R11/Last Academic Year",
                        "Jun/Last Academic Year",
                        "1000",
                        "Learning"});
            table547.AddRow(new string[] {
                        "R12/Last Academic Year",
                        "Jul/Last Academic Year",
                        "1000",
                        "Learning"});
            table547.AddRow(new string[] {
                        "R01/Current Academic Year",
                        "Aug/Current Academic Year",
                        "1000",
                        "Learning"});
#line 66
    testRunner.And("the following provider payments had been generated", ((string)(null)), table547, "And ");
#line hidden
            TechTalk.SpecFlow.Table table548 = new TechTalk.SpecFlow.Table(new string[] {
                        "Start Date",
                        "Planned Duration",
                        "Total Training Price",
                        "Total Training Price Effective Date",
                        "Total Assessment Price",
                        "Total Assessment Price Effective Date",
                        "Actual Duration",
                        "Completion Status",
                        "Contract Type",
                        "Aim Sequence Number",
                        "Aim Reference",
                        "Framework Code",
                        "Pathway Code",
                        "Programme Type",
                        "Funding Line Type",
                        "SFA Contribution Percentage"});
            table548.AddRow(new string[] {
                        "01/Aug/Last Academic Year",
                        "14 months",
                        "17500",
                        "01/Aug/Last Academic Year",
                        "",
                        "",
                        "13 months",
                        "completed",
                        "Act1",
                        "1",
                        "ZPROG001",
                        "593",
                        "1",
                        "20",
                        "19+ Apprenticeship (From May 2017) Levy Contract",
                        "90%"});
#line 80
 testRunner.But("the Provider now changes the Learner details as follows", ((string)(null)), table548, "But ");
#line hidden
            TechTalk.SpecFlow.Table table549 = new TechTalk.SpecFlow.Table(new string[] {
                        "Price Episode Id",
                        "Total Training Price",
                        "Total Training Price Effective Date",
                        "Total Assessment Price",
                        "Total Assessment Price Effective Date",
                        "Contract Type",
                        "Aim Sequence Number",
                        "SFA Contribution Percentage"});
            table549.AddRow(new string[] {
                        "pe-1",
                        "17500",
                        "01/Aug/Current Academic Year",
                        "",
                        "01/Sep/Current Academic Year",
                        "Act1",
                        "1",
                        "90%"});
#line 84
 testRunner.And("price details are changed as follows", ((string)(null)), table549, "And ");
#line 88
 testRunner.When(string.Format("the amended ILR file is re-submitted for the learners in collection period {0}", collection_Period), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table550 = new TechTalk.SpecFlow.Table(new string[] {
                        "Delivery Period",
                        "On-Programme",
                        "Completion",
                        "Balancing",
                        "Price Episode Identifier"});
            table550.AddRow(new string[] {
                        "Aug/Current Academic Year",
                        "1000",
                        "0",
                        "0",
                        "pe-1"});
            table550.AddRow(new string[] {
                        "Sep/Current Academic Year",
                        "0",
                        "3500",
                        "1000",
                        "pe-1"});
            table550.AddRow(new string[] {
                        "Oct/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-1"});
            table550.AddRow(new string[] {
                        "Nov/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-1"});
            table550.AddRow(new string[] {
                        "Dec/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-1"});
            table550.AddRow(new string[] {
                        "Jan/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-1"});
            table550.AddRow(new string[] {
                        "Feb/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-1"});
            table550.AddRow(new string[] {
                        "Mar/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-1"});
            table550.AddRow(new string[] {
                        "Apr/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-1"});
            table550.AddRow(new string[] {
                        "May/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-1"});
            table550.AddRow(new string[] {
                        "Jun/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-1"});
            table550.AddRow(new string[] {
                        "Jul/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-1"});
#line 89
 testRunner.Then("the following learner earnings should be generated", ((string)(null)), table550, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table551 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection Period",
                        "Delivery Period",
                        "On-Programme",
                        "Completion",
                        "Balancing"});
            table551.AddRow(new string[] {
                        "R02/Current Academic Year",
                        "Sep/Current Academic Year",
                        "0",
                        "0",
                        "1000"});
            table551.AddRow(new string[] {
                        "R02/Current Academic Year",
                        "Sep/Current Academic Year",
                        "0",
                        "3500",
                        "0"});
#line 103
    testRunner.And("at month end only the following payments will be calculated", ((string)(null)), table551, "And ");
#line hidden
            TechTalk.SpecFlow.Table table552 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection Period",
                        "Delivery Period",
                        "Levy Payments",
                        "Transaction Type"});
            table552.AddRow(new string[] {
                        "R02/Current Academic Year",
                        "Sep/Current Academic Year",
                        "1000",
                        "Balancing"});
            table552.AddRow(new string[] {
                        "R02/Current Academic Year",
                        "Sep/Current Academic Year",
                        "3500",
                        "Completion"});
#line 107
 testRunner.And("only the following provider payments will be recorded", ((string)(null)), table552, "And ");
#line hidden
            TechTalk.SpecFlow.Table table553 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection Period",
                        "Delivery Period",
                        "Levy Payments",
                        "Transaction Type"});
            table553.AddRow(new string[] {
                        "R02/Current Academic Year",
                        "Sep/Current Academic Year",
                        "1000",
                        "Balancing"});
            table553.AddRow(new string[] {
                        "R02/Current Academic Year",
                        "Sep/Current Academic Year",
                        "3500",
                        "Completion"});
#line 111
 testRunner.And("only the following provider payments will be generated", ((string)(null)), table553, "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
