// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SFA.DAS.Payments.AcceptanceTests.EndToEnd.Tests.Refunds
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Levy learner, price is changed and a negative amount is left to be paid resulting" +
        " in a refund PV2-257")]
    [NUnit.Framework.CategoryAttribute("basic_refund")]
    public partial class LevyLearnerPriceIsChangedAndANegativeAmountIsLeftToBePaidResultingInARefundPV2_257Feature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Levy-learner price change with negative earning - PV2-257.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Levy learner, price is changed and a negative amount is left to be paid resulting" +
                    " in a refund PV2-257", @"	Levy standard learner, where original commitment is withdrawn after payments made and new commitment is created with lower price and a negative amount is left to be paid - results in a refund
	As a provider,
	I want a levy learner, where original commitment is withdrawn after payments made and new commitment is created with lower price and a negative amount is left to be paid - results in a refund
	So that I am accurately paid my apprenticeship provision PV2-257", ProgrammingLanguage.CSharp, new string[] {
                        "basic_refund"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Levy learner, price is changed and a negative amount is left to be paid resulting" +
            " in a refund PV2-257")]
        public virtual void LevyLearnerPriceIsChangedAndANegativeAmountIsLeftToBePaidResultingInARefundPV2_257()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Levy learner, price is changed and a negative amount is left to be paid resulting" +
                    " in a refund PV2-257", null, ((string[])(null)));
#line 8
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 10
testRunner.Given("the employer levy account balance in collection period R03/Current Academic Year " +
                    "is 15000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2124 = new TechTalk.SpecFlow.Table(new string[] {
                        "start date",
                        "end date",
                        "agreed price",
                        "status",
                        "effective from",
                        "Standard Code",
                        "Programme Type"});
            table2124.AddRow(new string[] {
                        "01/Aug/Current Academic Year",
                        "01/Aug/Next Academic Year",
                        "11250",
                        "active",
                        "01/Aug/Current Academic Year",
                        "51",
                        "25"});
#line 12
testRunner.And("the following commitments exist", ((string)(null)), table2124, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2125 = new TechTalk.SpecFlow.Table(new string[] {
                        "Start Date",
                        "Planned Duration",
                        "Total Training Price",
                        "Total Training Price Effective Date",
                        "Total Assesment Price",
                        "Total Assesment Price Effective Date",
                        "Actual Duration",
                        "Completion Status",
                        "SFA Contribution Percentage",
                        "Contract Type",
                        "Aim Sequence Number",
                        "Aim Reference",
                        "Standard Code",
                        "Programme Type",
                        "Funding Line Type"});
            table2125.AddRow(new string[] {
                        "04/Aug/Current Academic Year",
                        "12 months",
                        "9000",
                        "04/Aug/Current Academic Year",
                        "2250",
                        "04/Aug/Current Academic Year",
                        "",
                        "continuing",
                        "90%",
                        "Act1",
                        "1",
                        "ZPROG001",
                        "51",
                        "25",
                        "19-24 Apprenticeship (From May 2017) Levy Contract"});
#line 16
testRunner.And("the provider previously submitted the following learner details", ((string)(null)), table2125, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2126 = new TechTalk.SpecFlow.Table(new string[] {
                        "Delivery Period",
                        "On-Programme",
                        "Completion",
                        "Balancing"});
            table2126.AddRow(new string[] {
                        "Aug/Current Academic Year",
                        "750",
                        "0",
                        "0"});
            table2126.AddRow(new string[] {
                        "Sep/Current Academic Year",
                        "750",
                        "0",
                        "0"});
            table2126.AddRow(new string[] {
                        "Oct/Current Academic Year",
                        "750",
                        "0",
                        "0"});
            table2126.AddRow(new string[] {
                        "Nov/Current Academic Year",
                        "750",
                        "0",
                        "0"});
            table2126.AddRow(new string[] {
                        "Dec/Current Academic Year",
                        "750",
                        "0",
                        "0"});
            table2126.AddRow(new string[] {
                        "Jan/Current Academic Year",
                        "750",
                        "0",
                        "0"});
            table2126.AddRow(new string[] {
                        "Feb/Current Academic Year",
                        "750",
                        "0",
                        "0"});
            table2126.AddRow(new string[] {
                        "Mar/Current Academic Year",
                        "750",
                        "0",
                        "0"});
            table2126.AddRow(new string[] {
                        "Apr/Current Academic Year",
                        "750",
                        "0",
                        "0"});
            table2126.AddRow(new string[] {
                        "May/Current Academic Year",
                        "750",
                        "0",
                        "0"});
            table2126.AddRow(new string[] {
                        "Jun/Current Academic Year",
                        "750",
                        "0",
                        "0"});
            table2126.AddRow(new string[] {
                        "Jul/Current Academic Year",
                        "750",
                        "0",
                        "0"});
#line 20
testRunner.And("the following earnings had been generated for the learner", ((string)(null)), table2126, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2127 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection Period",
                        "Delivery Period",
                        "Levy Payments",
                        "Transaction Type"});
            table2127.AddRow(new string[] {
                        "R01/Current Academic Year",
                        "Aug/Current Academic Year",
                        "750",
                        "Learning"});
            table2127.AddRow(new string[] {
                        "R02/Current Academic Year",
                        "Sep/Current Academic Year",
                        "750",
                        "Learning"});
#line 35
testRunner.And("the following provider payments had been generated", ((string)(null)), table2127, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2128 = new TechTalk.SpecFlow.Table(new string[] {
                        "start date",
                        "end date",
                        "status",
                        "agreed price",
                        "effective from",
                        "stop effective from"});
            table2128.AddRow(new string[] {
                        "01/Aug/Current Academic Year",
                        "01/Aug/Next Academic Year",
                        "stopped",
                        "11250",
                        "01/Aug/Current Academic Year",
                        "01/Aug/Current Academic Year"});
            table2128.AddRow(new string[] {
                        "01/Aug/Current Academic Year",
                        "01/Aug/Next Academic Year",
                        "active",
                        "1",
                        "01/Aug/Current Academic Year",
                        ""});
#line 40
testRunner.But("the Commitment details are changed as follows", ((string)(null)), table2128, "But ");
#line hidden
            TechTalk.SpecFlow.Table table2129 = new TechTalk.SpecFlow.Table(new string[] {
                        "Start Date",
                        "Planned Duration",
                        "Total Training Price",
                        "Total Training Price Effective Date",
                        "Total Assesment Price",
                        "Total Assesment Price Effective Date",
                        "Actual Duration",
                        "Completion Status",
                        "SFA Contribution Percentage",
                        "Contract Type",
                        "Aim Sequence Number",
                        "Aim Reference",
                        "Standard Code",
                        "Programme Type",
                        "Funding Line Type"});
            table2129.AddRow(new string[] {
                        "04/Aug/Current Academic Year",
                        "12 months",
                        "1",
                        "04/Aug/Current Academic Year",
                        "0",
                        "04/Aug/Current Academic Year",
                        "",
                        "continuing",
                        "90%",
                        "Act1",
                        "1",
                        "ZPROG001",
                        "51",
                        "25",
                        "19-24 Apprenticeship (From May 2017) Levy Contract"});
#line 46
testRunner.And("the Provider now changes the Learner details as follows", ((string)(null)), table2129, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2130 = new TechTalk.SpecFlow.Table(new string[] {
                        "Price Episode Id",
                        "Total Training Price",
                        "Total Training Price Effective Date",
                        "Contract Type",
                        "Aim Sequence Number",
                        "SFA Contribution Percentage"});
            table2130.AddRow(new string[] {
                        "pe-1",
                        "1",
                        "04/Aug/Current Academic Year",
                        "Act1",
                        "1",
                        "90%"});
#line 50
testRunner.And("price details as follows", ((string)(null)), table2130, "And ");
#line 53
testRunner.When("the amended ILR file is re-submitted for the learners in collection period R03/Cu" +
                    "rrent Academic Year", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2131 = new TechTalk.SpecFlow.Table(new string[] {
                        "Delivery Period",
                        "On-Programme",
                        "Completion",
                        "Balancing",
                        "Price Episode Identifier"});
            table2131.AddRow(new string[] {
                        "Aug/Current Academic Year",
                        "0.06667",
                        "0",
                        "0",
                        "pe-1"});
            table2131.AddRow(new string[] {
                        "Sep/Current Academic Year",
                        "0.06667",
                        "0",
                        "0",
                        "pe-1"});
            table2131.AddRow(new string[] {
                        "Oct/Current Academic Year",
                        "0.06667",
                        "0",
                        "0",
                        "pe-1"});
            table2131.AddRow(new string[] {
                        "Nov/Current Academic Year",
                        "0.06667",
                        "0",
                        "0",
                        "pe-1"});
            table2131.AddRow(new string[] {
                        "Dec/Current Academic Year",
                        "0.06667",
                        "0",
                        "0",
                        "pe-1"});
            table2131.AddRow(new string[] {
                        "Jan/Current Academic Year",
                        "0.06667",
                        "0",
                        "0",
                        "pe-1"});
            table2131.AddRow(new string[] {
                        "Feb/Current Academic Year",
                        "0.06667",
                        "0",
                        "0",
                        "pe-1"});
            table2131.AddRow(new string[] {
                        "Mar/Current Academic Year",
                        "0.06667",
                        "0",
                        "0",
                        "pe-1"});
            table2131.AddRow(new string[] {
                        "Apr/Current Academic Year",
                        "0.06667",
                        "0",
                        "0",
                        "pe-1"});
            table2131.AddRow(new string[] {
                        "May/Current Academic Year",
                        "0.06667",
                        "0",
                        "0",
                        "pe-1"});
            table2131.AddRow(new string[] {
                        "Jun/Current Academic Year",
                        "0.06667",
                        "0",
                        "0",
                        "pe-1"});
            table2131.AddRow(new string[] {
                        "Jul/Current Academic Year",
                        "0.06667",
                        "0",
                        "0",
                        "pe-1"});
#line 55
testRunner.Then("the following learner earnings should be generated", ((string)(null)), table2131, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table2132 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection Period",
                        "Delivery Period",
                        "On-Programme",
                        "Completion",
                        "Balancing"});
            table2132.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Aug/Current Academic Year",
                        "-749.93333",
                        "0",
                        "0"});
            table2132.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Sep/Current Academic Year",
                        "-749.93333",
                        "0",
                        "0"});
            table2132.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Oct/Current Academic Year",
                        "0.06667",
                        "0",
                        "0"});
#line 70
testRunner.And("at month end only the following payments will be calculated", ((string)(null)), table2132, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2133 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection Period",
                        "Delivery Period",
                        "Levy Payments",
                        "Transaction Type"});
            table2133.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Aug/Current Academic Year",
                        "-749.93333",
                        "Learning"});
            table2133.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Sep/Current Academic Year",
                        "-749.93333",
                        "Learning"});
            table2133.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Oct/Current Academic Year",
                        "0.06667",
                        "Learning"});
#line 76
testRunner.And("only the following provider payments will be recorded", ((string)(null)), table2133, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2134 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection Period",
                        "Delivery Period",
                        "Levy Payments",
                        "Transaction Type"});
            table2134.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Aug/Current Academic Year",
                        "-749.93333",
                        "Learning"});
            table2134.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Sep/Current Academic Year",
                        "-749.93333",
                        "Learning"});
            table2134.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Oct/Current Academic Year",
                        "0.06667",
                        "Learning"});
#line 82
testRunner.And("only the following provider payments will be generated", ((string)(null)), table2134, "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
