// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SFA.DAS.Payments.AcceptanceTests.EndToEnd.Tests.DisadvantagedUplift
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("PV2-447 Payment for a DAS learner, lives in a disadvantaged postocde area - 1-10%" +
        " most deprived, undertaking apprenticeship standard - Disadvantage Uplift is not" +
        " paid")]
    public partial class PV2_447PaymentForADASLearnerLivesInADisadvantagedPostocdeArea_1_10MostDeprivedUndertakingApprenticeshipStandard_DisadvantageUpliftIsNotPaidFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "PV2-447 - Levy learner, lives in a disadvantaged postocde area - 1-10 most deprived,undertaking standard.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "PV2-447 Payment for a DAS learner, lives in a disadvantaged postocde area - 1-10%" +
                    " most deprived, undertaking apprenticeship standard - Disadvantage Uplift is not" +
                    " paid", "\t\tAs a provider,\r\n\t\tI want a levy learner living in a Disadvantaged Postcode area" +
                    " (1-10% most deprived) to undertake an Apprenticeship Standard course\r\n\t\tSo that" +
                    " I am not paid the Disadvantage Uplift payment.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Levy learner, on standard, Disadvantage Uplift 1-10% not paid PV2-447")]
        [NUnit.Framework.TestCaseAttribute("R01/Current Academic Year", "15500", null)]
        [NUnit.Framework.TestCaseAttribute("R02/Current Academic Year", "14500", null)]
        [NUnit.Framework.TestCaseAttribute("R03/Current Academic Year", "13500", null)]
        [NUnit.Framework.TestCaseAttribute("R04/Current Academic Year", "12500", null)]
        [NUnit.Framework.TestCaseAttribute("R05/Current Academic Year", "11500", null)]
        [NUnit.Framework.TestCaseAttribute("R06/Current Academic Year", "10500", null)]
        [NUnit.Framework.TestCaseAttribute("R07/Current Academic Year", "9500", null)]
        [NUnit.Framework.TestCaseAttribute("R08/Current Academic Year", "8500", null)]
        [NUnit.Framework.TestCaseAttribute("R09/Current Academic Year", "7500", null)]
        [NUnit.Framework.TestCaseAttribute("R10/Current Academic Year", "6500", null)]
        [NUnit.Framework.TestCaseAttribute("R11/Current Academic Year", "5500", null)]
        [NUnit.Framework.TestCaseAttribute("R12/Current Academic Year", "4500", null)]
        public virtual void LevyLearnerOnStandardDisadvantageUplift1_10NotPaidPV2_447(string collection_Period, string levyBalance, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Levy learner, on standard, Disadvantage Uplift 1-10% not paid PV2-447", null, exampleTags);
#line 5
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
 testRunner.Given(string.Format("the employer levy account balance in collection period {0} is {1}", collection_Period, levyBalance), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table260 = new TechTalk.SpecFlow.Table(new string[] {
                        "start date",
                        "end date",
                        "agreed price",
                        "standard code",
                        "status",
                        "Standard Code",
                        "Programme Type"});
            table260.AddRow(new string[] {
                        "01/Aug/Current Academic Year",
                        "01/Aug/Next Academic Year",
                        "15000",
                        "50",
                        "active",
                        "50",
                        "25"});
#line 7
 testRunner.And("the following commitments exist", ((string)(null)), table260, "And ");
#line hidden
            TechTalk.SpecFlow.Table table261 = new TechTalk.SpecFlow.Table(new string[] {
                        "Start Date",
                        "Planned Duration",
                        "Total Training Price",
                        "Total Training Price Effective Date",
                        "Total Assessment Price",
                        "Total Assessment Price Effective Date",
                        "Actual Duration",
                        "Completion Status",
                        "Contract Type",
                        "Aim Sequence Number",
                        "Aim Reference",
                        "Standard Code",
                        "Programme Type",
                        "Funding Line Type",
                        "SFA Contribution Percentage"});
            table261.AddRow(new string[] {
                        "06/Aug/Current Academic Year",
                        "12 months",
                        "14000",
                        "06/Aug/Current Academic Year",
                        "1000",
                        "06/Aug/Current Academic Year",
                        "",
                        "continuing",
                        "Act1",
                        "1",
                        "ZPROG001",
                        "50",
                        "25",
                        "16-18 Apprenticeship (From May 2017) Levy Contract",
                        "90%"});
#line 10
    testRunner.And("the provider is providing training for the following learners", ((string)(null)), table261, "And ");
#line hidden
            TechTalk.SpecFlow.Table table262 = new TechTalk.SpecFlow.Table(new string[] {
                        "Price Episode Id",
                        "Total Training Price",
                        "Total Training Price Effective Date",
                        "Total Assessment Price",
                        "Total Assessment Price Effective Date",
                        "Residual Training Price",
                        "Residual Training Price Effective Date",
                        "Residual Assessment Price",
                        "Residual Assessment Price Effective Date",
                        "SFA Contribution Percentage",
                        "Contract Type"});
            table262.AddRow(new string[] {
                        "pe-1",
                        "14000",
                        "06/Aug/Current Academic Year",
                        "1000",
                        "06/Aug/Current Academic Year",
                        "0",
                        "",
                        "0",
                        "",
                        "90%",
                        "Act1"});
#line 13
 testRunner.And("price details as follows", ((string)(null)), table262, "And ");
#line 16
 testRunner.When(string.Format("the ILR file is submitted for the learners for collection period {0}", collection_Period), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table263 = new TechTalk.SpecFlow.Table(new string[] {
                        "Delivery Period",
                        "On-Programme",
                        "Completion",
                        "Balancing",
                        "Price Episode Identifier"});
            table263.AddRow(new string[] {
                        "Aug/Current Academic Year",
                        "1000",
                        "0",
                        "0",
                        "pe-1"});
            table263.AddRow(new string[] {
                        "Sep/Current Academic Year",
                        "1000",
                        "0",
                        "0",
                        "pe-1"});
            table263.AddRow(new string[] {
                        "Oct/Current Academic Year",
                        "1000",
                        "0",
                        "0",
                        "pe-1"});
            table263.AddRow(new string[] {
                        "Nov/Current Academic Year",
                        "1000",
                        "0",
                        "0",
                        "pe-1"});
            table263.AddRow(new string[] {
                        "Dec/Current Academic Year",
                        "1000",
                        "0",
                        "0",
                        "pe-1"});
            table263.AddRow(new string[] {
                        "Jan/Current Academic Year",
                        "1000",
                        "0",
                        "0",
                        "pe-1"});
            table263.AddRow(new string[] {
                        "Feb/Current Academic Year",
                        "1000",
                        "0",
                        "0",
                        "pe-1"});
            table263.AddRow(new string[] {
                        "Mar/Current Academic Year",
                        "1000",
                        "0",
                        "0",
                        "pe-1"});
            table263.AddRow(new string[] {
                        "Apr/Current Academic Year",
                        "1000",
                        "0",
                        "0",
                        "pe-1"});
            table263.AddRow(new string[] {
                        "May/Current Academic Year",
                        "1000",
                        "0",
                        "0",
                        "pe-1"});
            table263.AddRow(new string[] {
                        "Jun/Current Academic Year",
                        "1000",
                        "0",
                        "0",
                        "pe-1"});
            table263.AddRow(new string[] {
                        "Jul/Current Academic Year",
                        "1000",
                        "0",
                        "0",
                        "pe-1"});
#line 17
 testRunner.Then("the following learner earnings should be generated", ((string)(null)), table263, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table264 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection Period",
                        "Delivery Period",
                        "On-Programme",
                        "Completion",
                        "Balancing"});
            table264.AddRow(new string[] {
                        "R01/Current Academic Year",
                        "Aug/Current Academic Year",
                        "1000",
                        "0",
                        "0"});
            table264.AddRow(new string[] {
                        "R02/Current Academic Year",
                        "Sep/Current Academic Year",
                        "1000",
                        "0",
                        "0"});
            table264.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Oct/Current Academic Year",
                        "1000",
                        "0",
                        "0"});
            table264.AddRow(new string[] {
                        "R04/Current Academic Year",
                        "Nov/Current Academic Year",
                        "1000",
                        "0",
                        "0"});
            table264.AddRow(new string[] {
                        "R05/Current Academic Year",
                        "Dec/Current Academic Year",
                        "1000",
                        "0",
                        "0"});
            table264.AddRow(new string[] {
                        "R06/Current Academic Year",
                        "Jan/Current Academic Year",
                        "1000",
                        "0",
                        "0"});
            table264.AddRow(new string[] {
                        "R07/Current Academic Year",
                        "Feb/Current Academic Year",
                        "1000",
                        "0",
                        "0"});
            table264.AddRow(new string[] {
                        "R08/Current Academic Year",
                        "Mar/Current Academic Year",
                        "1000",
                        "0",
                        "0"});
            table264.AddRow(new string[] {
                        "R09/Current Academic Year",
                        "Apr/Current Academic Year",
                        "1000",
                        "0",
                        "0"});
            table264.AddRow(new string[] {
                        "R10/Current Academic Year",
                        "May/Current Academic Year",
                        "1000",
                        "0",
                        "0"});
            table264.AddRow(new string[] {
                        "R11/Current Academic Year",
                        "Jun/Current Academic Year",
                        "1000",
                        "0",
                        "0"});
            table264.AddRow(new string[] {
                        "R12/Current Academic Year",
                        "Jul/Current Academic Year",
                        "1000",
                        "0",
                        "0"});
#line 31
    testRunner.And("at month end only the following payments will be calculated", ((string)(null)), table264, "And ");
#line hidden
            TechTalk.SpecFlow.Table table265 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection Period",
                        "Delivery Period",
                        "Levy Payments",
                        "Transaction Type"});
            table265.AddRow(new string[] {
                        "R01/Current Academic Year",
                        "Aug/Current Academic Year",
                        "1000",
                        "Learning"});
            table265.AddRow(new string[] {
                        "R02/Current Academic Year",
                        "Sep/Current Academic Year",
                        "1000",
                        "Learning"});
            table265.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Oct/Current Academic Year",
                        "1000",
                        "Learning"});
            table265.AddRow(new string[] {
                        "R04/Current Academic Year",
                        "Nov/Current Academic Year",
                        "1000",
                        "Learning"});
            table265.AddRow(new string[] {
                        "R05/Current Academic Year",
                        "Dec/Current Academic Year",
                        "1000",
                        "Learning"});
            table265.AddRow(new string[] {
                        "R06/Current Academic Year",
                        "Jan/Current Academic Year",
                        "1000",
                        "Learning"});
            table265.AddRow(new string[] {
                        "R07/Current Academic Year",
                        "Feb/Current Academic Year",
                        "1000",
                        "Learning"});
            table265.AddRow(new string[] {
                        "R08/Current Academic Year",
                        "Mar/Current Academic Year",
                        "1000",
                        "Learning"});
            table265.AddRow(new string[] {
                        "R09/Current Academic Year",
                        "Apr/Current Academic Year",
                        "1000",
                        "Learning"});
            table265.AddRow(new string[] {
                        "R10/Current Academic Year",
                        "May/Current Academic Year",
                        "1000",
                        "Learning"});
            table265.AddRow(new string[] {
                        "R11/Current Academic Year",
                        "Jun/Current Academic Year",
                        "1000",
                        "Learning"});
            table265.AddRow(new string[] {
                        "R12/Current Academic Year",
                        "Jul/Current Academic Year",
                        "1000",
                        "Learning"});
#line 45
 testRunner.And("only the following provider payments will be recorded", ((string)(null)), table265, "And ");
#line hidden
            TechTalk.SpecFlow.Table table266 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection Period",
                        "Delivery Period",
                        "Levy Payments",
                        "Transaction Type"});
            table266.AddRow(new string[] {
                        "R01/Current Academic Year",
                        "Aug/Current Academic Year",
                        "1000",
                        "Learning"});
            table266.AddRow(new string[] {
                        "R02/Current Academic Year",
                        "Sep/Current Academic Year",
                        "1000",
                        "Learning"});
            table266.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Oct/Current Academic Year",
                        "1000",
                        "Learning"});
            table266.AddRow(new string[] {
                        "R04/Current Academic Year",
                        "Nov/Current Academic Year",
                        "1000",
                        "Learning"});
            table266.AddRow(new string[] {
                        "R05/Current Academic Year",
                        "Dec/Current Academic Year",
                        "1000",
                        "Learning"});
            table266.AddRow(new string[] {
                        "R06/Current Academic Year",
                        "Jan/Current Academic Year",
                        "1000",
                        "Learning"});
            table266.AddRow(new string[] {
                        "R07/Current Academic Year",
                        "Feb/Current Academic Year",
                        "1000",
                        "Learning"});
            table266.AddRow(new string[] {
                        "R08/Current Academic Year",
                        "Mar/Current Academic Year",
                        "1000",
                        "Learning"});
            table266.AddRow(new string[] {
                        "R09/Current Academic Year",
                        "Apr/Current Academic Year",
                        "1000",
                        "Learning"});
            table266.AddRow(new string[] {
                        "R10/Current Academic Year",
                        "May/Current Academic Year",
                        "1000",
                        "Learning"});
            table266.AddRow(new string[] {
                        "R11/Current Academic Year",
                        "Jun/Current Academic Year",
                        "1000",
                        "Learning"});
            table266.AddRow(new string[] {
                        "R12/Current Academic Year",
                        "Jul/Current Academic Year",
                        "1000",
                        "Learning"});
#line 59
 testRunner.And("only the following provider payments will be generated", ((string)(null)), table266, "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
