// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SFA.DAS.Payments.AcceptanceTests.EndToEnd.Tests.LevyLearner.BasicDay
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Two levy learners, one employer but two providers and enough levy available both " +
        "finished on time PV2-269")]
    [NUnit.Framework.CategoryAttribute("basic_day")]
    public partial class TwoLevyLearnersOneEmployerButTwoProvidersAndEnoughLevyAvailableBothFinishedOnTimePV2_269Feature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Two levy learners one employer but two providers and enough levy PV2-269.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Two levy learners, one employer but two providers and enough levy available both " +
                    "finished on time PV2-269", "\tAs a provider,\r\n\tI want 2 learners, 1 employer, 2 providers who have enough levy" +
                    " - to be paid the correct amount\r\n\tSo that I am accurately paid my apprenticeshi" +
                    "p provision.", ProgrammingLanguage.CSharp, new string[] {
                        "basic_day"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Two levy learners, one employer but two providers and enough levy available both " +
            "finished on time PV2-269")]
        [NUnit.Framework.TestCaseAttribute("R01/Current Academic Year", "6500", null)]
        [NUnit.Framework.TestCaseAttribute("R02/Current Academic Year", "5000", null)]
        [NUnit.Framework.TestCaseAttribute("R03/Current Academic Year", "500", null)]
        public virtual void TwoLevyLearnersOneEmployerButTwoProvidersAndEnoughLevyAvailableBothFinishedOnTimePV2_269(string collection_Period, string levyBalance, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Two levy learners, one employer but two providers and enough levy available both " +
                    "finished on time PV2-269", null, exampleTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 7
 testRunner.Given(string.Format("the employer levy account balance in collection period {0} is {1}", collection_Period, levyBalance), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1633 = new TechTalk.SpecFlow.Table(new string[] {
                        "Learner ID",
                        "Start Date",
                        "Planned Duration",
                        "Total Training Price",
                        "Total Training Price Effective Date",
                        "Total Assessment Price",
                        "Total Assessment Price Effective Date",
                        "Actual Duration",
                        "Completion Status",
                        "Contract Type",
                        "Aim Sequence Number",
                        "Aim Reference",
                        "Framework Code",
                        "Pathway Code",
                        "Programme Type",
                        "Funding Line Type",
                        "SFA Contribution Percentage"});
            table1633.AddRow(new string[] {
                        "learner a",
                        "01/Sep/Last Academic Year",
                        "12 months",
                        "7500",
                        "01/Sep/Last Academic Year",
                        "",
                        "",
                        "",
                        "continuing",
                        "Act1",
                        "1",
                        "ZPROG001",
                        "593",
                        "1",
                        "20",
                        "19+ Apprenticeship (From May 2017) Levy Contract",
                        "90%"});
#line 8
 testRunner.And("the \"provider a\" previously submitted the following learner details", ((string)(null)), table1633, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1634 = new TechTalk.SpecFlow.Table(new string[] {
                        "Learner ID",
                        "Start Date",
                        "Planned Duration",
                        "Total Training Price",
                        "Total Training Price Effective Date",
                        "Total Assessment Price",
                        "Total Assessment Price Effective Date",
                        "Actual Duration",
                        "Completion Status",
                        "Contract Type",
                        "Aim Sequence Number",
                        "Aim Reference",
                        "Framework Code",
                        "Pathway Code",
                        "Programme Type",
                        "Funding Line Type",
                        "SFA Contribution Percentage"});
            table1634.AddRow(new string[] {
                        "learner b",
                        "01/Sep/Last Academic Year",
                        "12 months",
                        "15000",
                        "01/Sep/Last Academic Year",
                        "",
                        "",
                        "",
                        "continuing",
                        "Act1",
                        "1",
                        "ZPROG001",
                        "593",
                        "1",
                        "20",
                        "19+ Apprenticeship (From May 2017) Levy Contract",
                        "90%"});
#line 11
 testRunner.And("the \"provider b\" previously submitted the following learner details", ((string)(null)), table1634, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1635 = new TechTalk.SpecFlow.Table(new string[] {
                        "Identifier",
                        "Provider",
                        "Learner ID",
                        "priority",
                        "start date",
                        "end date",
                        "agreed price",
                        "Framework Code",
                        "Pathway Code",
                        "Programme Type"});
            table1635.AddRow(new string[] {
                        "Apprenticeship 1",
                        "provider a",
                        "learner a",
                        "1",
                        "01/Sep/Last Academic Year",
                        "08/Sep/Current Academic Year",
                        "7500",
                        "593",
                        "1",
                        "20"});
            table1635.AddRow(new string[] {
                        "Apprenticeship 2",
                        "provider b",
                        "learner b",
                        "2",
                        "01/Sep/Last Academic Year",
                        "08/Sep/Current Academic Year",
                        "15000",
                        "593",
                        "1",
                        "20"});
#line 14
  testRunner.And("the following commitments exist", ((string)(null)), table1635, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1636 = new TechTalk.SpecFlow.Table(new string[] {
                        "Provider",
                        "Priority",
                        "Collection_Period"});
            table1636.AddRow(new string[] {
                        "provider a",
                        "1",
                        "R01/Current Academic Year"});
            table1636.AddRow(new string[] {
                        "provider b",
                        "2",
                        "R01/Current Academic Year"});
#line 19
  testRunner.And("the provider priority order is", ((string)(null)), table1636, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1637 = new TechTalk.SpecFlow.Table(new string[] {
                        "Learner ID",
                        "Delivery Period",
                        "On-Programme",
                        "Completion",
                        "Balancing"});
            table1637.AddRow(new string[] {
                        "learner a",
                        "Aug/Last Academic Year",
                        "0",
                        "0",
                        "0"});
            table1637.AddRow(new string[] {
                        "learner a",
                        "Sep/Last Academic Year",
                        "500",
                        "0",
                        "0"});
            table1637.AddRow(new string[] {
                        "learner a",
                        "Oct/Last Academic Year",
                        "500",
                        "0",
                        "0"});
            table1637.AddRow(new string[] {
                        "learner a",
                        "Nov/Last Academic Year",
                        "500",
                        "0",
                        "0"});
            table1637.AddRow(new string[] {
                        "learner a",
                        "Dec/Last Academic Year",
                        "500",
                        "0",
                        "0"});
            table1637.AddRow(new string[] {
                        "learner a",
                        "Jan/Last Academic Year",
                        "500",
                        "0",
                        "0"});
            table1637.AddRow(new string[] {
                        "learner a",
                        "Feb/Last Academic Year",
                        "500",
                        "0",
                        "0"});
            table1637.AddRow(new string[] {
                        "learner a",
                        "Mar/Last Academic Year",
                        "500",
                        "0",
                        "0"});
            table1637.AddRow(new string[] {
                        "learner a",
                        "Apr/Last Academic Year",
                        "500",
                        "0",
                        "0"});
            table1637.AddRow(new string[] {
                        "learner a",
                        "May/Last Academic Year",
                        "500",
                        "0",
                        "0"});
            table1637.AddRow(new string[] {
                        "learner a",
                        "Jun/Last Academic Year",
                        "500",
                        "0",
                        "0"});
            table1637.AddRow(new string[] {
                        "learner a",
                        "Jul/Last Academic Year",
                        "500",
                        "0",
                        "0"});
#line 24
   testRunner.And("the following earnings had been generated for the learner for \"provider a\"", ((string)(null)), table1637, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1638 = new TechTalk.SpecFlow.Table(new string[] {
                        "Learner ID",
                        "Delivery Period",
                        "On-Programme",
                        "Completion",
                        "Balancing"});
            table1638.AddRow(new string[] {
                        "learner b",
                        "Aug/Last Academic Year",
                        "0",
                        "0",
                        "0"});
            table1638.AddRow(new string[] {
                        "learner b",
                        "Sep/Last Academic Year",
                        "1000",
                        "0",
                        "0"});
            table1638.AddRow(new string[] {
                        "learner b",
                        "Oct/Last Academic Year",
                        "1000",
                        "0",
                        "0"});
            table1638.AddRow(new string[] {
                        "learner b",
                        "Nov/Last Academic Year",
                        "1000",
                        "0",
                        "0"});
            table1638.AddRow(new string[] {
                        "learner b",
                        "Dec/Last Academic Year",
                        "1000",
                        "0",
                        "0"});
            table1638.AddRow(new string[] {
                        "learner b",
                        "Jan/Last Academic Year",
                        "1000",
                        "0",
                        "0"});
            table1638.AddRow(new string[] {
                        "learner b",
                        "Feb/Last Academic Year",
                        "1000",
                        "0",
                        "0"});
            table1638.AddRow(new string[] {
                        "learner b",
                        "Mar/Last Academic Year",
                        "1000",
                        "0",
                        "0"});
            table1638.AddRow(new string[] {
                        "learner b",
                        "Apr/Last Academic Year",
                        "1000",
                        "0",
                        "0"});
            table1638.AddRow(new string[] {
                        "learner b",
                        "May/Last Academic Year",
                        "1000",
                        "0",
                        "0"});
            table1638.AddRow(new string[] {
                        "learner b",
                        "Jun/Last Academic Year",
                        "1000",
                        "0",
                        "0"});
            table1638.AddRow(new string[] {
                        "learner b",
                        "Jul/Last Academic Year",
                        "1000",
                        "0",
                        "0"});
#line 38
 testRunner.And("the following earnings had been generated for the learner for \"provider b\"", ((string)(null)), table1638, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1639 = new TechTalk.SpecFlow.Table(new string[] {
                        "Learner ID",
                        "Collection Period",
                        "Delivery Period",
                        "Levy Payments",
                        "Transaction Type"});
            table1639.AddRow(new string[] {
                        "learner a",
                        "R02/Last Academic Year",
                        "Sep/Last Academic Year",
                        "500",
                        "Learning"});
            table1639.AddRow(new string[] {
                        "learner a",
                        "R03/Last Academic Year",
                        "Oct/Last Academic Year",
                        "500",
                        "Learning"});
            table1639.AddRow(new string[] {
                        "learner a",
                        "R04/Last Academic Year",
                        "Nov/Last Academic Year",
                        "500",
                        "Learning"});
            table1639.AddRow(new string[] {
                        "learner a",
                        "R05/Last Academic Year",
                        "Dec/Last Academic Year",
                        "500",
                        "Learning"});
            table1639.AddRow(new string[] {
                        "learner a",
                        "R06/Last Academic Year",
                        "Jan/Last Academic Year",
                        "500",
                        "Learning"});
            table1639.AddRow(new string[] {
                        "learner a",
                        "R07/Last Academic Year",
                        "Feb/Last Academic Year",
                        "500",
                        "Learning"});
            table1639.AddRow(new string[] {
                        "learner a",
                        "R08/Last Academic Year",
                        "Mar/Last Academic Year",
                        "500",
                        "Learning"});
            table1639.AddRow(new string[] {
                        "learner a",
                        "R09/Last Academic Year",
                        "Apr/Last Academic Year",
                        "500",
                        "Learning"});
            table1639.AddRow(new string[] {
                        "learner a",
                        "R10/Last Academic Year",
                        "May/Last Academic Year",
                        "500",
                        "Learning"});
            table1639.AddRow(new string[] {
                        "learner a",
                        "R11/Last Academic Year",
                        "Jun/Last Academic Year",
                        "500",
                        "Learning"});
            table1639.AddRow(new string[] {
                        "learner a",
                        "R12/Last Academic Year",
                        "Jul/Last Academic Year",
                        "500",
                        "Learning"});
#line 52
    testRunner.And("the following \"provider a\" payments had been generated", ((string)(null)), table1639, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1640 = new TechTalk.SpecFlow.Table(new string[] {
                        "Learner ID",
                        "Collection Period",
                        "Delivery Period",
                        "Levy Payments",
                        "Transaction Type"});
            table1640.AddRow(new string[] {
                        "learner b",
                        "R02/Last Academic Year",
                        "Sep/Last Academic Year",
                        "1000",
                        "Learning"});
            table1640.AddRow(new string[] {
                        "learner b",
                        "R03/Last Academic Year",
                        "Oct/Last Academic Year",
                        "1000",
                        "Learning"});
            table1640.AddRow(new string[] {
                        "learner b",
                        "R04/Last Academic Year",
                        "Nov/Last Academic Year",
                        "1000",
                        "Learning"});
            table1640.AddRow(new string[] {
                        "learner b",
                        "R05/Last Academic Year",
                        "Dec/Last Academic Year",
                        "1000",
                        "Learning"});
            table1640.AddRow(new string[] {
                        "learner b",
                        "R06/Last Academic Year",
                        "Jan/Last Academic Year",
                        "1000",
                        "Learning"});
            table1640.AddRow(new string[] {
                        "learner b",
                        "R07/Last Academic Year",
                        "Feb/Last Academic Year",
                        "1000",
                        "Learning"});
            table1640.AddRow(new string[] {
                        "learner b",
                        "R08/Last Academic Year",
                        "Mar/Last Academic Year",
                        "1000",
                        "Learning"});
            table1640.AddRow(new string[] {
                        "learner b",
                        "R09/Last Academic Year",
                        "Apr/Last Academic Year",
                        "1000",
                        "Learning"});
            table1640.AddRow(new string[] {
                        "learner b",
                        "R10/Last Academic Year",
                        "May/Last Academic Year",
                        "1000",
                        "Learning"});
            table1640.AddRow(new string[] {
                        "learner b",
                        "R11/Last Academic Year",
                        "Jun/Last Academic Year",
                        "1000",
                        "Learning"});
            table1640.AddRow(new string[] {
                        "learner b",
                        "R12/Last Academic Year",
                        "Jul/Last Academic Year",
                        "1000",
                        "Learning"});
#line 65
 testRunner.And("the following \"provider b\" payments had been generated", ((string)(null)), table1640, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1641 = new TechTalk.SpecFlow.Table(new string[] {
                        "Learner ID",
                        "Start Date",
                        "Planned Duration",
                        "Total Training Price",
                        "Total Training Price Effective Date",
                        "Total Assessment Price",
                        "Total Assessment Price Effective Date",
                        "Actual Duration",
                        "Completion Status",
                        "Contract Type",
                        "Aim Sequence Number",
                        "Aim Reference",
                        "Framework Code",
                        "Pathway Code",
                        "Programme Type",
                        "Funding Line Type",
                        "SFA Contribution Percentage"});
            table1641.AddRow(new string[] {
                        "learner a",
                        "01/Sep/Last Academic Year",
                        "12 months",
                        "7500",
                        "01/Sep/Last Academic Year",
                        "",
                        "",
                        "12 months",
                        "completed",
                        "Act1",
                        "1",
                        "ZPROG001",
                        "593",
                        "1",
                        "20",
                        "19+ Apprenticeship (From May 2017) Levy Contract",
                        "90%"});
#line 78
    testRunner.But("the \"provider a\" now changes the Learner details as follows", ((string)(null)), table1641, "But ");
#line hidden
            TechTalk.SpecFlow.Table table1642 = new TechTalk.SpecFlow.Table(new string[] {
                        "Learner ID",
                        "Start Date",
                        "Planned Duration",
                        "Total Training Price",
                        "Total Training Price Effective Date",
                        "Total Assessment Price",
                        "Total Assessment Price Effective Date",
                        "Actual Duration",
                        "Completion Status",
                        "Contract Type",
                        "Aim Sequence Number",
                        "Aim Reference",
                        "Framework Code",
                        "Pathway Code",
                        "Programme Type",
                        "Funding Line Type",
                        "SFA Contribution Percentage"});
            table1642.AddRow(new string[] {
                        "learner b",
                        "01/Sep/Last Academic Year",
                        "12 months",
                        "15000",
                        "01/Sep/Last Academic Year",
                        "",
                        "",
                        "12 months",
                        "completed",
                        "Act1",
                        "1",
                        "ZPROG001",
                        "593",
                        "1",
                        "20",
                        "19+ Apprenticeship (From May 2017) Levy Contract",
                        "90%"});
#line 81
    testRunner.And("the \"provider b\" now changes the Learner details as follows", ((string)(null)), table1642, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1643 = new TechTalk.SpecFlow.Table(new string[] {
                        "Provider",
                        "Learner ID",
                        "Price Episode Id",
                        "Total Training Price",
                        "Total Training Price Effective Date",
                        "Total Assessment Price",
                        "Total Assessment Price Effective Date",
                        "Contract Type",
                        "Aim Sequence Number",
                        "SFA Contribution Percentage"});
            table1643.AddRow(new string[] {
                        "provider a",
                        "learner a",
                        "pe-1",
                        "7500",
                        "01/Sep/Last Academic Year",
                        "",
                        "01/Sep/Last Academic Year",
                        "Act1",
                        "1",
                        "90%"});
            table1643.AddRow(new string[] {
                        "provider b",
                        "learner b",
                        "pe-2",
                        "15000",
                        "01/Sep/Last Academic Year",
                        "",
                        "01/Sep/Last Academic Year",
                        "Act1",
                        "1",
                        "90%"});
#line 84
 testRunner.And("price details as follows", ((string)(null)), table1643, "And ");
#line 88
 testRunner.When(string.Format("the amended ILR file is re-submitted for the learners in the collection period {0" +
                        "} by \"provider a\"", collection_Period), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 89
 testRunner.When(string.Format("the amended ILR file is re-submitted for the learners in the collection period {0" +
                        "} by \"provider b\"", collection_Period), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table1644 = new TechTalk.SpecFlow.Table(new string[] {
                        "Learner ID",
                        "Delivery Period",
                        "On-Programme",
                        "Completion",
                        "Balancing",
                        "Price Episode Identifier"});
            table1644.AddRow(new string[] {
                        "learner a",
                        "Aug/Current Academic Year",
                        "500",
                        "0",
                        "0",
                        "pe-1"});
            table1644.AddRow(new string[] {
                        "learner a",
                        "Sep/Current Academic Year",
                        "0",
                        "1500",
                        "0",
                        "pe-1"});
            table1644.AddRow(new string[] {
                        "learner a",
                        "Oct/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-1"});
            table1644.AddRow(new string[] {
                        "learner a",
                        "Nov/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-1"});
            table1644.AddRow(new string[] {
                        "learner a",
                        "Dec/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-1"});
            table1644.AddRow(new string[] {
                        "learner a",
                        "Jan/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-1"});
            table1644.AddRow(new string[] {
                        "learner a",
                        "Feb/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-1"});
            table1644.AddRow(new string[] {
                        "learner a",
                        "Mar/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-1"});
            table1644.AddRow(new string[] {
                        "learner a",
                        "Apr/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-1"});
            table1644.AddRow(new string[] {
                        "learner a",
                        "May/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-1"});
            table1644.AddRow(new string[] {
                        "learner a",
                        "Jun/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-1"});
            table1644.AddRow(new string[] {
                        "learner a",
                        "Jul/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-1"});
#line 90
 testRunner.Then("the following learner earnings should be generated for \"provider a\"", ((string)(null)), table1644, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table1645 = new TechTalk.SpecFlow.Table(new string[] {
                        "Learner ID",
                        "Delivery Period",
                        "On-Programme",
                        "Completion",
                        "Balancing",
                        "Price Episode Identifier"});
            table1645.AddRow(new string[] {
                        "learner b",
                        "Aug/Current Academic Year",
                        "1000",
                        "0",
                        "0",
                        "pe-2"});
            table1645.AddRow(new string[] {
                        "learner b",
                        "Sep/Current Academic Year",
                        "0",
                        "3000",
                        "0",
                        "pe-2"});
            table1645.AddRow(new string[] {
                        "learner b",
                        "Oct/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-2"});
            table1645.AddRow(new string[] {
                        "learner b",
                        "Nov/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-2"});
            table1645.AddRow(new string[] {
                        "learner b",
                        "Dec/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-2"});
            table1645.AddRow(new string[] {
                        "learner b",
                        "Jan/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-2"});
            table1645.AddRow(new string[] {
                        "learner b",
                        "Feb/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-2"});
            table1645.AddRow(new string[] {
                        "learner b",
                        "Mar/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-2"});
            table1645.AddRow(new string[] {
                        "learner b",
                        "Apr/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-2"});
            table1645.AddRow(new string[] {
                        "learner b",
                        "May/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-2"});
            table1645.AddRow(new string[] {
                        "learner b",
                        "Jun/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-2"});
            table1645.AddRow(new string[] {
                        "learner b",
                        "Jul/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-2"});
#line 104
 testRunner.And("the following learner earnings should be generated for \"provider b\"", ((string)(null)), table1645, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1646 = new TechTalk.SpecFlow.Table(new string[] {
                        "Learner ID",
                        "Collection Period",
                        "Delivery Period",
                        "On-Programme",
                        "Completion",
                        "Balancing"});
            table1646.AddRow(new string[] {
                        "learner a",
                        "R01/Current Academic Year",
                        "Aug/Current Academic Year",
                        "500",
                        "0",
                        "0"});
            table1646.AddRow(new string[] {
                        "learner a",
                        "R02/Current Academic Year",
                        "Sep/Current Academic Year",
                        "0",
                        "1500",
                        "0"});
#line 118
    testRunner.And("at month end only the following payments will be calculated for \"provider a\"", ((string)(null)), table1646, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1647 = new TechTalk.SpecFlow.Table(new string[] {
                        "Learner ID",
                        "Collection Period",
                        "Delivery Period",
                        "On-Programme",
                        "Completion",
                        "Balancing"});
            table1647.AddRow(new string[] {
                        "learner b",
                        "R01/Current Academic Year",
                        "Aug/Current Academic Year",
                        "1000",
                        "0",
                        "0"});
            table1647.AddRow(new string[] {
                        "learner b",
                        "R02/Current Academic Year",
                        "Sep/Current Academic Year",
                        "0",
                        "3000",
                        "0"});
#line 122
    testRunner.And("at month end only the following payments will be calculated for \"provider b\"", ((string)(null)), table1647, "And ");
#line 127
 testRunner.And("Month end is triggered", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1648 = new TechTalk.SpecFlow.Table(new string[] {
                        "Learner ID",
                        "Collection Period",
                        "Delivery Period",
                        "Levy Payments",
                        "Transaction Type"});
            table1648.AddRow(new string[] {
                        "learner a",
                        "R01/Current Academic Year",
                        "Aug/Current Academic Year",
                        "500",
                        "Learning"});
            table1648.AddRow(new string[] {
                        "learner a",
                        "R02/Current Academic Year",
                        "Sep/Current Academic Year",
                        "1500",
                        "Completion"});
#line 129
 testRunner.And("only the following \"provider a\" payments will be recorded", ((string)(null)), table1648, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1649 = new TechTalk.SpecFlow.Table(new string[] {
                        "Learner ID",
                        "Collection Period",
                        "Delivery Period",
                        "Levy Payments",
                        "Transaction Type"});
            table1649.AddRow(new string[] {
                        "learner b",
                        "R01/Current Academic Year",
                        "Aug/Current Academic Year",
                        "1000",
                        "Learning"});
            table1649.AddRow(new string[] {
                        "learner b",
                        "R02/Current Academic Year",
                        "Sep/Current Academic Year",
                        "3000",
                        "Completion"});
#line 133
 testRunner.And("only the following \"provider b\" payments will be recorded", ((string)(null)), table1649, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1650 = new TechTalk.SpecFlow.Table(new string[] {
                        "Learner ID",
                        "Collection Period",
                        "Delivery Period",
                        "Levy Payments",
                        "Transaction Type"});
            table1650.AddRow(new string[] {
                        "learner a",
                        "R01/Current Academic Year",
                        "Aug/Current Academic Year",
                        "500",
                        "Learning"});
            table1650.AddRow(new string[] {
                        "learner a",
                        "R02/Current Academic Year",
                        "Sep/Current Academic Year",
                        "1500",
                        "Completion"});
#line 137
 testRunner.And("only the following \"provider a\" payments will be generated", ((string)(null)), table1650, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1651 = new TechTalk.SpecFlow.Table(new string[] {
                        "Learner ID",
                        "Collection Period",
                        "Delivery Period",
                        "Levy Payments",
                        "Transaction Type"});
            table1651.AddRow(new string[] {
                        "learner b",
                        "R01/Current Academic Year",
                        "Aug/Current Academic Year",
                        "1000",
                        "Learning"});
            table1651.AddRow(new string[] {
                        "learner b",
                        "R02/Current Academic Year",
                        "Sep/Current Academic Year",
                        "3000",
                        "Completion"});
#line 141
 testRunner.And("only the following \"provider b\" payments will be generated", ((string)(null)), table1651, "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
