// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SFA.DAS.Payments.AcceptanceTests.EndToEnd.Tests.Transfers
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Transfers - PV2-732 Single Levy learner paid via transfer but withdraws, refund t" +
        "o sender employer")]
    public partial class Transfers_PV2_732SingleLevyLearnerPaidViaTransferButWithdrawsRefundToSenderEmployerFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "PV2-732 - Single Levy learner paid via transfer but withdraws refund to sender employer.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Transfers - PV2-732 Single Levy learner paid via transfer but withdraws, refund t" +
                    "o sender employer", "\tAs a provider,\r\n\tI want a Levy learner, where the employer receives a transfer f" +
                    "rom another employer to fund the learner, and the learner then withdraws\r\n\tSo th" +
                    "at I am not paid for the learner by SFA via a transfer - PV2-732", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Transfers - Single Levy learner paid via transfer but withdraws, refund to sender" +
            " employer - PV2-732")]
        [NUnit.Framework.TestCaseAttribute("R12/Current Academic Year", "0", "60000", "0", null)]
        public virtual void Transfers_SingleLevyLearnerPaidViaTransferButWithdrawsRefundToSenderEmployer_PV2_732(string collection_Period, string levyBalanceForEmployer1, string levyBalanceForEmployer2, string employer2RemainingTransferAllowance, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Transfers - Single Levy learner paid via transfer but withdraws, refund to sender" +
                    " employer - PV2-732", null, exampleTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 8
 testRunner.Given(string.Format("the \"employer 1\" levy account balance in collection period {0} is {1}", collection_Period, levyBalanceForEmployer1), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 9
 testRunner.And(string.Format("the \"employer 2\" levy account balance in collection period {0} is {1}", collection_Period, levyBalanceForEmployer2), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
 testRunner.And(string.Format("the remaining transfer allowance for \"employer 2\" is {0}", employer2RemainingTransferAllowance), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2191 = new TechTalk.SpecFlow.Table(new string[] {
                        "Employer",
                        "Sending Employer",
                        "Start Date",
                        "End Date",
                        "Agreed Price",
                        "Standard Code",
                        "Programme Type",
                        "Status",
                        "Effective From"});
            table2191.AddRow(new string[] {
                        "employer 1",
                        "employer 2",
                        "01/May/Current Academic Year",
                        "01/May/Next Academic Year",
                        "15000",
                        "50",
                        "25",
                        "active",
                        "01/May/Current Academic Year"});
#line 13
 testRunner.And("the following apprenticeships exist", ((string)(null)), table2191, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2192 = new TechTalk.SpecFlow.Table(new string[] {
                        "Start Date",
                        "Planned Duration",
                        "Total Training Price",
                        "Total Training Price Effective Date",
                        "Total Assessment Price",
                        "Total Assessment Price Effective Date",
                        "Actual Duration",
                        "Completion Status",
                        "Contract Type",
                        "Aim Sequence Number",
                        "Aim Reference",
                        "Standard Code",
                        "Programme Type",
                        "Funding Line Type",
                        "SFA Contribution Percentage"});
            table2192.AddRow(new string[] {
                        "06/May/Current Academic Year",
                        "12 months",
                        "12000",
                        "06/May/Current Academic Year",
                        "3000",
                        "06/May/Current Academic Year",
                        "",
                        "continuing",
                        "Act1",
                        "1",
                        "ZPROG001",
                        "50",
                        "25",
                        "19-24 Apprenticeship (From May 2017) Levy Contract",
                        "90%"});
#line 17
    testRunner.And("the provider previously submitted the following learner details", ((string)(null)), table2192, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2193 = new TechTalk.SpecFlow.Table(new string[] {
                        "Delivery Period",
                        "On-Programme",
                        "Completion",
                        "Balancing"});
            table2193.AddRow(new string[] {
                        "Aug/Current Academic Year",
                        "0",
                        "0",
                        "0"});
            table2193.AddRow(new string[] {
                        "Sep/Current Academic Year",
                        "0",
                        "0",
                        "0"});
            table2193.AddRow(new string[] {
                        "Oct/Current Academic Year",
                        "0",
                        "0",
                        "0"});
            table2193.AddRow(new string[] {
                        "Nov/Current Academic Year",
                        "0",
                        "0",
                        "0"});
            table2193.AddRow(new string[] {
                        "Dec/Current Academic Year",
                        "0",
                        "0",
                        "0"});
            table2193.AddRow(new string[] {
                        "Jan/Current Academic Year",
                        "0",
                        "0",
                        "0"});
            table2193.AddRow(new string[] {
                        "Feb/Current Academic Year",
                        "0",
                        "0",
                        "0"});
            table2193.AddRow(new string[] {
                        "Mar/Current Academic Year",
                        "0",
                        "0",
                        "0"});
            table2193.AddRow(new string[] {
                        "Apr/Current Academic Year",
                        "0",
                        "0",
                        "0"});
            table2193.AddRow(new string[] {
                        "May/Current Academic Year",
                        "1000",
                        "0",
                        "0"});
            table2193.AddRow(new string[] {
                        "Jun/Current Academic Year",
                        "1000",
                        "0",
                        "0"});
            table2193.AddRow(new string[] {
                        "Jul/Current Academic Year",
                        "1000",
                        "0",
                        "0"});
#line 21
 testRunner.And("the following earnings had been generated for the learner", ((string)(null)), table2193, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2194 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection Period",
                        "Delivery Period",
                        "Levy Payments",
                        "Transfer Payments",
                        "Transaction Type",
                        "Employer",
                        "Sending Employer"});
            table2194.AddRow(new string[] {
                        "R10/Current Academic Year",
                        "May/Current Academic Year",
                        "0",
                        "1000",
                        "Learning",
                        "employer 1",
                        "employer 2"});
            table2194.AddRow(new string[] {
                        "R11/Current Academic Year",
                        "Jun/Current Academic Year",
                        "0",
                        "1000",
                        "Learning",
                        "employer 1",
                        "employer 2"});
#line 36
 testRunner.And("the following provider payments had been generated", ((string)(null)), table2194, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2195 = new TechTalk.SpecFlow.Table(new string[] {
                        "Start Date",
                        "Planned Duration",
                        "Total Training Price",
                        "Total Training Price Effective Date",
                        "Total Assessment Price",
                        "Total Assessment Price Effective Date",
                        "Actual Duration",
                        "Completion Status",
                        "Contract Type",
                        "Aim Sequence Number",
                        "Aim Reference",
                        "Standard Code",
                        "Programme Type",
                        "Funding Line Type",
                        "SFA Contribution Percentage"});
            table2195.AddRow(new string[] {
                        "06/May/Current Academic Year",
                        "12 months",
                        "12000",
                        "06/May/Current Academic Year",
                        "3000",
                        "06/May/Current Academic Year",
                        "0 months",
                        "withdrawn",
                        "Act1",
                        "1",
                        "ZPROG001",
                        "50",
                        "25",
                        "19-24 Apprenticeship (From May 2017) Levy Contract",
                        "90%"});
#line 41
 testRunner.But("the Provider now changes the Learner details as follows", ((string)(null)), table2195, "But ");
#line 45
 testRunner.When(string.Format("the amended ILR file is re-submitted for the learners in collection period {0}", collection_Period), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2196 = new TechTalk.SpecFlow.Table(new string[] {
                        "Delivery Period",
                        "On-Programme",
                        "Completion",
                        "Balancing"});
            table2196.AddRow(new string[] {
                        "Aug/Current Academic Year",
                        "0",
                        "0",
                        "0"});
            table2196.AddRow(new string[] {
                        "Sep/Current Academic Year",
                        "0",
                        "0",
                        "0"});
            table2196.AddRow(new string[] {
                        "Oct/Current Academic Year",
                        "0",
                        "0",
                        "0"});
            table2196.AddRow(new string[] {
                        "Nov/Current Academic Year",
                        "0",
                        "0",
                        "0"});
            table2196.AddRow(new string[] {
                        "Dec/Current Academic Year",
                        "0",
                        "0",
                        "0"});
            table2196.AddRow(new string[] {
                        "Jan/Current Academic Year",
                        "0",
                        "0",
                        "0"});
            table2196.AddRow(new string[] {
                        "Feb/Current Academic Year",
                        "0",
                        "0",
                        "0"});
            table2196.AddRow(new string[] {
                        "Mar/Current Academic Year",
                        "0",
                        "0",
                        "0"});
            table2196.AddRow(new string[] {
                        "Apr/Current Academic Year",
                        "0",
                        "0",
                        "0"});
            table2196.AddRow(new string[] {
                        "May/Current Academic Year",
                        "0",
                        "0",
                        "0"});
            table2196.AddRow(new string[] {
                        "Jun/Current Academic Year",
                        "0",
                        "0",
                        "0"});
            table2196.AddRow(new string[] {
                        "Jul/Current Academic Year",
                        "0",
                        "0",
                        "0"});
#line 46
 testRunner.Then("the following learner earnings should be generated", ((string)(null)), table2196, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table2197 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection Period",
                        "Delivery Period",
                        "On-Programme",
                        "Completion",
                        "Balancing"});
            table2197.AddRow(new string[] {
                        "R12/Current Academic Year",
                        "May/Current Academic Year",
                        "-1000",
                        "0",
                        "0"});
            table2197.AddRow(new string[] {
                        "R12/Current Academic Year",
                        "Jun/Current Academic Year",
                        "-1000",
                        "0",
                        "0"});
#line 61
    testRunner.And("at month end only the following payments will be calculated", ((string)(null)), table2197, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2198 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection Period",
                        "Delivery Period",
                        "Levy Payments",
                        "Transfer Payments",
                        "Transaction Type",
                        "Employer",
                        "Sending Employer",
                        "Standard Code"});
            table2198.AddRow(new string[] {
                        "R12/Current Academic Year",
                        "May/Current Academic Year",
                        "0",
                        "-1000",
                        "Learning",
                        "employer 1",
                        "employer 2",
                        "50"});
            table2198.AddRow(new string[] {
                        "R12/Current Academic Year",
                        "Jun/Current Academic Year",
                        "0",
                        "-1000",
                        "Learning",
                        "employer 1",
                        "employer 2",
                        "50"});
#line 65
 testRunner.And("only the following provider payments will be recorded", ((string)(null)), table2198, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2199 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection Period",
                        "Delivery Period",
                        "Levy Payments",
                        "Transfer Payments",
                        "Transaction Type",
                        "Employer",
                        "Sending Employer",
                        "Standard Code"});
            table2199.AddRow(new string[] {
                        "R12/Current Academic Year",
                        "May/Current Academic Year",
                        "0",
                        "-1000",
                        "Learning",
                        "employer 1",
                        "employer 2",
                        "50"});
            table2199.AddRow(new string[] {
                        "R12/Current Academic Year",
                        "Jun/Current Academic Year",
                        "0",
                        "-1000",
                        "Learning",
                        "employer 1",
                        "employer 2",
                        "50"});
#line 69
 testRunner.And("only the following provider payments will be generated", ((string)(null)), table2199, "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
