// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SFA.DAS.Payments.AcceptanceTests.EndToEnd.Tests.Transfers
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Transfers - PV2-733 Two Levy learners paid via transfer but later one deleted, se" +
        "nder gets refund")]
    public partial class Transfers_PV2_733TwoLevyLearnersPaidViaTransferButLaterOneDeletedSenderGetsRefundFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "PV2-733 - Two Levy learners paid via transfer but later one deleted sender gets refund.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Transfers - PV2-733 Two Levy learners paid via transfer but later one deleted, se" +
                    "nder gets refund", "\tAs a provider,\r\n\tI want a Levy learner, where the employer receives a transfer f" +
                    "rom another employer to fund the learner, and 1 learner is then deleted\r\n\tSo tha" +
                    "t I am not paid for the deleted learner by SFA via a transfer - PV2-733", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Transfers - Two Levy learners paid via transfer but later one deleted, sender get" +
            "s refund - PV2-733")]
        [NUnit.Framework.TestCaseAttribute("R12/Current Academic Year", "0", "72000", "600", null)]
        public virtual void Transfers_TwoLevyLearnersPaidViaTransferButLaterOneDeletedSenderGetsRefund_PV2_733(string collection_Period, string levyBalanceForEmployer1, string levyBalanceForEmployer2, string employer2RemainingTransferAllowance, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Transfers - Two Levy learners paid via transfer but later one deleted, sender get" +
                    "s refund - PV2-733", null, exampleTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 8
 testRunner.Given(string.Format("the \"employer 1\" levy account balance in collection period {0} is {1}", collection_Period, levyBalanceForEmployer1), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 9
 testRunner.And(string.Format("the \"employer 2\" levy account balance in collection period {0} is {1}", collection_Period, levyBalanceForEmployer2), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
 testRunner.And(string.Format("the remaining transfer allowance for \"employer 2\" is {0}", employer2RemainingTransferAllowance), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2200 = new TechTalk.SpecFlow.Table(new string[] {
                        "Learner ID",
                        "Identifier",
                        "Employer",
                        "Sending Employer",
                        "Start Date",
                        "End Date",
                        "Agreed Price",
                        "Standard Code",
                        "Programme Type",
                        "Status",
                        "Effective From"});
            table2200.AddRow(new string[] {
                        "learner a",
                        "Apprentiiship a",
                        "employer 1",
                        "employer 2",
                        "01/May/Current Academic Year",
                        "01/May/Next Academic Year",
                        "9000",
                        "50",
                        "25",
                        "active",
                        "01/May/Current Academic Year"});
            table2200.AddRow(new string[] {
                        "learner b",
                        "Apprentiiship b",
                        "employer 1",
                        "employer 2",
                        "01/May/Current Academic Year",
                        "01/May/Next Academic Year",
                        "9000",
                        "50",
                        "25",
                        "active",
                        "01/May/Current Academic Year"});
#line 13
 testRunner.And("the following apprenticeships exist", ((string)(null)), table2200, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2201 = new TechTalk.SpecFlow.Table(new string[] {
                        "Learner ID",
                        "Start Date",
                        "Planned Duration",
                        "Total Training Price",
                        "Total Training Price Effective Date",
                        "Total Assessment Price",
                        "Total Assessment Price Effective Date",
                        "Actual Duration",
                        "Completion Status",
                        "Contract Type",
                        "Aim Sequence Number",
                        "Aim Reference",
                        "Standard Code",
                        "Programme Type",
                        "Funding Line Type",
                        "SFA Contribution Percentage"});
            table2201.AddRow(new string[] {
                        "learner a",
                        "01/May/Current Academic Year",
                        "12 months",
                        "9000",
                        "01/May/Current Academic Year",
                        "0",
                        "01/May/Current Academic Year",
                        "",
                        "continuing",
                        "Act1",
                        "1",
                        "ZPROG001",
                        "50",
                        "25",
                        "16-18 Apprenticeship (From May 2017) Levy Contract",
                        "90%"});
            table2201.AddRow(new string[] {
                        "learner b",
                        "01/May/Current Academic Year",
                        "12 months",
                        "9000",
                        "01/May/Current Academic Year",
                        "0",
                        "01/May/Current Academic Year",
                        "",
                        "continuing",
                        "Act1",
                        "1",
                        "ZPROG001",
                        "50",
                        "25",
                        "16-18 Apprenticeship (From May 2017) Levy Contract",
                        "90%"});
#line 18
    testRunner.And("the provider previously submitted the following learner details", ((string)(null)), table2201, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2202 = new TechTalk.SpecFlow.Table(new string[] {
                        "Learner ID",
                        "Delivery Period",
                        "On-Programme",
                        "Completion",
                        "Balancing"});
            table2202.AddRow(new string[] {
                        "learner a",
                        "Aug/Current Academic Year",
                        "0",
                        "0",
                        "0"});
            table2202.AddRow(new string[] {
                        "learner a",
                        "Sep/Current Academic Year",
                        "0",
                        "0",
                        "0"});
            table2202.AddRow(new string[] {
                        "learner a",
                        "Oct/Current Academic Year",
                        "0",
                        "0",
                        "0"});
            table2202.AddRow(new string[] {
                        "learner a",
                        "Nov/Current Academic Year",
                        "0",
                        "0",
                        "0"});
            table2202.AddRow(new string[] {
                        "learner a",
                        "Dec/Current Academic Year",
                        "0",
                        "0",
                        "0"});
            table2202.AddRow(new string[] {
                        "learner a",
                        "Jan/Current Academic Year",
                        "0",
                        "0",
                        "0"});
            table2202.AddRow(new string[] {
                        "learner a",
                        "Feb/Current Academic Year",
                        "0",
                        "0",
                        "0"});
            table2202.AddRow(new string[] {
                        "learner a",
                        "Mar/Current Academic Year",
                        "0",
                        "0",
                        "0"});
            table2202.AddRow(new string[] {
                        "learner a",
                        "Apr/Current Academic Year",
                        "0",
                        "0",
                        "0"});
            table2202.AddRow(new string[] {
                        "learner a",
                        "May/Current Academic Year",
                        "600",
                        "0",
                        "0"});
            table2202.AddRow(new string[] {
                        "learner a",
                        "Jun/Current Academic Year",
                        "600",
                        "0",
                        "0"});
            table2202.AddRow(new string[] {
                        "learner a",
                        "Jul/Current Academic Year",
                        "600",
                        "0",
                        "0"});
            table2202.AddRow(new string[] {
                        "learner b",
                        "Aug/Current Academic Year",
                        "0",
                        "0",
                        "0"});
            table2202.AddRow(new string[] {
                        "learner b",
                        "Sep/Current Academic Year",
                        "0",
                        "0",
                        "0"});
            table2202.AddRow(new string[] {
                        "learner b",
                        "Oct/Current Academic Year",
                        "0",
                        "0",
                        "0"});
            table2202.AddRow(new string[] {
                        "learner b",
                        "Nov/Current Academic Year",
                        "0",
                        "0",
                        "0"});
            table2202.AddRow(new string[] {
                        "learner b",
                        "Dec/Current Academic Year",
                        "0",
                        "0",
                        "0"});
            table2202.AddRow(new string[] {
                        "learner b",
                        "Jan/Current Academic Year",
                        "0",
                        "0",
                        "0"});
            table2202.AddRow(new string[] {
                        "learner b",
                        "Feb/Current Academic Year",
                        "0",
                        "0",
                        "0"});
            table2202.AddRow(new string[] {
                        "learner b",
                        "Mar/Current Academic Year",
                        "0",
                        "0",
                        "0"});
            table2202.AddRow(new string[] {
                        "learner b",
                        "Apr/Current Academic Year",
                        "0",
                        "0",
                        "0"});
            table2202.AddRow(new string[] {
                        "learner b",
                        "May/Current Academic Year",
                        "600",
                        "0",
                        "0"});
            table2202.AddRow(new string[] {
                        "learner b",
                        "Jun/Current Academic Year",
                        "600",
                        "0",
                        "0"});
            table2202.AddRow(new string[] {
                        "learner b",
                        "Jul/Current Academic Year",
                        "600",
                        "0",
                        "0"});
#line 23
 testRunner.And("the following earnings had been generated for the learner", ((string)(null)), table2202, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2203 = new TechTalk.SpecFlow.Table(new string[] {
                        "Learner ID",
                        "Collection Period",
                        "Delivery Period",
                        "Levy Payments",
                        "Transfer Payments",
                        "Transaction Type",
                        "Employer",
                        "Sending Employer"});
            table2203.AddRow(new string[] {
                        "learner a",
                        "R10/Current Academic Year",
                        "May/Current Academic Year",
                        "0",
                        "600",
                        "Learning",
                        "employer 1",
                        "employer 2"});
            table2203.AddRow(new string[] {
                        "learner a",
                        "R11/Current Academic Year",
                        "Jun/Current Academic Year",
                        "0",
                        "600",
                        "Learning",
                        "employer 1",
                        "employer 2"});
            table2203.AddRow(new string[] {
                        "learner b",
                        "R10/Current Academic Year",
                        "May/Current Academic Year",
                        "0",
                        "600",
                        "Learning",
                        "employer 1",
                        "employer 2"});
            table2203.AddRow(new string[] {
                        "learner b",
                        "R11/Current Academic Year",
                        "Jun/Current Academic Year",
                        "0",
                        "600",
                        "Learning",
                        "employer 1",
                        "employer 2"});
#line 49
 testRunner.And("the following provider payments had been generated", ((string)(null)), table2203, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2204 = new TechTalk.SpecFlow.Table(new string[] {
                        "Learner ID",
                        "Start Date",
                        "Planned Duration",
                        "Total Training Price",
                        "Total Training Price Effective Date",
                        "Total Assessment Price",
                        "Total Assessment Price Effective Date",
                        "Actual Duration",
                        "Completion Status",
                        "Contract Type",
                        "Aim Sequence Number",
                        "Aim Reference",
                        "Standard Code",
                        "Programme Type",
                        "Funding Line Type",
                        "SFA Contribution Percentage"});
            table2204.AddRow(new string[] {
                        "learner a",
                        "01/May/Current Academic Year",
                        "12 months",
                        "9000",
                        "01/May/Current Academic Year",
                        "0",
                        "01/May/Current Academic Year",
                        "",
                        "continuing",
                        "Act1",
                        "1",
                        "ZPROG001",
                        "50",
                        "25",
                        "16-18 Apprenticeship (From May 2017) Levy Contract",
                        "90%"});
#line 56
 testRunner.But("the Provider now changes the Learner details as follows", ((string)(null)), table2204, "But ");
#line hidden
            TechTalk.SpecFlow.Table table2205 = new TechTalk.SpecFlow.Table(new string[] {
                        "Learner ID",
                        "Price Episode Id",
                        "Total Training Price",
                        "Total Training Price Effective Date",
                        "Total Assessment Price",
                        "Total Assessment Price Effective Date",
                        "Residual Training Price",
                        "Residual Training Price Effective Date",
                        "Residual Assessment Price",
                        "Residual Assessment Price Effective Date",
                        "SFA Contribution Percentage",
                        "Contract Type",
                        "Aim Sequence Number"});
            table2205.AddRow(new string[] {
                        "learner a",
                        "pe-1",
                        "9000",
                        "01/May/Current Academic Year",
                        "0",
                        "01/May/Current Academic Year",
                        "0",
                        "",
                        "0",
                        "",
                        "90%",
                        "Act1",
                        "1"});
            table2205.AddRow(new string[] {
                        "learner b",
                        "pe-2",
                        "9000",
                        "01/MAy/Current Academic Year",
                        "0",
                        "01/May/Current Academic Year",
                        "0",
                        "",
                        "0",
                        "",
                        "90%",
                        "Act1",
                        "1"});
#line 59
 testRunner.And("price details as follows", ((string)(null)), table2205, "And ");
#line 64
 testRunner.When(string.Format("the amended ILR file is re-submitted for the learners in collection period {0}", collection_Period), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2206 = new TechTalk.SpecFlow.Table(new string[] {
                        "Learner ID",
                        "Delivery Period",
                        "On-Programme",
                        "Completion",
                        "Balancing",
                        "Price Episode Identifier"});
            table2206.AddRow(new string[] {
                        "learner a",
                        "Aug/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-1"});
            table2206.AddRow(new string[] {
                        "learner a",
                        "Sep/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-1"});
            table2206.AddRow(new string[] {
                        "learner a",
                        "Oct/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-1"});
            table2206.AddRow(new string[] {
                        "learner a",
                        "Nov/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-1"});
            table2206.AddRow(new string[] {
                        "learner a",
                        "Dec/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-1"});
            table2206.AddRow(new string[] {
                        "learner a",
                        "Jan/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-1"});
            table2206.AddRow(new string[] {
                        "learner a",
                        "Feb/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-1"});
            table2206.AddRow(new string[] {
                        "learner a",
                        "Mar/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-1"});
            table2206.AddRow(new string[] {
                        "learner a",
                        "Apr/Current Academic Year",
                        "0",
                        "0",
                        "0",
                        "pe-1"});
            table2206.AddRow(new string[] {
                        "learner a",
                        "May/Current Academic Year",
                        "600",
                        "0",
                        "0",
                        "pe-1"});
            table2206.AddRow(new string[] {
                        "learner a",
                        "Jun/Current Academic Year",
                        "600",
                        "0",
                        "0",
                        "pe-1"});
            table2206.AddRow(new string[] {
                        "learner a",
                        "Jul/Current Academic Year",
                        "600",
                        "0",
                        "0",
                        "pe-1"});
#line 65
 testRunner.Then("the following learner earnings should be generated", ((string)(null)), table2206, "Then ");
#line 79
 testRunner.And("3 required payments are generated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 80
 testRunner.And("levy month end is ran", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2207 = new TechTalk.SpecFlow.Table(new string[] {
                        "Learner ID",
                        "Collection Period",
                        "Delivery Period",
                        "Levy Payments",
                        "Transfer Payments",
                        "Transaction Type",
                        "Employer",
                        "Sending Employer",
                        "Standard Code"});
            table2207.AddRow(new string[] {
                        "learner a",
                        "R12/Current Academic Year",
                        "Jul/Current Academic Year",
                        "0",
                        "600",
                        "Learning",
                        "employer 1",
                        "employer 2",
                        "50"});
            table2207.AddRow(new string[] {
                        "learner b",
                        "R12/Current Academic Year",
                        "May/Current Academic Year",
                        "0",
                        "-600",
                        "Learning",
                        "employer 1",
                        "employer 2",
                        "50"});
            table2207.AddRow(new string[] {
                        "learner b",
                        "R12/Current Academic Year",
                        "Jun/Current Academic Year",
                        "0",
                        "-600",
                        "Learning",
                        "employer 1",
                        "employer 2",
                        "50"});
#line 81
 testRunner.And("only the following provider payments will be recorded", ((string)(null)), table2207, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2208 = new TechTalk.SpecFlow.Table(new string[] {
                        "Learner ID",
                        "Collection Period",
                        "Delivery Period",
                        "Levy Payments",
                        "Transfer Payments",
                        "Transaction Type",
                        "Employer",
                        "Sending Employer",
                        "Standard Code"});
            table2208.AddRow(new string[] {
                        "learner a",
                        "R12/Current Academic Year",
                        "Jul/Current Academic Year",
                        "0",
                        "600",
                        "Learning",
                        "employer 1",
                        "employer 2",
                        "50"});
            table2208.AddRow(new string[] {
                        "learner b",
                        "R12/Current Academic Year",
                        "May/Current Academic Year",
                        "0",
                        "-600",
                        "Learning",
                        "employer 1",
                        "employer 2",
                        "50"});
            table2208.AddRow(new string[] {
                        "learner b",
                        "R12/Current Academic Year",
                        "Jun/Current Academic Year",
                        "0",
                        "-600",
                        "Learning",
                        "employer 1",
                        "employer 2",
                        "50"});
#line 86
 testRunner.And("only the following provider payments will be generated", ((string)(null)), table2208, "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
