// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SFA.DAS.Payments.AcceptanceTests.EndToEnd.Tests.Employer_Change_of_Circumstances
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("One Levy Learner no payment if commitment has gap while changing employers and no" +
        " change in ACT code or employment status specified PV2-377")]
    [NUnit.Framework.IgnoreAttribute("Ignored feature")]
    public partial class OneLevyLearnerNoPaymentIfCommitmentHasGapWhileChangingEmployersAndNoChangeInACTCodeOrEmploymentStatusSpecifiedPV2_377Feature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "No_payment_commitment_gap_employer_change_same_ACT_PV2-377.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "One Levy Learner no payment if commitment has gap while changing employers and no" +
                    " change in ACT code or employment status specified PV2-377", @"		As a provider,
		I want provider earnings and payments where learner changes employer and there is a gap between commitments - provider receives no payment during the gap as they do not change the ACT code or employment status on the ILR, to be paid the correct amount
		So that I am accurately paid my apprenticeship provision.", ProgrammingLanguage.CSharp, new string[] {
                        "ignore"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("One Levy Learner no payment if commitment has gap while changing employers and no" +
            " change in ACT code or employment status specified PV2-377")]
        [NUnit.Framework.TestCaseAttribute("R01/Current Academic Year", "15500", "6125", null)]
        [NUnit.Framework.TestCaseAttribute("R02/Current Academic Year", "14500", "6125", null)]
        [NUnit.Framework.TestCaseAttribute("R03/Current Academic Year", "13500", "6125", null)]
        [NUnit.Framework.TestCaseAttribute("R04/Current Academic Year", "13500", "6125", null)]
        [NUnit.Framework.TestCaseAttribute("R05/Current Academic Year", "13500", "5625", null)]
        public virtual void OneLevyLearnerNoPaymentIfCommitmentHasGapWhileChangingEmployersAndNoChangeInACTCodeOrEmploymentStatusSpecifiedPV2_377(string collection_Period, string levyBalanceForEmployer1, string levyBalanceForEmployer2, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("One Levy Learner no payment if commitment has gap while changing employers and no" +
                    " change in ACT code or employment status specified PV2-377", null, exampleTags);
#line 7
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 8
 testRunner.Given(string.Format("the \"employer 1\" levy account balance in collection period {0} is {1}", collection_Period, levyBalanceForEmployer1), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 9
 testRunner.And(string.Format("the \"employer 2\" levy account balance in collection period {0} is {1}", collection_Period, levyBalanceForEmployer2), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Identifier",
                        "Employer",
                        "start date",
                        "end date",
                        "agreed price",
                        "status",
                        "effective from",
                        "effective to",
                        "stop effective from"});
            table1.AddRow(new string[] {
                        "Apprenticeship 1",
                        "employer 1",
                        "01/Aug/Current Academic Year",
                        "04/Aug/Next Academic Year",
                        "15000",
                        "cancelled",
                        "01/Aug/Current Academic Year",
                        "02/Oct/Current Academic Year",
                        "03/Oct/Current Academic Year"});
            table1.AddRow(new string[] {
                        "Apprenticeship 2",
                        "employer 2",
                        "01/Nov/Current Academic Year",
                        "04/Aug/Next Academic Year",
                        "5625",
                        "active",
                        "01/Nov/Current Academic Year",
                        "",
                        ""});
#line 10
 testRunner.And("the following commitments exist", ((string)(null)), table1, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Start Date",
                        "Planned Duration",
                        "Total Training Price",
                        "Total Training Price Effective Date",
                        "Total Assessment Price",
                        "Total Assessment Price Effective Date",
                        "Actual Duration",
                        "Completion Status",
                        "Contract Type",
                        "Aim Sequence Number",
                        "Aim Reference",
                        "Standard Code",
                        "Programme Type",
                        "Funding Line Type"});
            table2.AddRow(new string[] {
                        "03/Aug/Current Academic Year",
                        "12 months",
                        "12000",
                        "03/Aug/Current Academic Year",
                        "3000",
                        "03/Aug/Current Academic Year",
                        "",
                        "continuing",
                        "Act1",
                        "1",
                        "ZPROG001",
                        "51",
                        "25",
                        "16-18 Apprenticeship (From May 2017) Levy Contract"});
#line 14
    testRunner.And("the provider is providing training for the following learners", ((string)(null)), table2, "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Price Episode Id",
                        "Total Training Price",
                        "Total Training Price Effective Date",
                        "Total Assessment Price",
                        "Total Assessment Price Effective Date",
                        "Residual Training Price",
                        "Residual Training Price Effective Date",
                        "Residual Assessment Price",
                        "Residual Assessment Price Effective Date",
                        "SFA Contribution Percentage"});
            table3.AddRow(new string[] {
                        "pe-1",
                        "12000",
                        "03/Aug/Current Academic Year",
                        "3000",
                        "03/Aug/Current Academic Year",
                        "0",
                        "",
                        "0",
                        "",
                        "90%"});
            table3.AddRow(new string[] {
                        "pe-2",
                        "12000",
                        "03/Aug/Current Academic Year",
                        "3000",
                        "03/Aug/Current Academic Year",
                        "5000",
                        "03/Nov/Current Academic Year",
                        "625",
                        "03/Nov/Current Academic Year",
                        "90%"});
#line 17
 testRunner.And("price details as follows", ((string)(null)), table3, "And ");
#line 21
 testRunner.When(string.Format("the ILR file is submitted for the learners for collection period {0}", collection_Period), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Delivery Period",
                        "On-Programme",
                        "Completion",
                        "Balancing",
                        "Price Episode Identifier"});
            table4.AddRow(new string[] {
                        "Aug/Current Academic Year",
                        "1000",
                        "0",
                        "0",
                        "pe-1"});
            table4.AddRow(new string[] {
                        "Sep/Current Academic Year",
                        "1000",
                        "0",
                        "0",
                        "pe-1"});
            table4.AddRow(new string[] {
                        "Oct/Current Academic Year",
                        "1000",
                        "0",
                        "0",
                        "pe-1"});
            table4.AddRow(new string[] {
                        "Nov/Current Academic Year",
                        "500",
                        "0",
                        "0",
                        "pe-2"});
            table4.AddRow(new string[] {
                        "Dec/Current Academic Year",
                        "500",
                        "0",
                        "0",
                        "pe-2"});
            table4.AddRow(new string[] {
                        "Jan/Current Academic Year",
                        "500",
                        "0",
                        "0",
                        "pe-2"});
            table4.AddRow(new string[] {
                        "Feb/Current Academic Year",
                        "500",
                        "0",
                        "0",
                        "pe-2"});
            table4.AddRow(new string[] {
                        "Mar/Current Academic Year",
                        "500",
                        "0",
                        "0",
                        "pe-2"});
            table4.AddRow(new string[] {
                        "Apr/Current Academic Year",
                        "500",
                        "0",
                        "0",
                        "pe-2"});
            table4.AddRow(new string[] {
                        "May/Current Academic Year",
                        "500",
                        "0",
                        "0",
                        "pe-2"});
            table4.AddRow(new string[] {
                        "Jun/Current Academic Year",
                        "500",
                        "0",
                        "0",
                        "pe-2"});
            table4.AddRow(new string[] {
                        "Jul/Current Academic Year",
                        "500",
                        "0",
                        "0",
                        "pe-2"});
#line 22
 testRunner.Then("the following learner earnings should be generated", ((string)(null)), table4, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection Period",
                        "Delivery Period",
                        "On-Programme",
                        "Completion",
                        "Balancing"});
            table5.AddRow(new string[] {
                        "R01/Current Academic Year",
                        "Aug/Current Academic Year",
                        "1000",
                        "0",
                        "0"});
            table5.AddRow(new string[] {
                        "R02/Current Academic Year",
                        "Sep/Current Academic Year",
                        "1000",
                        "0",
                        "0"});
            table5.AddRow(new string[] {
                        "R03/Current Academic Year",
                        "Oct/Current Academic Year",
                        "0",
                        "0",
                        "0"});
            table5.AddRow(new string[] {
                        "R04/Current Academic Year",
                        "Nov/Current Academic Year",
                        "500",
                        "0",
                        "0"});
            table5.AddRow(new string[] {
                        "R05/Current Academic Year",
                        "Dec/Current Academic Year",
                        "500",
                        "0",
                        "0"});
#line 36
    testRunner.And("at month end only the following payments will be calculated", ((string)(null)), table5, "And ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection Period",
                        "Delivery Period",
                        "Levy Payments",
                        "Transaction Type",
                        "Employer"});
            table6.AddRow(new string[] {
                        "R01/Current Academic Year",
                        "Aug/Current Academic Year",
                        "1000",
                        "Learning",
                        "employer 1"});
            table6.AddRow(new string[] {
                        "R02/Current Academic Year",
                        "Sep/Current Academic Year",
                        "1000",
                        "Learning",
                        "employer 1"});
            table6.AddRow(new string[] {
                        "R04/Current Academic Year",
                        "Nov/Current Academic Year",
                        "500",
                        "Learning",
                        "employer 2"});
            table6.AddRow(new string[] {
                        "R05/Current Academic Year",
                        "Dec/Current Academic Year",
                        "500",
                        "Learning",
                        "employer 2"});
#line 43
 testRunner.And("only the following provider payments will be recorded", ((string)(null)), table6, "And ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Collection Period",
                        "Delivery Period",
                        "Levy Payments",
                        "Transaction Type",
                        "Employer"});
            table7.AddRow(new string[] {
                        "R04/Current Academic Year",
                        "Aug/Current Academic Year",
                        "1000",
                        "Learning",
                        "employer 1"});
            table7.AddRow(new string[] {
                        "R04/Current Academic Year",
                        "Sep/Current Academic Year",
                        "1000",
                        "Learning",
                        "employer 1"});
            table7.AddRow(new string[] {
                        "R04/Current Academic Year",
                        "Nov/Current Academic Year",
                        "500",
                        "Learning",
                        "employer 2"});
            table7.AddRow(new string[] {
                        "R05/Current Academic Year",
                        "Dec/Current Academic Year",
                        "500",
                        "Learning",
                        "employer 2"});
#line 49
 testRunner.And("only the following provider payments will be generated", ((string)(null)), table7, "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
